---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.2.0/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: photoprism
  namespace: photoprism
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      photoprism:
        containers:
          photoprism:
            image:
              repository: photoprism/photoprism
              tag: latest@sha256:19fdf0d52676d07abe63376a3b2d07779cac010a1bfca563af11968abd2df218
              pullPolicy: IfNotPresent
            env:
              # https://github.com/photoprism/photoprism/discussions/2799
              UID: 1199
              GID: 2316
              TZ: "America/New York"
              PHOTOPRISM_ADMIN_PASSWORD: "${PHOTOPRISM_ADMIN_PASSWORD}"
              PHOTOPRISM_DISABLE_CHOWN: "true"
              ${PHOTOPRISM_SUBSCRIPTION_KEY}: "${PHOTOPRISM_SUBSCRIPTION_VALUE}"
            probes:
              readiness: &probe
                enabled: true
                custom: true
                type: HTTP
                spec:
                  httpGet:
                    path: /api/v1/status
                    port: 2342
              liveness: *probe
              startup:
                enabled: false
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 4Gi
    
    service:
      photoprism:
        controller: photoprism
        ports:
          http:
            port: 2342
    
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          nginx.ingress.kubernetes.io/proxy-body-size: 4G
          hajimari.io/icon: arcticons:photoprism
          #hajimari.io/icon: "image-album"
          hajimari.io/group: "media"
        hosts:
          - host: &host "photoprism.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: photoprism
        tls:
          - hosts:
              - *host
    
    persistence:
      config:
        enabled: true
        existingClaim: nfs-photoprism-storage-pvc
        globalMounts:
          - path:  /photoprism/storage
      originals:
        enabled: true
        existingClaim: nfs-photoprism-originals-pvc
        globalMounts:
          - path:  /photoprism/originals
      import:
        enabled: true
        existingClaim: nfs-photoprism-import-pvc
        globalMounts: 
         - path: /photoprism/import     
    # try this instead of using manual pvcs
    #   media:
    #     type: nfs
    #     server: expanse.turbo.ac
    #     path: /eros/Media
    #     globalMounts:
    #       - path: /media
    #         readOnly: true
