---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: photoprism
  namespace: photoprism
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        pod:
          dnsPolicy: ClusterFirstWithHostNet
        containers:
          main:
            image:
              repository: photoprism/photoprism
              pullPolicy: IfNotPresent
              tag: "231021"
            env:
              # https://github.com/photoprism/photoprism/discussions/2799
              UID: 1199
              GID: 2316
              TZ: "America/New York"
              PHOTOPRISM_ADMIN_PASSWORD: "${PHOTOPRISM_ADMIN_PASSWORD}"
              PHOTOPRISM_DISABLE_CHOWN: "true"
              ${PHOTOPRISM_SUBSCRIPTION_KEY}: "${PHOTOPRISM_SUBSCRIPTION_VALUE}"
            probes:
              readiness:
                enabled: false
                # type: HTTP
                # spec:
                #   httpGet:
                #     path: /api/v1/status
              liveness:
                enabled: false
                # type: HTTP
                # spec:
                #   httpGet:
                #     path: /api/v1/status
              startup:
                enabled: false
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 4Gi
        # pod:
        #   securityContext:
        #     runAsUser: 568
        #     runAsGroup: 568
        #     fsGroup: 568
        #     fsGroupChangePolicy: OnRootMismatch
    
    service:
      main:
        ports:
          http:
            port: 2432
    
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          nginx.ingress.kubernetes.io/proxy-body-size: 4G
          hajimari.io/icon: arcticons:photoprism
          #hajimari.io/icon: "image-album"
          hajimari.io/group: "media"
        hosts:
          - host: &host "photoprism.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    
    persistence:
      config:
        enabled: true
        existingClaim: nfs-nebula-photoprism-storage-pvc
        mountPath: /photoprism/storage
      originals:
        enabled: true
        existingClaim: nfs-nebula-photoprism-originals-pvc
        mountPath: /photoprism/originals
      import:
        enabled: true
        existingClaim: nfs-nebula-photoprism-import-pvc
        mountPath: /photoprism/import     # try this instead of using manual pvcs
    #   media:
    #     type: nfs
    #     server: expanse.turbo.ac
    #     path: /eros/Media
    #     globalMounts:
    #       - path: /media
    #         readOnly: true
