---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-nvidia-device-plugin
  namespace: flux-system
spec:
  path: ./cluster/apps/nvidia-device-plugin/nvidia-device-plugin/app
  # dependsOn:
  #   - name: cluster-apps-longhorn
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
