apiVersion: v1
kind: Secret
metadata:
    name: mealie-mirror-secret
    namespace: radicale
stringData:
    config.json: ENC[AES256_GCM,data:y7F/tL2VwUvdvBAgNl07mmyBYYBbJziA7Igut872CVO79MQn9znoIXjuWcSCsK2pWnygAq8iY1a6qfSoAutdWEiU9kCNsKoWaqV0WUu82UkOXELW52N4/OmnXN+VRrDVOp4RXQe3iio5RdfJ2NY358wOU1gtcIAqhAwWWf3/KXXGe5EPhcjB7IYSdi+d0iTxJmqTBxA2iuXVwx/VebtANG9sE9LTCH01C5GgN+d0z6S3qBynFs7NnANqoigw,iv:VRGZOo4foroUpyMXR7hdzXu+qmx4SgTd2qpOSwFbgyc=,tag:9treh2rBjKDS4/m7qoLrpw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-11T22:21:43Z"
    mac: ENC[AES256_GCM,data:QfDzpmm37m8IbF0/payHpF8cOEljO3cuR1izWQQBqBm7gWGRNMMCa9yDWzWXSh0fIhYTcEmEdB8fQLzi3W/6pTyP+1/orG/tIsnYyPjw8lLfyegoPP5DI+DSPx7+8L82yGu7sp43CRJMSBeYh4jAdaBY70d0kaXSu7rcl3fzJpU=,iv:UE6O9T3RxHMTjT8w7UIQ/jVYYjr6YWr7VD+BGYRf1JI=,tag:O1UX+2bvS2olAy5KgDCHpg==,type:str]
    pgp:
        - created_at: "2026-07-11T22:21:42Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0dSZMvnEisuAQ/8DD5SodXBB0+yzbJjysOiEv+3MejF8zp61iQo2BOgEGDq
            o9fVUt3F1N1JrEKhDTC4QRE5l6JJxCdFO0jnWoI43DvrXMuv6yL8Ih6WOETbo7bL
            t7Tx6Q3ov4xFHZ14Ji3yqtC4x/VcmCu6EUImv3EjjV4ur/pbvKE93sbOaKF1A7Mh
            J19sJMyygmi+lTpV/36sOn0k3MpxEh1i0AN6ugoM4SNbKrjEf+/JgJsA/fOfFPh3
            LoMFg+OjdDz2k6puuJMn//mZaQ+GV0bvFgIpLkIiUT0E/3b6f0DPZ7JpP3VvH28F
            z2armdXwlprCNEV3VsgFufcLJqBkZOQCH4qV9KIDD9OmdWpAQWc+MXTjMKVrguRv
            UEm/emyq47iDzm9vVGxjvtPgE7gIbqUyPHqe7gdXDsxgKdcVWNCzUVXgJ51fdWZc
            ZXV1Kpb7RH35FPJ8epRAK1cEHd16RKIMms/2xJ02piezjZb5nCsCY1ylD50k+8al
            XOevxfpnNamiJZcLJXIUCljgYZnU58fVskirkzoadSqwWP8mEyQBLzeEfLs2GpO3
            lAVcRuJyCKaX78vARRCLQ2XEDynmdDNU97mOF5YSKKEmfobBm+ylkYnemRyT20Ns
            xX+mpGIVVGyMRo0j4nMA1GPyeI9J67BOisA5m+UES5YZqrvapAXKCpiebH3i+6PS
            XgFoTeYLgpLk6YJ0KhkrwLrRBlv1Z30kCGMUXn2kEerB9HCfvMf2gHEiZecyhBu4
            llBGQN3b6C6qNiiQYbSXgbcG26TMbCVUGCpoyy9IzQ0NfqOJlrZ3wZsqPl6J0QY=
            =dQvg
            -----END PGP MESSAGE-----
          fp: 1DBC3ACFDB8B1DF2C44CDA23996024D3718273FA
        - created_at: "2026-07-11T22:21:42Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxbwxdi5IniFARAAnV2DNOjuHpPwK7wqJqvPco/+HAleO6/MKhX4Gp65gMky
            Ukq9hQ+zOPVlvCjzl4RBdLYmWH91q/sol5Nac//WYHwyHE2QqlXOe6nJ7QCzfvxl
            qP7L6pBGzvW9X4hh47uUgNOV82c4cyeGAukNbQFAhjop9otOPh+nIM3PYipj6ZR8
            2yjvsjkKktRHLPqL36z/SlGEHWewWINMUAhGv4STMN/7ip+eD/u6KFPmczd/gimE
            oC37Kx73i11uvXldNDaE/UqhBlH3rX/t4gRXkOV9COD01EWBqeFtsON766YPIfaD
            JyDH0dIZj/XxRfY0AQ2dcFADuf9Pdpt70LcZnCOcH/thlPcFoCSvYajwqWuO5rO6
            guGkE2La5kITOWeSaxHtwRwZuUATxnlMf7rvxXjpEboFhX6k2vxBTfTUSKN5Qw2P
            exsxlQU9jCb8a3xHUcgR5S6lodkpifzFpW/ob7VhP4tOnEt6zbBQrp32ZztbnfU9
            T3HAvE0ijhHD3vEq95wvvb54VIVz4126czrR/xWB1Xr78snau0UOBAerWNhoa86K
            LHLnZBf9aGZJ5WhAdMKlLAd4qERMyZ/T2X2bFWfjDRlwQ4l+RWUXf4NlqR5nXcQv
            kOLefWyfxV8aI6Jo4p8VwKSFgbvbQyn6RGCbuBZlPsrvr/C54CQ8B0ccARQmMZHS
            XgE2VFCpUTsp0HgC7iU9j2BlRwvYZMXCzy5eXLMch3dpbXpxfWnciD82hvSGRZaz
            MafP/N39QFxAUpoXs+GpHEasbKGIKEw799kBjzcU2kYPcLJsiaOCo+t8TtL6TG0=
            =hLEH
            -----END PGP MESSAGE-----
          fp: D9F3AF2D9762D61A974DCD3E7B318B162A7DEBC9
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
