---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nf-piper-pv
  namespace: home
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  mountOptions:
    - nfsvers=4
    - port=2049
  nfs:
    path: /tank/appdata/piper
    server: "${NFS_SERVER}"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-piper-pvc
  namespace: home
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: nfs-piper-pv
