---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app wyoming-piper
  namespace: home
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  # dependsOn:
  #   - name: rook-ceph-cluster
  #     namespace: rook-ceph
  #   - name: volsync
  #     namespace: storage
  #   - name: mosquitto
  #     namespace: home-automation
  values:
    controllers:
      wyoming-piper:
        containers:
          app:
            image:
              # repository: rhasspy/wyoming-piper
              # tag: 1.6.3
              repository: ghcr.io/slackr31337/wyoming-piper-gpu
              tag: v2025.08.0
            args:
              - --voice
              - glados
            #   - --voice
            #   - jarvis
            env:
              TZ: America/New_York
            resources:
              requests:
                nvidia.com/gpu: 0
              limits:
                nvidia.com/gpu: 0
        pod:
          nodeSelector:
            gpu: "true"
    service:
      app:
        controller: *app
        ports:
          whisper:
            enabled: true
            primary: true
            port: 10200
            protocol: TCP
    persistence:
      data:
        enabled: true
        existingClaim: nfs-piper-pvc
