---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-loki-pv
  namespace: monitoring
spec:
  capacity:
    storage: 30i    
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /tank/appdata/loki
    server: "${NFS_SERVER}"
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: home
    name: nfs-loki-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-loki-pvc
  namespace: monitoring
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi