---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-nebula-loki-pv
  namespace: monitoring
spec:
  storageClassName: "nfs"
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  mountOptions:
    - nfsvers=4
    - port=2049
  nfs:
    path: /tank/appdata/loki
    server: "${NFS_SERVER_NEBULA}"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-loki-0 # nfs-nebula-loki-pvc
  namespace: monitoring
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  volumeName: nfs-nebula-loki-pv
