---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-loki-pv
  namespace: monitoring
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /tank/appdata/loki
    server: "${NFS_SERVER}"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-loki-pvc
  namespace: monitoring
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  volumeName: nfs-loki-pv
