---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: loki
      version: 2.8.1
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      interval: 5m
  values:
    ingress:
      enabled: false
      annotations:
        kubernetes.io/ingress.class: "nginx"
      hosts:
        - host: "loki.${SECRET_DOMAIN}"
          paths:
            - /
      tls:
        - hosts:
            - "loki.${SECRET_DOMAIN}"
    serviceMonitor:
      enabled: true
    persistence:
      enabled: true
      existingClaim: nfs-loki-pvc
    securityContext:
      fsGroup: 2316
      runAsGroup: 2316
      runAsNonRoot: true
      runAsUser: 2316
  # TODO: https://github.com/grafana/helm-charts/pull/700
  postRenderers:
    - kustomize:
        patchesJson6902:
          - target:
              version: v1beta1
              kind: Ingress
              name: loki
            patch:
              - op: replace
                path: /apiVersion
                value: networking.k8s.io/v1
              - op: remove
                path: /spec/rules/0/http/paths/0/backend/servicePort
              - op: remove
                path: /spec/rules/0/http/paths/0/backend/serviceName
              - op: add
                path: /spec/rules/0/http/paths/0/backend/service
                value:
                  name: loki
                  port:
                    name: http-metrics
              - op: add
                path: /spec/rules/0/http/paths/0/pathType
                value: Prefix
