---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-authentik
  namespace: flux-system
spec:
  path: ./cluster/apps/authentik/authentik/app
  dependsOn:
    - name: cluster-apps-longhorn
    - name: cluster-apps-proxmox-csi
    - name: cluster-apps-authentik-database
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-authentik-database
  namespace: flux-system
spec:
  path: ./cluster/apps/authentik/authentik/database
  dependsOn:
    - name: cluster-apps-longhorn
    - name: cluster-apps-proxmox-csi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
