---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik
  namespace: authentik
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:14.8-6
  inheritedMetadata:
    labels:
      kube-image-keeper.enix.io/image-caching-policy: ignore
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
    storageClass: longhorn
  superuserSecret:
    name: cloudnative-pg-secret
  postgresql:
    parameters:
      max_connections: "600"
      shared_buffers: 512MB
  monitoring:
    enablePodMonitor: true

  bootstrap:
    initdb:
      import:
        type: microservice
        databases:
          - authentik
        source:
          externalCluster: authentik-postgresql

  externalClusters:
    - name: authentik-postgresql
      connectionParameters:
        # Use the correct IP or host name for the source database
        host: authentik-postgresql.networking.svc.cluster.local
        user: authentik
        dbname: authentik
      password:
        name: authentik-postgresql
        key: postgresql-password
