apiVersion: v1
kind: Secret
metadata:
    name: radicale-secret
    namespace: radicale
stringData:
    users: ENC[AES256_GCM,data:tosVDwQ2Mm7YdWKN48Bm7DHdVHRl4PbSzeXVIrP5kVK8VJqCRZR3PnQoDv/iuHNXY0QmXauOkIoV5k6W7X4OUlhWFTz3e7JEmld3MqOJaZVcX1K3DjAMvCQcCbcq+/Ptxj8nQ0FtPXFQwDXfZo+S7IPui3EbmaEWlGHqcK5w1O34AGdSMoSP9s+/KZDwwZV9Cyw2wFxLiZjjIQFQkJKAGFomPNnqT8ag5hpSZkBWkMRwwE5oPGDofs7DMH4i9/AgCobkkWHgXeXZcaetqK8WI8nSwUg4aTdWzpKUsq5HQ82094GuIL1BUetAP6jHZ2/mgHrHrw3gUwzNFB6jhLnV/5jl0RoHidoutjLepDaWbtbJT4AvFG7cKeYD/v64uvJqSikBR0fixRXK7S6oNzFjQAKXoBYVFSHZuulY91G7vNTVcKQXyshX98DAEUU0yW3r,iv:iRTINSjD3mrltcmA4hxI1DSN74YMMVpaBs4WVqQsiKE=,tag:AsLhwci81dZywlzwYbiOOQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-11T15:38:54Z"
    mac: ENC[AES256_GCM,data:mC64RDXWT+WG6cZbdogdOHzO6wg49/W8KKVdEtafD/e3PfblszOBLF//QZ+wc9lGbzkKCfJdH4YLsowTRXvhBgNoNDSPKJGHpq6Spu7l2TGIakRhusLpQvwNsi1o/7mdCEiFmQ5/YrJKrPEiugTUA0pOlMCw7P5bU8eB/VXlAYU=,iv:JQKP0LV2jDjWCG+zisEJ3u9isHtbdJIx3ge3acGCW10=,tag:xmPkEED6qsdNlD/v++HNCQ==,type:str]
    pgp:
        - created_at: "2026-07-11T15:38:53Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0dSZMvnEisuARAAr3LJvsOCsTANZTetC4uVZ8ZcjV9o7L6BJYeh0bw/PXmH
            EIUdwUImn4i9lq5vxJ2NAFGLaYeyYuGvYFMTXzpLCDJFjtml/rf1sMyVaO8o1ud+
            m1hFFoKqlnIQMK6epqb+JAd3yYq/m49s1pRCD7T8hjU0nCiv1jMDloXnu7D+hXkr
            EpqZB0hFJ7kkAOZvXu2kYWZAAMOf4Eujvhd/9N+YkA9C2HSvfCfu9QTmIsNNl5tq
            GefLZupWKUxbcfKikGixYyurj/bnP3nTaAJtunWVww879RpxQDHeQLwOlAiLw1Ik
            4DLtUtxB5EQ+2xXhswvuzIBKhIS6xIMlPdqI7UXPInqJd7KsEWomifL7nicEQTU4
            9+ozntDV+PyLxSYsa0IcKLoS2D/9LjdKwOhEmKuqUy9NqoII67cpVTg5ZqbkFU8i
            B0mSFUISM2oPCra8XmNp5/RoNpEo7trj61U3RH2buQ9QzWsBUnP5j8DyS+wsLhE+
            WFlTtvTkKrO0p7/9EF0d996DogCuoXl8n41CGDRkt5E+PJiMH3pAzlFLEw+hu7h0
            RVvAlPtdiU1AgJkIxAG/KE7b2Uf5COJHiPsfwstUjdS5EKvsYty7QGgIVSCcEK6o
            bTRIhcr6KTVbRXismWl2tW31yvvvkHhcfazn7O3uFnEQsQ4VUHhdcRgXrwlhLkzS
            XAGN4f5axRchlGZVz5sFSiPyavDsWJwZAjInzambyFGVlOz3n/XwBCvRUlqCK6m7
            MSvZ4+uvoa4VScb5KWHfeEZVdbkEto/bvzS7DKNunZvRjayrqGlgYRiCAnJ7
            =/ARC
            -----END PGP MESSAGE-----
          fp: 1DBC3ACFDB8B1DF2C44CDA23996024D3718273FA
        - created_at: "2026-07-11T15:38:53Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxbwxdi5IniFAQ/9FHltauR1juOXKHsHx6hkk5h5vqPeFhqhw5haVDh2D+KW
            jyXuU+r+lYumDJ/xw/nEuy0R628ZSiHsSYJkcD1Z+BC7ptOcCIZMMqE+8Pi5DhXA
            aQocYyvOMjvzSY8L7BSkc0NDaRUlfW7r1CLXgS37Fzqdffk9+2747xsHfa45Nk3y
            Jfa7H3CIFhzIB76c2qRUYvKjSRvQT3paJi9S8SmJsE9k8/sryQGc1kVJITprO8oa
            UTgSHyjvGY3wKUY51ZMTZxVTiGLqqLuz6R1cMzls/AVAMrUDpNwQebRdIdQq0EOy
            eQgjOPseoh477sEkxaCWK4OiL5L79fETN11Z6BF0QYvY8PcbFMO6YGYEv3IULFF/
            m9+K6y+qc5dCnvapAl6Y31CCJxnesjMTsc6YWOh8ybvzGbd7ysuR7kUWul995wgE
            ijc/b7V6ifElWbGUCKFucwfYiD7NwYLxX2IlYcLwZduBiDjbJtLWSME1pakRt/01
            reM7BFQ7esRRtNF408rrwgbbxF4Ya1FhxDCvNE6NjNQoz1ccFskbOA9Sohq5AKkS
            E1gN8HhYI+FpV9eY9vi01w6fDHrPk9JFPt8z/ATh0lm+Ld1pPJKAx4glJnIq08en
            BciphBfMzI5CT84pP0jV8vz/m6TVCqr+pxs6CROUGFkSeyxMSqj5Cx8u644bkj7S
            XAHCFwVDyZwYl+kz3bFw2rGtuEw586FRHjogZnycKuB67P5m9w5fQMNQril//Hno
            3UYKS56KePiEvGhrcuu/phgfDYnjkhrquET0WchK2/B8RCih48VZDQYLe8xu
            =CJ/X
            -----END PGP MESSAGE-----
          fp: D9F3AF2D9762D61A974DCD3E7B318B162A7DEBC9
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
