apiVersion: v1
kind: Secret
metadata:
    name: radicale-secret
    namespace: radicale
stringData:
    users: ENC[AES256_GCM,data:cN8Us/AQkMNceU6hAjBfVoLy8UBb+cMHadj5etN6JUeV/T/9FThGWP5Q+VIVJNAwrX2gyIT05issv1suCpIZI0AorXOPXdL0DpS/GuOd5ZN1ifF6QwYL08rUn0eODtTYLHEYLioAREKNdWdIDH75FGkQ4rQpdg1kAz7L+0UfUxHxF8pKUwzQ68gUpskRVOHYQ8EkSLEdxyJVghP0CL5lAchqioycd6ZqOo70TA30iU03fEOTg4EwAj3LILKTa09I+fhjSyl5mA2R0ZQiCWcvJLV1DD3yhZ3/AoGgnXTlO1ALA0+QysyrzIT83sz12TGS95+bheNS0T6LNBvlKM5CXzrZDZuhbkMlcYd9yg==,iv:C2khtabKToEdGCONIXPwOWN5ohlvLh/zGLl1ClW1JxI=,tag:8q9/bqiZLMeiMmY8eav2fg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-10T19:58:43Z"
    mac: ENC[AES256_GCM,data:Ru1jysGg2zGeXmba7HbjYo2otfbDBq0fbLr5+GuOrebALUdPdDuPcGbLYMwFjHHO4fCY3pFNKVh95rUW8P0vjzBn3NyGknrmaD78hChfv7V7h8lMZSswsG9ShuTU7k276AijF8pWUdoNHOJQUEKlVI20jRcOz4PdpQFcWibaQlM=,iv:sIFYd1RoEbRTrQreJ4Hi/iIkz5hsWT7YXiv4pjcfkog=,tag:4IBal4bQnCdSoEWOBU2wEA==,type:str]
    pgp:
        - created_at: "2026-07-10T19:58:42Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0dSZMvnEisuAQ//ZOgBo9IapWh8jMDR+Iwnm+P3hLeWFxNq6GkAlVyz6dL2
            Ivm5nFtlfEejL/RSMd22jP5n+oLJaWwlkM1fZXTzvNE7uzIyc9JutPvKokZj+gTX
            mLRMi0GKNZTC/2Zt4lRW8K+VrZrT5F1ZZ8/qArxnwlbd8EUQIUEPqvgdYYADI4VZ
            CS97FWzar0YLZwFt43OOuMBVbYI1jYKbIKRiBiSWRAIieT71EK6HZfPZEMWTGdh5
            Dv9WzBkNaX77cqe4ONV81V2QoiyGY8aOd316f5/Gd8ex6gW16UWldaaQInCne6aW
            VgT0cONJrnM+sOBYbl/67ag+XfLd+SRiepzaulxyH5eRdAMLqYRnypVOO8gPP+78
            7xDO9lTMmrqpiJXITS+FwHc53h8ckYuJey82bPG+4p2qU+GCnWKItQzQX958K2br
            wV/C5T7CL2uXmpgJrrhuM3Gwbi9NwvOXgBrUb+zwnwpAy9GPuM6j2AoHvdL3r6WH
            b0OTtW+5/3ODq8+wZD7QJhjcd4ycMwOhBNiivOkhDPHqr69BjIIzS4C79awQJSrF
            l+aHjNKlwmRUSwsXUQ0IkRJlYNt22I0nCf+vpKRsXXxPMIarebPy79HL8FrQNKYR
            PPsJCKrPgurHFd4Zha+bBpmewz4+Pz6dePj6/BhjoxlnmwaPGPlH080Y0ZXWX0fS
            XgHByMO4RoWMIbsA6XTPaqSlvmb1ZyBydLVzycfdsZljZxvyFqkkxQADHg7DCpw9
            kRmfNc8XYmv3Rq64eYrlzqxSnNAGwIsx+8mYexrqMauxO/39bmnVpz61BpLVL3w=
            =A9GN
            -----END PGP MESSAGE-----
          fp: 1DBC3ACFDB8B1DF2C44CDA23996024D3718273FA
        - created_at: "2026-07-10T19:58:42Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxbwxdi5IniFAQ//We8h4TnfXR7nrR+p/JhzCmg4q6ox2n9hpqTe/Ns6ibOX
            lMr+7vVzQJn4JbxNubjuVrk7n/Y1Bed+3KGcCbVwLWiKavf3oDNBacPD4GgiI3D9
            h50x3kC/POtZNmgnEzhA0t2evY9ygj2LP+5hkXm8S2oHbf0mLLxT1WQTLpkmSdNm
            dRTA9b0+UqCbthI8t0Y6uOt8NkZSPGu2ymHgvFZyInEzyWkTiBh8Sy7h+OUx9DVI
            6223xXatXEw3d/k85ijJHpk2qHLMDkjUMTYv2R5fhgCuYWCzc+Abilv57D5ReaPz
            mb/KGw1rOu8kvfHfqOOggaXSkNvPqXCfWtoYFQ2sslImNBHm0Op36IkexKyqLT/h
            kxpllNd/lR9NLI2KmMr5AoEkCwA3jFxKRAf7H0fBrDNqYviQxoQy06Q5FZ0+VbFX
            HvV9jafPkXN7U+KpMdgarvsjR977Ruwr3fJS+tANIaB5ZVg94ts3d1kp3T2hGY4z
            k14JpBKDmsaZNVNTCTU5N6MiUMQ1hB9J0Z2YEmSNFx2+V29ShWz5U99GHdLA9QmE
            Y/L3N5ruKq4SMasFbiIwECbpDUFS5zrSQFJ+mcI8H4biCd1NwnwmANEgsKbgLyel
            O0oit9AIqtMACIYmxJMqAgcA+7zKVEkWbKc9QbWxVeHnk2zDN6f7iIl94+fcsyfS
            XgF/WXQARDAY1LPxCJvlr0lO63s9V0S3tMXwk/uYv30/w21pk7F9dXMpkO0p7Eqd
            XvKp3avRjUC/fslLogLySYAtq4hSUyrJeTYdf2Ng+zbqfE04g/Nn9r1O1WG2JR0=
            =BX5F
            -----END PGP MESSAGE-----
          fp: D9F3AF2D9762D61A974DCD3E7B318B162A7DEBC9
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
