apiVersion: v1
kind: Secret
metadata:
    name: radicale-secret
    namespace: radicale
stringData:
    users: ENC[AES256_GCM,data:N0f3PdCsZtQTT1p+cqRIpUMkw7WE6nEM6ZgmYy7VMeA5x9JWS3jB4MK/M98s8KbS+5c8H02j1/YWtXG2rwPW7BD6dIw3onuQG7kiKrb3MkS3Pk7bxHQjAjlDBPd0f/sNK6tYYON/PrXBzKcGbc5Q/oDSr8WF+EwlSjqb6+ej7sgUYRAlhGtDDnTYOh57U5El/N2m1VEIxikOKzG7vUoedrJi+RSkdLvJ5gdm3jcZetHrcMx9hfynQM4ihSlGR/fUxjYPw6QTmu4=,iv:7sbJ35d6xuS+u7UJBfGq+znqHwl6XFjRijkWtWjXo/c=,tag:75N1FJ3LTshgaVzaZoIx7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-10T19:46:22Z"
    mac: ENC[AES256_GCM,data:9qIneawFaBFolC6DUILZusXDk26Fkhx8aBPspchzweLnGDLyFaHPueE0C8nMFkN7cphFvMtcycfRNNuy5IjvjisNRxn7rh4PJJk0+sJPCJbVIYIlGDqcdaRjWkh6GJ0BLfipkkPkCcuQSqW7jAbI9Pk+wQbn9AIm9MdVYVaY46c=,iv:mBZWFWRBCpJeeg1+VR0jUZcVnloGWQGoKBreAlHOP+g=,tag:S3EYYgEAOvGp+CYT61XS2A==,type:str]
    pgp:
        - created_at: "2026-07-10T19:46:21Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0dSZMvnEisuAQ/8C5WVSyBuQ4pAhGKAyjNzWv58On2nR+kDy7amK0IMvMoV
            0ZoboUYeFUmJFyuHxZyj+FeQufvw01lQ64mO32qgO+9iaGvk5L0cjWmJV1QbMxTR
            HLAT/yaqYy89r202fz3J75dS7S+GqcAWzfj7709nOANs8Va89t9W1IXlHn5v1j9M
            SYDMk9KhGspiTlBU0s3BUdOUrxqNGEkYcL109MPlOYb6viGCJ3kocqKIOLNBiw/S
            OovH3E43LCHFKQgm9V26ez8YaBJNybH9LBG2VrEQ0TJilRIsjwJeRKZglVYK+mjX
            PPwFsFkb9Od1USB5pQpCN4/APOY7Hnc1rc6Gs63I+e+6IjMWaSZz5TCNg2pyRn2e
            MsgtM53jCxiVJpQuGymXOJTDlchN1qddMKP4EONxiJgAoRYgqPOeyT/tEwG3HuzZ
            74MI+N0JGifS5azW5s0YFfWQj/stZbCNPGbii5lmLJfT4tEMSkY/oQt4mdaLw8mV
            +0yNQQDUyUbzYDHrEncrTkczNdex0ipf/b6oMmv2RkuVYI1JSmFln7jY4WIVOeYN
            28FGvPhI8kxrwAzmLCETDaNYTtARFnBVuJVkiKvNJ9a8VQrE8ILJQlaFRTTZ6Rlq
            da685shN78pJkN5FgoK8X2GTaOa7jmaKHFVJHlw7qwZJgCy072GaVKftJnG/D5XS
            XAE1ZI+gMJiV9hzkmu+yVKdNt9Uq4GqBz8pDTzLTpDugT1H612VnB2sM5uhHg1hN
            gCBChH6ai6ZygErHluhuLRpq2OnGxlN3nEWydnON6PPOrpvpe2XuN0VrQ4xP
            =4z7g
            -----END PGP MESSAGE-----
          fp: 1DBC3ACFDB8B1DF2C44CDA23996024D3718273FA
        - created_at: "2026-07-10T19:46:21Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxbwxdi5IniFARAAlVXfugLiPb8YPwuQ5ZbMD4TGhgK4ioSX6v0i65t6YWqo
            9gchiF0ZkzW3kUVQcHtKRO2Me4HhbK3IBrWI5jK3Br5RmEoSfRe244KRtNG3FL9B
            M22paxanq4OQYmMdNF0JODikIQqX/7SOehCH5QKY8SwGejZj1Q2c+LH3zehsczSF
            v8CHPbMEgw0Gc1axGdmPAvTWstuiJhFoymVFd8pvqVgcSVUbR4LsGYUTFhiugOUG
            eQVUsKoOuQhmHrcDUI3jMsAidYRWusX3pm7WF2MziXY9uV0BJpHE4U98W0DCnMIc
            GY/1eY39o8gTk5MXBqqPNteLPSs/SfILhmh1oI3N7hCPAIYTUQJSI0bt1PPTYDo4
            SpcFYKLIp/zd04HeGF30epFBsRWkRorwtBbG1H0mwoupy5WPbbnj89Fes/Czm5Kh
            VZYUdGbSxbCq7Kovw/wibiobagKsj2PdhYPsdkmclrHUZZUnvUoECB3rdxkMQS8j
            da2Zt7iCs45qeewZo33J7B2cPSEtmAI7K0tijWAgnEqxrlDb3EdsO0McZb4SH1sw
            Rw57a/VGB6Oqvd4+EbaWKpUSiLhukC6uFmcbKoi+cQCCUf3xVopqjPbdUmqLIzg7
            fyuYaH7IszlYtGjF6vvWDITd5vQADrgz9tp9vk5jx5BeN2QdQPmLQj5hKI487YjS
            XAEjTRtjyU8G6AzWk8cVDK1/dNRuE+Gc1OhkF7JZZss2BnFXyXHnIAM+QPkoSL4a
            k5z04gZnZ+v11rbPhkWIlowRp9HwtdA3dwMH2azNAY/xtD/r+N33L6SX5ZUh
            =OLDG
            -----END PGP MESSAGE-----
          fp: D9F3AF2D9762D61A974DCD3E7B318B162A7DEBC9
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
