# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.2.0/charts/library/common/values.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zwave-js-ui
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      zwave-js-ui:
        type: statefulset
        pod:
          nodeSelector:
            zwave: "true"
        containers:
          zwave-js-ui:
            image:
              repository: ghcr.io/zwave-js/zwave-js-ui
              tag: 9.29.0
            env:
              TZ: America/New_York
            securityContext:
              privileged: true
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: 8091
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              limits:
                memory: 500Mi
    service:
      zwave-js-ui:
        controller: zwave-js-ui
        ports:
          http:
            port: 8091
          websocket:
            enabled: true
            port: 3000

    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          hajimari.io/icon: mdi:z-wave
          hajimari.io/group: "home automation"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: zwave-js-ui
                pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: longhorn-zwave-js-ui-config
        globalMounts:
          - path: /usr/src/app/store
      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/serial/by-id/usb-Zooz_800_Z-Wave_Stick_533D004242-if00
        hostPathType: CharDevice
        globalMounts:
          - path: /dev/serial/by-id/usb-Zooz_800_Z-Wave_Stick_533D004242-if00
