---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: litellm-backup
  namespace: ai
spec:
  schedule: "0 10 23 * *"
  backupOwnerReference: self
  cluster:
    name: litellm-cnpg
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
