---
# yaml-language-server: $schema=https://kochhaus-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ocis
  namespace: ocis
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-connect
  target:
    name: ocis-secret
    template:
      data:
        OCIS_JWT_SECRET: "{{ .OCIS_JWT_SECRET }}"
        #OCIS_CLIENT_ID: "{{ .OCIS_CLIENT_ID }}"
        WEB_OCIS_CLIENT_ID: "{{ .OCIS_CLIENT_ID }}"
        # OCIS_SERVICE_ACCOUNT_ID: "{{ .service_account_id }}"
        # OCIS_SERVICE_ACCOUNT_SECRET: "{{ .service_account_secret }}"
  dataFrom:
    - extract:
        key: ocis