---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ocis
  namespace: ocis
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      ocis:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 2316
            runAsGroup: 2316
            runAsNonRoot: true
            fsGroup: 2316
            fsGroupChangePolicy: OnRootMismatch

        initContainers:
          init-config:
            image:
              repository: docker.io/owncloud/ocis
              tag: 5.0.8
            command:
              - /bin/sh
              - -c
            args:
              - |
                if [ ! -f /etc/ocis/ocis.yaml ]; then ocis init; else exit 0; fi
            env:
              OCIS_INSECURE: true

        containers:
          ocis:
            image:
              repository: docker.io/owncloud/ocis
              tag: 5.0.8
            env:
              DEMO_USERS: false
              OCIS_LOG_COLOR: true
              OCIS_LOG_LEVEL: info
              OCIS_LOG_PRETTY: true
              OCIS_URL: "https://ocis.${SECRET_DOMAIN}"
              PROXY_TLS: false
              STORAGE_USERS_OCIS_ROOT: /data
              # Authentik OIDC
              # Auto role assignment:
              # docs: https://doc.owncloud.com/ocis/next/deployment/services/s-list/proxy.html#automatic-role-assignments
              OCIS_OIDC_ISSUER: "https://authentik.${SECRET_DOMAIN}/application/o/ocis/"
              PROXY_AUTOPROVISION_ACCOUNTS: true
              PROXY_OIDC_ACCESS_TOKEN_VERIFY_METHOD: none
              PROXY_OIDC_REWRITE_WELLKNOWN: true
              PROXY_ROLE_ASSIGNMENT_DRIVER: oidc
              PROXY_ROLE_ASSIGNMENT_OIDC_CLAIM: groups
              PROXY_USER_OIDC_CLAIM: preferred_username
              WEB_OIDC_CLIENT_ID: ocis
              WEB_OIDC_METADATA_URL: "https://authentik.${SECRET_DOMAIN}/application/o/ocis/.well-known/openid-configuration"
              WEB_OIDC_SCOPE: "openid profile email groups"
            envFrom:
              - secretRef:
                  name: ocis-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 512Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    service:
      app:
        controller: ocis
        ports:
          http:
            port: 9200

    ingress:
      app:
        className: "nginx"
        annotations:
          hajimari.io/appName: "OCIS"
          hajimari.io/group: "Storage"
          hajimari.io/icon: arcticons:owncloud
        hosts:
          - host: "ocis.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      config:
        type: configMap
        name: ocis-configmap
        globalMounts:
          - path: /etc/ocis/web.yaml
            subPath: web.yaml
            readOnly: true
          - path: /etc/ocis/proxy.yaml
            subPath: proxy.yaml
            readOnly: true
      storage-users:
        type: nfs
        server: &nfsServer ${NFS_SERVER}
        path: /tank/user_files/shared/ocis
        globalMounts:
          - path: /data
            subPath: storage-users
      data:
        type: nfs
        server: *nfsServer
        path: /tank/appdata/ocis
        globalMounts:
          - path: /etc/ocis
            subPath: config
          - path: /var/lib/ocis
            subPath: data
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
            subPath: tmp
