# yaml-language-server: $schema=https://json.schemastore.org/kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: radicale
resources:
  - ./secret.sops.yaml
  - ./helm-release.yaml
configMapGenerator:
  - name: school-lunch-mirror-configmap
    files:
      - school_lunch_mirror.py=./resources/school_lunch_mirror.py
    options:
      disableNameSuffixHash: true
