apiVersion: v1
kind: Secret
metadata:
    name: school-lunch-mirror-secret
    namespace: radicale
stringData:
    config.json: ENC[AES256_GCM,data:oS3e6nSnK+bGpGVIbhiEZXH9DdxgnVA0MsyOss4dH/c30I647/psKo3SIqprSkrvmU0xK8w0akOg3TWCzB451fG2O6oeYGL4U0Gljg/6Atguy9RfDf1qpYBll6cnN3mCoL9S7R+wai6jU2Tj710rtF/+E4E5fuWCcZ8GDF1SSt5266SaAVzKetHOlImtnUlsK+9WZ2B8nyv/ATFIVpJzLJJHHzUPTFstIHz+sS9FQWFkKlCDUzzbblDneT/Y48NxLbs806DZmx+rpMFCXZPxQyLW,iv:I+8qUD13vk5eS/4BQYnvjcPNRKnZr5IZIixLgJSp9u0=,tag:to1W9I4BkFD2Qz4qnH1LVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-24T22:36:49Z"
    mac: ENC[AES256_GCM,data:yxuPRwy+91nLG+iLAms8voFJxyJ87d4cc2t6NKQS/dLOEhRglwRBLJciHn6wd1I7XmEeEikAA/x8dtasQ90nTErltaWe7qmh97O9gu8IFq5Zwlo1EsfjfoUalFwg/fAONQpqtv0W8QtnteQl1Bj84mv0uDqLkj6OHDX8bz0WqWc=,iv:1c9J9wpf27ntnZvZ7vYqOF3cHiCoTGj6364UWdG0e9w=,tag:7pXKR5J+JKQQ372oiakO7g==,type:str]
    pgp:
        - created_at: "2026-08-24T22:36:48Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0dSZMvnEisuARAAtQbrmUYzftzTCTcprNc7A8n4ROi6zt3UEcjI2Yy4yPVB
            vsocCCpkvMai7eCxgmciMHion4OaMFvUXmA15sXd9cB2mpXsADvjoVQsV7qGXipp
            ITfo0lqcj+4eet+UKP2UDr+W8vh4GkimvzCXzGyCyDR9qHiF7xCdzOzvaBHbPXiT
            gansez1jCiIIwjI36mwDbQUB398DOALaiRSq6hI295av7WVZeJriJ5QnOZuxbLIk
            Bjmm6L8U3SYgXrCx1tu2IInmNixXPBiWc/k1WCvwcyv7DCP4GpQF99SZda/6pUbY
            PNG38HF17WKqm95Y9LIi3zkkwsaTHOtnLZrSa1AfJUSukxDeH5dvNRf1tUqkNlrs
            LeavSE7d5uaoqQ/6Xkgy+MTyj+VigeIk8TIv9SktAWgipEhgIKXV+AwU/q2jazQ7
            foJRYkhF20/iTIxGx9bqyXfYDVexbQOs5cnvLYRaPUBMRvD7Th2G8HC8zNoibf4S
            3ATpCAIP7pod7f8YHRxULk5GXjPSzGjWru7uLT/MdVFsUbN3ScgRM/aUb9KIG9Bm
            3/6Ce8w+bDC8x8h2npZaAeb/nOejC7Y6cq26LOJIJeRNnE8K6ma2if5COgsJWbQE
            9qe+sT7VcGaZNaTvtisN26pHE9ZzSPYzkRlTJHuwAqMQ+xQLjkmJwZ9ewNxfTl7S
            XgGRwYQYRcn6BDRxsdubDtSuBYZ2A2VJOrWzNVnqcd3/FY9bfe4XcYsF7oS6QnXa
            eP4ytkoX8NcI6TMP4mejGnbuPMUiC+NySZlkDXhdq5XpguKcrXx4VQxGVGW01Ng=
            =UGsh
            -----END PGP MESSAGE-----
          fp: 1DBC3ACFDB8B1DF2C44CDA23996024D3718273FA
        - created_at: "2026-08-24T22:36:48Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxbwxdi5IniFAQ//Qln7l+syhPD/SbJyg9hZwarUaCzMC51If36Y8eGNb6RQ
            Qdkejvw98um9oXywMZ9SW4c6JvFFxqsCNZ5M4qn3Z2F3+wqKo9JIkOmbUriWbSJa
            9ZAGCG5Imh74X+5ZZEgUzysvqpTICISjKtMMMsh+KZGlcLX/XioJ6e0M7FVG759O
            NMVC9U0JsgF0PjlNb4mGVoTIpy7O2Dd2otC8sVA5Fi79WBXZtmw1H6lFtK9tyZ/0
            u8/fiL2X2HgEBfPCvg0n+QfCYqB737bOOOIEB53Vk6AS/eluD6caJU5EsFbbld98
            ceBVN7Pzlh8gmHC1gwWCwp3Pnge4jySrZ3JXocqCc5TdCy4Yt50FwphzcUsuwWex
            DbFmxD42HLrJV54fh9HiTXOxPNJFwSLVjetrPE6nHZNsIDG6xRn+zCd7sdzIbFNY
            USEuUWuIKjnvh08yfVC2pugl4lx2kUorFBy6l6QyJ3lXU9zRTNl64jDzlYsQKV8v
            Jme5KiLWePH9+Y207UxXhTDyq6KMziYl+JcMc7x2IoZP17iiK+BaLwvN7CjZG/FM
            R6ct38eGxMfpjRt57y6Pz6hGHBYs4uCii9DWzrQbZXdJ9XiMtlNYWY4Tu62qSUu3
            t6cx3pHNkawp6tvbv75lqApCX5n+rWqwNAZoYsEolRWVGnwu4NZFQ5fxz/OVQN/S
            XgHwFZEKrN9QsYD7gGF/TBvEjJjzubB0cBfg8MVGF3r+Y+lTCO7OwgbYATpyYbxw
            YFKgsfj7Pg2+YXy7x+mKu0CtuPu8mTYBYifTQHnIFqTdvKQsfscB5XrRd2aTT58=
            =9VZn
            -----END PGP MESSAGE-----
          fp: D9F3AF2D9762D61A974DCD3E7B318B162A7DEBC9
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
