---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword-sdk
  namespace: external-secrets
spec:
  provider:
    onepasswordSDK:
      vault: kubernetes
      auth:
        serviceAccountSecretRef:
          name: onepassword-sdk-token
          namespace: external-secrets
          key: token
      integrationInfo:
        name: external-secrets
        version: v1
