apiVersion: v1
kind: Secret
metadata:
    name: onepassword-sdk-token
    namespace: external-secrets
stringData:
    token: ENC[AES256_GCM,data:rfrLNyMKnoEppbfm526EPCKSuZKNUC7hUZ8nj6t64BW0DllK464WzyHo+EaY2Nt23vPbzeFgU44LxNH0H9GQ4hFYq2s2ru9gNuhR0NeX3MpreGeU5DlxgXesgqnXlG6NXOAhkN1YQKAydEB65OAyh4D9a/1vWby8rlKOIsI4dvtlDdiwhIDcl32e3XLGim5yFJxBBdIY9HrzXXCSxc5CVOJYmxVtMJLIWEfGzXVdpsJU/paeFU90WwRfHmSyJMazjtJOgGIlpz4+dYbEjHH4b5jCsoLIgfpuU6BMsxodk8ULbFbs95WGkN1ircBvJyL8i5HWYbOS2cFPArfEAdRQXhhceuXCKoCdZlmgHB6zo8n22V4cF75HkvsVR51VpVflv04KgwRK3HwHfY39iGENehgq6LoEtL6tY0xgbDt28brbDwLN9+xPCTzocY5r3vvU/VzPAvgKR682NttYVXcDunn66FS1HE2vJVxpmtxZd3L43A5VJGQNdpkDOjRjU+O865IOeFKLkVQWyy2DsMLDYnG6fpoA8YMbvrP9g74gzrqnQK8abkvh5vubB1K307S1lLTYCSp8eS/kfWVMpxkWk0rp1sbnY6ufQVBxikwxDmWxVOW0CkR6OyOvgRrkI3HEinjrZxEjkukmoeQG8JrE/pund+oSvCIGp3dMIQcYAhRViurYiT+f5OJAZkQrboUWWajRfmxpe2BF7vZ+LFDwLQQ5Ab0CGpFzMn1RTt7fQTywNI+VGpjuhOmv2OzKq/g83QD2mTx/zo2tH6Ih63SmnoF6h78x+8fiGeX3a8cfZDUSx6+7lfaon4CdPtEfvNX5Yut+d2utNEOM1L/yZpBP1jC87wSnPJeyUW2tb8Bm/Xd0tf+RZB3lSRGjnEqcbg3uS5tw5EltsCTG7k11prh97nNOzuCXP0qfKjEgcjYqtXTQWP+HHXaPKypc8KUMuBu/YXfvpX+dpNQHEFtWIzBjn4UEvjBh6U1UXVT12/7MJ94psEoarCXH9O5gIMtvNxDR9cstp2izA5ugZUFKp6GOXkKxdV6z0IxlHiF0RnaGy029fWiXqBESLXDoWbTvs4zUylczp3IlF5bqgCFe4CbSnTZ+m7WHxyFQml1ozyGT/7aVYsbl,iv:ropP6z85yg1i239jt0NA51AI9eiK80U5ZR7IXgo+dqI=,tag:LmHiqM6M9HGlnPunlTDwpQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-07T13:54:18Z"
    mac: ENC[AES256_GCM,data:/LG05iJS3qA7icZ6nvBFu/lH454vKDBwBLM5wPGAnxstjtZeOdEOaQ+LUYb1M+1pcc3+BOg/VkXiGmK8KBXdCYTMAPieskOKAsvYmD5SaTfHEBWSh25CFuDfL2EntSd5XJS7BLTm8yRcUbDABp2L58Ra9IBFsum1ZrQPunCZ5Sk=,iv:WT64cGFP+IN7g5Zz+yfNn1bxQMe4u0Hynzz9xBW0ttc=,tag:Ok2A38HVWj1CgMRR8UCmzw==,type:str]
    pgp:
        - created_at: "2026-07-06T19:05:45Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0dSZMvnEisuAQ/+JJfH9Z59inJVyF3zZ1lGlwIUbxIHhWbR5OjC9GntwnDf
            c7Fgsmolagwbx6z/gg+/iF+jVA/au2MbSX+c8SkV2WRCv17VGp5+lYOB1DRq/+t7
            MNZh4xEOqFyEEYXww7dGJBmYldkSTm0jkozbO9pagf5yIJYRhAldx/mC/fygbR66
            j92kjRso+JAEsZonKUEf/AAw3MfOJcZCZcxBDXpPe0OpqZO8rOKnBf4hreaSJ8Pj
            InMS2e6Nzmksxo7oT8JB/7HJ0ZLVYGd1VX+4ZpzSb4nUvi+IcLnrFb7cQ6PHeaRB
            ro/Txvzgz8aHzs3r+hKoeMn/uyxoxW8q0ieY5yjSQKRTFH06mZ2jr6TVLf/hfhii
            Z5sEEpowiRCuoHOFoQw3An2d2pXZi1srbpGlBYD9rsGPnOydZ0RsfBCKTNo8twpX
            +O1SmlDOxUGUFjF6tQPMoAfpaj3rnN24ngqTR7zLoXOZ4quCOeTXPQVAv9CeGTkr
            uX0l6piH2HYvWhcxSOqUQRg7whRdyb7r3FhDtAuEnAVgJDxJBYSP90RNozMJV2Cx
            /EymC1K8K90pZzGKMkxxBA0q6iqAk4rR9Nr38KYGTIhe3qWGy17iytESn/zhpLEb
            UXoNfGAadbkGaqykJP1QtU7EPhJ/rKZTmNE6vYLbrFkrD8AGHyhFYr5JLgcLiq/S
            XgEkrKxic/zxSbt+ypW3DeCHZzuNaiYPEGiz43j8YKVDXikYa1k1Al9m/C6NTdSD
            M5B4BkZ6ge7m5AjY7w8dDaBlb5Zx6JGk6qqLllBVQEs5FnZhQYgs+0OVTWPoCJM=
            =r+bX
            -----END PGP MESSAGE-----
          fp: 1DBC3ACFDB8B1DF2C44CDA23996024D3718273FA
        - created_at: "2026-07-06T19:05:45Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxbwxdi5IniFARAAlLlKqUbAV9OJtMVD0aZK84bMAS3E8P2Qh0AO0sxseotJ
            eoiPuL25jb75M+jrAblX9k8dWgievOnxZfeMUdVNjLU2lCTfSj4PTuorsPF8MKk5
            pu5pxioKdP0QB4TAGcps9vDHXj6veLwd5DiXaB6wSRhQwKcYaDcs+d5D2o9cVgAI
            ZU4w5vBOHcCuUhy/CFPeCvrTX+w6HIzruVncYQIYvfmIJPfy9qqOL/gNklRIAxSf
            kGg+YWiofhN6gD8L8rfIPfwmW98EYeSx4fxs4Ni5ToHOS/xM2tBNPhleG5iFJK6l
            Rsc+Na+5z9hcKSaOyMJ2S+hf89eN+dX8T1R/BTH5kzKtUkm4XVPMAkC8sEb68BAY
            WT1A066WVvm5cJgeDE9d9F2Y7eWDSJ8N0OvPezWYI7aD6ZEiLIY1QeuKsKwZK9Jp
            mG7CfaDS0bFmm9Ogws3tAzJE+aq6jLmrbsUm/Ln+fcPQzebDbkoiuJrgwmj2IYVM
            eZ9MsVi2dcxyP5trtVfShRQDTGml9Qy4EzKqEFHqEYURSD8lXq3cHcYZMfMDtwCi
            tbrSdL5dd1coSwt1k2W/W+uxzUdD7289BALxxh+uGJ3jbOVy3lRoHvIGMr67zb69
            pFcmT6k6HMPY3LAmH+9f1VeRpvqSawFnATv22abJOVrKGyYgs6XpdIToV8b5KXLS
            XgEPncnuBRzgcW2bzoalc09l2s/5SGBQAkI9pY19VxtBrvbkT/k6IqEez+0Bk/3l
            QzH6MFAMlawARcxCFJ6/9a6WAIOcmrosL4DWp9Cuqnj8/ZtQU9TtiQytemO1M0w=
            =o9z+
            -----END PGP MESSAGE-----
          fp: D9F3AF2D9762D61A974DCD3E7B318B162A7DEBC9
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
