---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.2.0/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: music-assistant
  namespace: home
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      music-assistant:
        pod:
          # needed for homekit integration? more research requried.
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
        strategy: Recreate
        containers:
          music-assistant:
            image:
              repository: ghcr.io/music-assistant/server
              tag: 2.7.8@sha256:be0286a4cab1d1f0d5a3c3c11b938f0520e20b51477faf3eb8da81d6b9fd227d
            env:
              TZ: ${TZ}
              LOG_LEVEL: info
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 4Gi
    service:
      music-assistant:
        controller: music-assistant
        ports:
          http:
            port: 8095
          stream:
            port: 8097
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          hajimari.io/appName: "Music Assistant"
          hajimari.io/icon: "music-assistant"
          hajimari.io/group: "home automation"
        hosts:
          - host: &host "music-assistant.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: music-assistant
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      data:
        enabled: true
        existingClaim: nfs-music-assistant-config-pvc
      audio:
        enabled: true
        existingClaim: nfs-music-assistant-audio-pvc
        globalMounts:
          - path: /audio
            readOnly: true
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp