---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.2.0/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: music-assistant
  namespace: home
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      music-assistant:
        strategy: Recreate
        containers:
          music-assistant:
            image:
              repository: ghcr.io/music-assistant/server
              tag: 2.7.3@sha256:f25a959247df34ed83e756900b775a2ae26fb24b0cc5fa220b70d03e71395ad7
            env:
              TZ: ${TZ}
              LOG_LEVEL: info
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 4Gi
    service:
      music-assistant:
        controller: music-assistant
        ports:
          http:
            port: 8095
          stream:
            port: 8097
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          hajimari.io/appName: "Music Assistant"
          hajimari.io/icon: "music-assistant"
          hajimari.io/group: "home automation"
        hosts:
          - host: &host "music-assistant.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: music-assistant
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      data:
        enabled: true
        existingClaim: nfs-music-assistant-config-pvc
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp