---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-heimdall-pv
  namespace: default
spec:
  capacity:
    storage: 500Mi    
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /tank/appdata/heimdall
    server: 172.16.1.10
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: nfs-heimdall-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-heimdall-pvc
  namespace: default
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi