---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-nebula-heimdall-pv
  namespace: default
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  mountOptions:
    - nfsvers=4
    - port=2049
  nfs:
    path: /tank/appdata/heimdall
    server: "${NFS_SERVER_NEBULA}"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-nebula-heimdall-pvc
  namespace: default
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  volumeName: nfs-nebula-heimdall-pv
