---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: heimdall
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: heimdall
      version: 8.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: linuxserver/heimdall
      tag: version-v2.5.5
      pullPolicy: IfNotPresent
    dnsConfig:
      options:
        - name: ndots
          value: "1"
    env:
      PUID: 2316
      PGID: 2316
    ingress:
      main:
        primary: true
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          hajimari.io/enable: "false"
        hosts:
          - host: "heimdall.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "heimdall.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: nfs-nebula-heimdall-pvc
