---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.2.0/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: garage-bulk-webui
  namespace: garage
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      garage-bulk-webui:
        containers:
          app:
            image:
              repository: khairul169/garage-webui
              tag: 1.1.0@sha256:17c793551873155065bf9a022dabcde874de808a1f26e648d4b82e168806439c
            env:
              API_BASE_URL: http://garage-bulk.garage.svc.cluster.local:3903
              S3_ENDPOINT_URL: http://garage-bulk.garage.svc.cluster.local:3900
              API_ADMIN_KEY:
                valueFrom:
                  secretKeyRef:
                    name: garage-bulk
                    key: GARAGE_ADMIN_TOKEN
              AUTH_USER_PASS:
                valueFrom:
                  secretKeyRef:
                    name: garage-bulk
                    key: GARAGE_AUTH_USER_PASS
            envFrom:
              - secretRef:
                  name: garage-bulk
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: [ALL] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 128Mi
    service:
      app:
        controller: garage-bulk-webui
        ports:
          http:
            port: &port 3909

    ingress:
      app:
        enabled: true
        className: nginx
        annotations:
          hajimari.io/appName: "Garage bulk"
          hajimari.io/icon: "database"
          hajimari.io/group: "storage"
        hosts:
          - host: &host "garage-bulk.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        type: configMap
        name: garage-bulk
        globalMounts:
          - path: /etc/garage.toml
            subPath: configuration.toml