---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: retrosavemanager-config-pvc
  namespace: retrosavemanager
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: proxmox-csi-ext4-ssd
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: retrosavemanager-saves-pvc
  namespace: retrosavemanager
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: proxmox-csi-ext4-ssd
  volumeMode: Filesystem
