---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kured
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubereboot.github.io/charts
      chart: kured
      version: 5.10.0
      sourceRef:
        kind: HelmRepository
        name: kubereboot-charts
        namespace: flux-system
      interval: 5m
  values:
    updateStrategy: RollingUpdate
    configuration:
      startTime: "9:00"
      endTime: "18:00"
      timeZone: "${TZ}"
      logFormat: json
      rebootCommand: "/bin/systemctl reboot"
      forceReboot: false
      drainTimeout: 0
      drainDelay: 30s
      rebootDelay: 120s
      period: 10m
      slackHookUrl: "${SECRET_SLACK_WEBHOOK}"
      slackChannel: "#kured"
      messageTemplateDrain: "⏳ Draining node %s"
      messageTemplateReboot: "♻️ Rebooted node %s"

    tolerations:
      - operator: "Exists"
        effect: "NoSchedule"

    metrics:
      create: true
      labels:
        release: kube-prometheus-stack