---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-syncthing-pv
  namespace: syncthing
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  mountOptions:
    - nfsvers=4
    - port=2049
  nfs:
    path: /tank/appdata/syncthing
    server: "${NFS_SERVER}"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-syncthing-pvc
  namespace: syncthing
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  volumeName: nfs-syncthing-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-syncthing-backup-pv
  namespace: syncthing
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  mountOptions:
    - nfsvers=4
    - port=2049
  nfs:
    path: /dumpster/backups/syncthing
    server: "${NFS_SERVER}"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-syncthing-backup-pvc
  namespace: syncthing
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  volumeName: nfs-syncthing-backup-pv
