---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: syncthing
  namespace: syncthing
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 2316
        runAsGroup: 2316
        fsGroup: 2316
        fsGroupChangePolicy: OnRootMismatch

    controllers:
      syncthing:
        containers:
          syncthing:
            image:
              repository: syncthing/syncthing
              tag: 1.29.2
            resources:
              requests:
                cpu: 15m
                memory: 64M
              limits:
                cpu: 100m
                memory: 128M
    service:
      syncthing:
        controller: syncthing
        ports:
          http:
            port: 8384
      listen:
        enabled: true
        type: LoadBalancer
        controller: syncthing
        loadBalancerIP: "${SYNCTHING_IP}"
        ports:
          discovery:
            enabled: true
            port: 21027
            protocol: UDP
          listen:
            enabled: true
            port: 22000
            protocol: TCP
          listen-udp:
            enabled: true
            port: 22000
            protocol: UDP
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          hajimari.io/appName: "Syncthing"
          hajimari.io/group: "Storage"
          hajimari.io/icon: "cloud"
        hosts:
          - host:  &host "syncthing.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: syncthing
                  port: 8384
        tls:
          - hosts:
              - *host
    persistence:
      data:
        enabled: true
        existingClaim: nfs-syncthing-pvc
        globalMounts:
          - path: /var/syncthing
      backups:
        enabled: true
        existingClaim: nfs-syncthing-backup-pvc
        globalMounts:
          - path: /backups
