---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hajimari
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: hajimari
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: hajimari
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    hajimari:
      title: Apps
      darkTheme: blackboard
      alwaysTargetBlank: true
      showGreeting: false
      showAppGroups: true
      showAppStatus: true
      showBookmarkGroups: true
      showGlobalBookmarks: false
      showAppUrls: true
      defaultEnable: true
      namespaceSelector:
        any: true
      customApps:
        group: Infrastructure
        apps:
          - name: Proxmox VE
            url: "${PVE_URL}"
            icon: simple-icons:proxmox
          - name: Unifi
            url: "https://${UNIFI_HOST}"
            icon: arcticons:unifi-network
          - name: pfSense
            url: "https://${PFSENSE_HOST}"
            icon: simple-icons:pfsense
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/enable: "false"
        hosts:
          - host: &host1 "hajimari.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
          - host: &host2 "home.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host1
              - *host2
    podAnnotations:
      configmap.reloader.stakater.com/reload: hajimari-settings
    # persistence:
    #   data:
    #     enabled: false
    #     type: emptyDir
    resources:
      requests:
        cpu: 100m
        memory: 128M
