---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app freshrss
  namespace: freshrss
spec:
  releaseName: freshrss
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: freshrss/freshrss
              tag: 1.22.1
            env:
              TZ: ${TIMEZONE}
              CRON_MIN: "18,48"
              DOMAIN: "https://freshrss.${SECRET_DOMAIN}/"
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "arcticons:freshrss"
          hajimari.io/group: "media"
        hosts:
          - host: &host "freshrss.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        mountPath: /var/www/FreshRSS/data
        storageClassName: longhorn
        size: 10Gi

    # podAnnotations:
    #   secret.reloader.stakater.com/reload: freshrss-secret
    # #   backup.velero.io/backup-volumes: config
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
