# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.2.0/charts/library/common/values.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app freshrss
  namespace: freshrss
spec:
  releaseName: freshrss
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      freshrss:
        containers:
          freshrss:
            image:
              repository: freshrss/freshrss
              tag: 1.26.1
            env:
              TZ: ${TIMEZONE}
              CRON_MIN: "18,48"
              DOMAIN: "https://freshrss.${SECRET_DOMAIN}/"
    service:
      freshrss:
        controller: freshrss
        ports:
          http:
            port: 80
          # websocket:
          #   enabled: true
          #   port: 3000
    ingress:
      main:
        enabled: true
        className: "nginx"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "arcticons:freshrss"
          hajimari.io/group: "media"
        hosts:
          - host: &host "freshrss.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: freshrss
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        globalMounts:
          - path: /var/www/FreshRSS/data
        existingClaim: nfs-freshrss-config-pvc

    # podAnnotations:
    #   secret.reloader.stakater.com/reload: freshrss-secret
    # #   backup.velero.io/backup-volumes: config
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
