---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        strategy: Recreate
        pod:
          # needed for homekit integration? more research requried.
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
        containers:
          main:
            image:
              repository: ghcr.io/home-assistant/home-assistant
              tag: 2024.8.1
            env:
              TZ: America/New_York
              # POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
              # POSTGRES_DB: home_assistant
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 4Gi
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: "${HOME_ASSISTANT_SVC_IP}"
        ports:
          http:
            port: 8123
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          hajimari.io/appName: "Home Assistant"
          hajimari.io/icon: "home-assistant"
          hajimari.io/group: "home automation"
        hosts:
          - host: &host "hass.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: nfs-home-assistant-config-pvc