---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-external-secrets
  namespace: flux-system
spec:
  path: ./cluster/apps/external-secrets/external-secrets/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-external-secrets-vault-store
  namespace: flux-system
spec:
  path: ./cluster/apps/external-secrets/external-secrets/vault-store
  dependsOn:
    - name: cluster-apps-external-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: cluster-apps-external-secrets-1pc-store
#   namespace: flux-system
# spec:
#   path: ./cluster/apps/external-secrets/external-secrets/1pc-store
#   dependsOn:
#     - name: cluster-apps-external-secrets
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   wait: true
#   interval: 30m
#   retryInterval: 1m
#   timeout: 5m
