---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-opencloud-test-storage-users-pv
  namespace: opencloud-test
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  mountOptions:
    - nfsvers=4.2
    - port=2049
  nfs:
    path: /tank/user_files/shared/opencloud-test
    server: "${NFS_SERVER}"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-opencloud-test-storage-users-pvc
  namespace: opencloud-test
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeName: nfs-opencloud-test-storage-users-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-opencloud-test-data-pv
  namespace: opencloud-test
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  mountOptions:
    - nfsvers=4
    - port=2049
  nfs:
    path: /tank/appdata/opencloud-test
    server: "${NFS_SERVER}"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-opencloud-test-data-pvc
  namespace: opencloud-test
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: nfs-opencloud-test-data-pv
