---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-nextcloud-data-pv
  namespace: nextcloud
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /tank/appdata/nextcloud-data
    server: "${NFS_SERVER_NEBULA}"
  mountOptions:
    - async
    - noatime
    - nfsvers=4
    - port=2049
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-nextcloud-data-pvc
  namespace: nextcloud
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  volumeName: nfs-nextcloud-data-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-nextcloud-mariadb-pv
  namespace: nextcloud
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  mountOptions:
    - nfsvers=4
    - port=2049
  nfs:
    path: /tank/appdata/nextcloud-mariadb
    server: "${NFS_SERVER_NEBULA}"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-nextcloud-mariadb-pvc
  namespace: nextcloud
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: nfs-nextcloud-mariadb-pv
