---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://nextcloud.github.io/helm/
      chart: nextcloud
      version: 3.5.12 # this version needs to be pinned until flux supports helm 3.71+ -- https://github.com/a-mcf/k3s-gitops/issues/116
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
  values:
    image:
      repository: nextcloud
      tag: 26.0.1-apache
      #repository: nextcloud
      #tag: 23.0.0-fpm-alpine
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/proxy-body-size: 4G
        # nginx.ingress.kubernetes.io/server-snippet: |-
        #   location = /.well-known/carddav {
        #       return 301 https://$host/remote.php/dav;
        #   }
        #   location = /.well-known/caldav {
        #       return 301 https://$host/remote.php/dav;
        #   }
      hosts:
        - host: "nextcloud.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "nextcloud.${SECRET_DOMAIN}"
    persistence:
      enabled: true
      existingClaim: nfs-nextcloud-data-pvc
    cronjob:
      enabled: false
    metrics:
      enabled: true
    nextcloud:
      host: "nextcloud.${SECRET_DOMAIN}"
      configs:
        custom.config.php: |-
          <?php
          $CONFIG = array(
            'overwriteprotocol' => 'https',
            'filelocking.enabled' => 'true',
            'loglevel' => 2
          );
    nginx:
      enabled: false # true
      #image:
      #  repository: nginx
      #  tag: 1.19.10-alpine
    internalDatabase:
      enabled: false
      name: nextcloud
    mariadb:
      enabled: true
      db:
        name: nextcloud
        user: nextcloud
        password: "${NEXTCLOUD_DB_PASSWORD}"
      replication:
        enabled: false
      rootUser:
        password: "${NEXTCLOUD_DB_PASSWORD}"
      master:
        persistence:
          enabled: true
          existingClaim: nfs-nextcloud-mariadb-pvc
    # lifecycle:
    #  postStartCommand: ["/bin/sh", "-c", "/bin/crond"]
