---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 1password.yaml
  - authentik-charts.yaml
  - bjw-s.yaml
  - cloudnative-pg.yaml
  - external-secrets.yaml
  - grafana-charts.yaml
  - immich-charts.yaml
  - jetstack-charts.yaml
  - kurereboot-charts.yaml
  - metallb-charts.yaml
  - nvidia-device-plugin-charts.yaml
  - prometheus-community-charts.yaml
  - traefik-charts.yaml
  - vllm-charts.yaml
