---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nvidia-gpu-plugin
  namespace: nvidia-device-plugin
spec:
  interval: 15m
  chart:
    spec:
      chart: nvidia-device-plugin
      version: 0.14.3
      sourceRef:
        kind: HelmRepository
        name: nvidia-device-plugin-charts
        namespace: flux-system
      interval: 15m
  values:
    runtimeClassName: nvidia
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: nvidia.com/gpu.present
                  operator: In
                  values:
                    - "true"
