apiVersion: v1
kind: Secret
metadata:
    name: proton-mirror-secret
    namespace: radicale
stringData:
    mirrors.json: ENC[AES256_GCM,data:4f6xAFWHwfJLI2eIDWdOJJri95lPZwRs7SEdJA9OZ2G0RFtCKQe8UOAHEy5S7hq9wRN1+c+0M7K7JgI8C7+iKLrkVmAdc/3vM1TNCfAaIMRqC8gaSOOvOlDZryDLpXAOPZKzvhTU3WqjqVN1KN48fjNOSTswcOceEpyqFDSgqLEemjDT4gcBrsYEmplx6HLi63upj3w/nJ6Xdx9M/gpXaAXXIA8vffh629F7818lOhCHsBTLJw42srsCTxR2i/Wp5kdk5vZ7fINkRSMh7Se4FQWa7KzC3EDttF7sCydlUvi5nbwSxbKAQRSPJtgGm8Dbt6/rA5qgIJz1TwCg4XloYX0dK18P3qacVh+Kjd5VqhHPdHXbNpaMP1r5EXVbaZCRPlu+qXhepif2WcD5Z6o6sThdBewm5R4H34SMQLqkiBQ5ZlVyZM4EFAnLdm3iN+mGHrGlVcRgBi6UHNOQOdTl6s8v5GP47/kz/AXO2jNTO1YwVXR4Flo=,iv:Qnow0H8IfecAwKoTz/aT7ZUn9G/ZFTwMDHC00r0bNro=,tag:0AYZG1EsDvIIc4zUq5J6DA==,type:str]
    mirrors-pending.json: ENC[AES256_GCM,data:jNPXwBxyBmaXU78YF7ABKkVR4sgpYVI8NG1bHusjP96dVCfJs0Q7qK2xSs0ktqPkjpUCLiGP0zEH6fixo6XhXJHR5Uv5xwj8WtzOfJX7ApCQ6LE8/3Ku10Z933yMbnCeHB+brj3IZF8JEzycXBuaxx5F31r0IERfnpIxRqQCOd0X99KmeDk98oRPgdkrdzDst3b4vVPL2tswrTHRp/O09G6Ri+M/WoXaddzg,iv:OBrmTfyOamyo4EAmpthOo0vdIiVCk68Psid8Y2SRx+g=,tag:/Qw0Qjs3cKMekp46U/xT+Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-11T21:54:32Z"
    mac: ENC[AES256_GCM,data:Ln+Zvpi9YYypspKFMsM9ZeP7iEsAQM/0kSa5qIceSCHPDIly/nWs5154c8mtnh1W15mSsegt81S6dzNwmpGZZihe6gKRAUpJ7npDsoGzh/vUmXXmLiEwyRSUMIMu4rdWgywYW7r/X4dJdYEYY1JrsI0HWFh0c87etl++DPbyg90=,iv:liHe2CkbYv8SFF06be9Vrtep+o6Gkxwe3Sfb+v5OGjo=,tag:AaSxHcrpL2H0eJdai63kjg==,type:str]
    pgp:
        - created_at: "2026-07-11T21:54:32Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0dSZMvnEisuAQ//fWattHDY+UP/x1QrIxAzG3zuReiwyiyOCLTM3ux79IvO
            GZQ4AYK4ZlWL3G42s5necAZQp6LE5vUVmBbAKH9sPGN/GygSTIvwv54fIl/6TEiy
            SauFhtG1DCcrXYde9+ubDhBQNhtsd/942VMLD5BDkby+IT+Wod5q92LgQxbTjM3e
            V8nNBG428X7tAT9snbt79Z7PKtfKWKtYL77USmTAkZKpRACAKs/UOBDNoX1tL3Kn
            YTpq5mWl6nAVJwhBMUdhYfHEjp4mXBMVO+CvYQKxt5+yKXBvP7APUZQgtRnlsiMk
            IZRorLUPxWYRvMcWnx61nz+af7ESsZCdKX+624jDettaABT7h7visDaJlE8HP5/p
            vRVS39a3sEMTvJf8QJFod3RRNHv0+G4O1T0g+0G8hCvM5rtILApi28lH4uosvgg7
            w/RdiGO8YCpHAlHMgeyfU1otVcB2g+WrC22jZR9+h9E87GdNswsKnH6JVv5HJ8Ix
            XWS61wT8YPy2sARYgeAN0dYrEvgIUrLucAJTunEVko8PanCnyuWDo1t+iCWOlpzn
            aRih1Rj+rAyIZH77tvenk8uKFRL8GQKCPCbM0AWR0oJe9z0A9Udz71R0LwZhfTaH
            fQdlqDSRzvv5ZeE7lbXgxTM5C8KUetgmc1JoASCTBLc26e7LxMFHtspyLD5L79PS
            XgGc/YlOTo3CnySYcvw3MOSmncv8ezXN9pADixHQrEP9gYZ2U0pMriwgY+xoOLNm
            OovwQx4Ed7FtizKpPFfoRqGz8ViavAMDaG5riXW2klmqufSqAfnFZehM2FOg0QM=
            =fusP
            -----END PGP MESSAGE-----
          fp: 1DBC3ACFDB8B1DF2C44CDA23996024D3718273FA
        - created_at: "2026-07-11T21:54:32Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxbwxdi5IniFARAAsatsDA4ebhl695s9OL3L41yKlcYDiI+1Vo+6yjP6h/w2
            TBZXdIUB3q/P+NzdiwIdx0Mc6w3osO4thy7NOlHU1nBqfrrw5Gkv63Efe4Yn0KfJ
            5JbjnTbJGb2oiC999XT420nOxr1ExAE/HS/dbKt6fS7MlhDHka7+lNTupLUCaPA+
            7hCUp0A/MGyvIeaspyUvOcQx99XB7uRa/JkumDnEiUpdz4X3jJKVNc+wmeTdQYEw
            Jk7TO35s3k534WDfXNnKPDMGEu92q+cx8Rjc+uLlWbTrbQxmqvUaaopQFTmRUQ02
            djG3XANPmV+b4YhLLQsML16wmpgEEnEV69wM85jFDWw0zPLWnGcEr0r/KFub3ZhT
            CbXUJ8MrbWVnJhnfe0qAg9fo6emENc8iHTA1S6xABS+iaUoXyY6IK0O1GvUgceEb
            fF/eBW0hcnViugcKoGOGNS7dOZFg7gH98JQ2xr+I6nS7EA/idjcc81hbXPIx1VcP
            ohpjBiw3U3ffFm63oFb8fSGrw8NW2oa0rWC7mtQKdixwNKTQ9BmINC4aPoQV9QR0
            jc6I75n2HT9CBJHtSMlCTGZ4c1M+5KxKi1peKVNdfxyZ6laRiIRkvcjr59mmjn6r
            Wp+iDy5RZngPpBO+aemYygp4XF7IH/0mddP70IZGyLCvawHmwED8Dqdj4sSonnTS
            XgEfGkqvl8tstS5iArW59JIlz1I6npfC/YZTf00L6eKPbDkEhlfju5X46I/OUake
            oteCPRtlL+dhFLmFPG+LQh4GKWrRTz7q+DLa/rcQtvzfVFdb/t4tRiBGY+GRdkg=
            =ev9Z
            -----END PGP MESSAGE-----
          fp: D9F3AF2D9762D61A974DCD3E7B318B162A7DEBC9
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
