apiVersion: v1
kind: Secret
metadata:
    name: proton-mirror-secret
    namespace: radicale
stringData:
    mirrors.json: ENC[AES256_GCM,data:x9Gn9eFC+p7hU1/pfa4nibufi6kCI0lHNAvvsS5qKPp0NWdgQiBh8Z5h0W67P46r9wKsxVArSfUc9UFEhzciJo83ih4OXWHaow0nU4q1YpW0BH6f5uI4Iu69wKc3B2FedTOBrF6f5xo1Rxmmn82dmUNEa52uqar2IhA6T3HBCodvcpBonKfE0bEuIr09BfIWXeilxD1O9sZz8hvamncZyrYW3Fw6s9yoVrbD+fKn/dVXuBar0hxLLUM/VrGC+TAwtrgwK+W7MvT8/ZiIFkN2tF1aaIBJfkTt5EiER+M2bbd26gF1mhyv1WDKwffKdkx+P+jI5WQs8dOGPmClMc+sj9mWZFDoEPgkzZyhsMsGFR0DwOJUE5ChFefhS3nctFD4QSZaWEdaQHRCBBql2xZ1+wp77S+uyGBpag==,iv:fC8Mb/9mb+aB4W0sndXIv2qOEYEjWxMVzIecJrXDe/U=,tag:nsPd5K6wej1UwdtHHOrzkA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-11T17:24:07Z"
    mac: ENC[AES256_GCM,data:xgtolw3jWQET0XPPYeGD84D5vT+lV4vtFR3m7WQ8HLLQz/kFQbaU0xHlX+s7qeVftgyUdEu2RxAS4jfhu7kMhAZqm4WTaRVLeTol//pATmZuPUMzNaUBRqzueMM9UgTDR8HxoP6Uw5aJH/mYuUV7pmhWHIGwcR2VcUdiFnTlZLY=,iv:yBJPj77bagG9a7a6pETGOJPqBB7Y1CIZMKUzZgwG/F0=,tag:H2IvvHCvtW6A4+7+xvLpxg==,type:str]
    pgp:
        - created_at: "2026-07-11T17:24:06Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0dSZMvnEisuAQ/9FgLENWv1FDG5P0hVg9Rjmw09ZHSR2IEik0zbS5KNRIB9
            +qXuOCdH7uJGtWnZ23GRTJTJuC91zUqxxPs8EA6+ve5IIVkOTveJyOTKOpy2wGSk
            2fMTLMK0W2Y0bb0FekCmt3x0vDDayFzYqjYtSC5pfZLaUjjXlu+aI+B7AhIUc+4Q
            43wiV+ezeP5lFummNRQEtNxIbRmxBKGWG+I10a8J4imgx6JEMam/sJFqTFDnPUdH
            +WT+KaTDV/N4NcYJWqeGwJQDmwNi2/kXFLU+dQhNLZJ/ccK2LiFzgXAhUvQWddm7
            lU1GJmlatjVeI2d3YZhTJK7gWIlUWi/fMD4l6aK0h9mFiwPmD2PXcaWAEegYkJYb
            zbKDl4BkIKS2fa0Aatbg60VX/Z6v0mDXu1whXOzgGZWsr/eEWgi0Id2V3T0kW1ch
            BlADutR7git51k6gOkAfIRvrUkBK3M+HNqur09vjlNms11IH4DoqLiruXR2OYwuX
            A2dtjY2boyAE2Xv5hOFTHskfrkc1DfMRWIusNwyuu5xQzi1P6KwBozDJef5A+y5h
            D6D4Dh0CeNizJnI9GGn7CSmQFS8C8fukJwLjdimIzMfTEGbsmCH447RU7x2VNg1q
            l2BvkgMt46RCd0YZpgiTYGUKwo+LS7c1DxzeEJqXi0wGHgM2IIh997IZBoNJox/S
            XAH4uzvE0G+iFN+HaktoKlDgVeIMHlCXcJbuNVb5M8/Wk6B+63/P+YLdIA+lbql6
            vjmGwbI9D+DrI+GQpok/YKUCF5j2WAEaVyu0JQUFlaBSbXzgs2on3/jUJ3CE
            =hVb+
            -----END PGP MESSAGE-----
          fp: 1DBC3ACFDB8B1DF2C44CDA23996024D3718273FA
        - created_at: "2026-07-11T17:24:06Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxbwxdi5IniFARAAul31qqvXgJSLnz8ZanyZ5PqascU4G0kSwib1hlqIAEUn
            wGzg5YpZdnjgK/WMT/CDo/PspCP+NVkPqMBBgRTf+Y9m14a1n0Wz7Ev3q7jLyF/F
            keB1fIlqt7ZNkoU/g125GqdEO6mPGWiV+Ax/MWLM9qINISAkXf8IpiO04+OHUec1
            qb6YT5wht5wQrXlgvUqh3BKwtoAFvOu//SocOPqm96JLDVDIpj80y/q2NNlFCPI/
            P6QpNj/GgPNU5fYUeDK/8VJ33SgclohV00yGXYRVyN/hblSMgS5XrZtpR+i3sBo5
            yJimuiHk855fwkFK0y8W+g2XbdNjLaReS6IJgiSmtrbj9+ANKSNSS8xzkzYJMDIo
            kcL9u3WihSYwIQ/MiIrH/TyfYbWIN4dMby+nFVKIxdHLfivYwXSz5r40dRYOW1ax
            2dfFM/dTQJsQpaoq2j2hUUNx9GO83y1lsQGYCF3De5E2em6J7JBYozOjSF1zv0pz
            Jnf/P2atXliJSbMPo+ESzKjhSdQQ284V4CMcTbTISWCSNq9G1TuI5lOmMFA4zFPO
            geLdDWtvL7tqZPa8M1aGDxjO2uVQGwrRAwghs4g0M5AuB4TJLcDkpYDMNY5qgO7b
            7r81gcQqleqgoztOCKs/s2u+us9i82cIlxSDfoguz4Rk8es1obD0C+MmNg+MV1nS
            XAHHXGsgBnP7dQ9WDB5H0gSv9JRwauNyp8/FKv2Ipx0hYJYGu5y8spHDNSbzjdv1
            CqjilrATcEe4on1rZzsirdan+R57Jt3SyztPxMxi0OzOMU5N1qNUs7HXQVFJ
            =eUJx
            -----END PGP MESSAGE-----
          fp: D9F3AF2D9762D61A974DCD3E7B318B162A7DEBC9
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
