---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-home-assistant-config-pv
spec:
  capacity:
    storage: 5Gi    
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /tank/appdata/home-assistant-config
    server: ${NFS_SERVER}
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: home
    name: nfs-home-assistant-config-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-home-assistant-config-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi