---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.2.0/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    values:
    controllers:
      uptime:
        containers:
          uptime:
            image:
              repository: louislam/uptime-kuma
              tag: 1.23.16
            env:
              TZ: "America/New_York"
              UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN: 0
    service:
      uptime:
        controller: uptime
        ports:
          http:
            port: 3001
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          hajimari.io/appName: "Uptime Kuma"
          hajimari.io/icon: "simple-icons:uptimekuma"
          hajimari.io/group: "monitoring"
          hajimari.io/enable: "true"
        hosts:
          - host: &host "uptime.${SECRET_DOMAIN}"
            paths:
              - path: "/"
                pathType: "Prefix"
                service:
                  identifier: uptime
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: uptime-kuma-config-longhorn-pvc
        globalMounts:
          - path: /app/data
