---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-nebula-homer-pv
  namespace: default
spec:
  capacity:
    storage: 128Mi    
  accessModes:
  - ReadWriteMany
  mountOptions:
  - nfsvers=4
  - port=2049
  nfs:
    path: /tank/appdata/homer
    server: "${NFS_SERVER_NEBULA}"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-nebula-homer-pvc
  namespace: default
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 128Mi
  volumeName: nfs-nebula-homer-pv