---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-homer-pv
spec:
  capacity:
    storage: 128Mi    
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /tank/appdata/homer
    server: 172.16.1.10
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: nfs-homer-pvc
---
appVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-homer-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi