---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-audiobookshelf-config-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-audiobookshelf-metadata-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-nebula-audiobooks-pv
  namespace: media
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteOnce
  mountOptions:
    - nfsvers=4
    - port=2049
  nfs:
    path: /tank/user_files/shared/audiobooks
    server: "${NFS_SERVER_NEBULA}"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-nebula-audiobooks-pvc
  namespace: media
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
  volumeName: nfs-nebula-audiobooks-pv
