apiVersion: v1
kind: Secret
metadata:
    name: retrosync-secret
    namespace: retrosync
stringData:
    RETROSYNC_PASSWORD: ENC[AES256_GCM,data:CdBQKH48Csrm9kf7Iq9PRJu74TRHe1ESwRrjNQUxHJc=,iv:1/djQMLb+7OzPPWcMaZF1iiSc+53RCUoxBdijL24aSo=,tag:m3uwmLHIVwidcBX6v2db6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-06T13:07:15Z"
    mac: ENC[AES256_GCM,data:/KhQ59knnvK0RvAlq7WHAQCg7/MjEds2CopvzLmRcvriP/yI/kwSAirQiUB3Di+QrXHS7IzXscxMGSv0tNOvjyu/vLLaV6xL6A8CAgGUptQRTtZZkH9al9jJ1sauPOC2qlj/kUIsThhlV54yUXHwOZKaIKbWp1VY82Rg8T9sOAw=,iv:PSM5mnfJgwigpd4EitklsV2mVb8M973dagy7/yEcjGc=,tag:1EL2G5h4rLZvnwlC49amXQ==,type:str]
    pgp:
        - created_at: "2026-07-06T13:07:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0dSZMvnEisuARAAgo5eIDIrT2e3SVmxYxRO1QD5h3K/w5ecw2hpF/UYy8aR
            r7WbwAx/ittu3Sb5GQOzzSG676AHf5JEk3ItHzfl9OLF+R8WP7jXa8jlficnW10s
            sIn53DcQ03OSM2ylrFks63mgsJiWX0BTzEByXNBeEPalnErs3VODTQ0bErgv1hGP
            o7YSNiSJMTChGGpB4eeLekrF6gHpMBF6sczGpJiyOVE+MZ65+O+b/qyTg3NETbGH
            xAPJkUodss/P30OzMzOi3Jw4XSJrtJZ7/lhSf0T1AEnH5zh3kvHiOLpFv9c1nzFJ
            RW9d5AWRUOlbw3EiSmhi/MO+EOJiaPEYtgt5coN+nl/SmDfQeWyUmVVw7Yp1wDTZ
            /LUHB7sI4EE4DZW4bMvqySQII97rPjsCiF28AhJnvR3WT6239V0Uwnx4TbcP8+zI
            DqNsTBw8M083YwMVAbqSBje9BAnUz9hBHqQ3IOQpjJHI0c1FBfsk3f/1TH98kn1D
            MqjCN91nUjZ6SRwkiVKqx+FS44dnqIjnbRpJnYGzAr9WrXoRJ1HSR+fELkCXLlVE
            v4kgAIK/4C9lAk0df6BA0pwVTkSYy3cf/yq1D4alm8drk6zy057EzxzMEZH1ZxFK
            pp7C55SqJlW92Y9Cpjm3eEBYhjhuJJVsk+2UZDPnD5q5lCJvikMkD8NGgOYF/mLS
            XAFcBjhnZirQxKyGzLMXoDSexV2j2GSwoA3XyA75sfKhI+po6ehmUbZwXUF4i+7L
            +2hP0HUmZwt6XJczR99ZZY8hBqvmXKNWV4n+qhUQUwwdWVVcFdZ08WKPWmmc
            =Bby8
            -----END PGP MESSAGE-----
          fp: 1DBC3ACFDB8B1DF2C44CDA23996024D3718273FA
        - created_at: "2026-07-06T13:07:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxbwxdi5IniFAQ/9GKoFH2v51dUtvnUBmOj9WuerueerRf+qhMztOJexJ8KN
            QGJwj5lfWHUj/+Z0g3zvt891y1z1m3bCjxe8d2RhKkVlorwCvP++5wefb53g1IxD
            90Ug/mp2TX/4nA7gLGXgl8APH1vQId+gNB2CzGYz3u1G7NEAp4Tqj9SYoDlpryKf
            OxEALbJ8czQ4vAWSWS/Gu2eKTJOIHJBu97zrDTyaGxTrdTvsXyoClIjGPL/Gclzk
            iZHGWR+bwZAIMAWFPwlau69x9WZwJERpikRmBr2DVXGtRGPMOrZdUiZ+igqn5QY1
            cd/WgZioNXnCeJMtwWiR4PPbEqoFK1hohHGm8mfWbnmR67J05zx3hNLT8yhEfyub
            OCBVo0nzmoQmKjnvnoyOCyNDcA8YyFvUwdERd4zuvEHkNjlbRa25FhLCAaVyrRs5
            kDQN1OlEiNQuLuO38xwYNCp9FU40nvwKGI9O9MxibRTFunJmZpRulStgYM1mlhnP
            fU0mWKyNAtKjq1zIwJgHmYtCVINknLab/l+muoYS8wSQDDxl2Wwy6Dec5RIVokiB
            aNir0k/V53oJIY/vRSYLkrAbEsqXwavqASJ9LQBIKId1JOL8dcpPemxZdJgeEWO4
            /Bm0TWEYD1XWIwpM0gOpBpsmYzjW7nWbocBrbXasuObTRLElq0OwPEiW+x6Ip9DS
            XAFMaz786wDpa6hYGuHfJ/GPNa8SzbNYITjpX0CT37Sn/dFojB1gRyI26AuRpYrt
            4x9f6jdduNQWEhjHpSWPXDA8sMIFrRqJ13fP79bgHbnz9ZZpI0p8MtyciIvx
            =987/
            -----END PGP MESSAGE-----
          fp: D9F3AF2D9762D61A974DCD3E7B318B162A7DEBC9
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
