---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-home-music-assistant
  namespace: flux-system
spec:
  path: ./cluster/apps/home/music-assistant/app
  dependsOn:
    - name: cluster-apps-proxmox-csi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
