apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 5m
  chart:
    spec:
      chart: immich
      version: 0.10.1
      sourceRef:
        kind: HelmRepository
        name: immich-charts
        namespace: immich
      interval: 1m
  upgrade:
    remediation:
      retries: 3
  values:
    valkey:
      enabled: true

    immich:
      metrics:
        enabled: true
      persistence:
        library:
          existingClaim: nfs-immich-library-pvc

    controllers:
      main:
        containers:
          main:
            env:
              MACHINE_LEARNING_PRELOAD__CLIP: "ViT-H-14-378-quickgelu__dfn5b"
              DB_HOSTNAME: immichdb-rw
              DB_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: immichdb-app
                    key: username
              DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: immichdb-app
                    key: password
              DB_DATABASE_NAME: app
              TZ: America/New_York
  
            image:
              # renovate: datasource=github-releases depName=immich-app/immich
              tag: "v2.1.0"

    server:
      controllers:
        main:
          resources:
            requests:
              cpu: 1500m
              memory: 2048M
      persistence:
        external:
          enabled: true
          existingClaim: nfs-immich-photprism-originals-pvc
          readOnly: true
      ingress:
        main:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/proxy-body-size: "0"
            hajimari.io/appName: Immich
            hajimari.io/icon: arcticons:immich
            hajimari.io/group: "media"
          hosts:
            - host: immich.${SECRET_DOMAIN}
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - immich.${SECRET_DOMAIN}

    microservices:
      persistence:
        external:
          enabled: true
          existingClaim: nfs-immich-photprism-originals-pvc
          readOnly: true

    machine-learning:
      controllers:
        main:
          resources:
            requests:
              cpu: 500m
              memory: 4096M
      persistence:
        cache:
          existingClaim: nfs-immich-ml-cache-pvc
