---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-paperless-data-pv
  namespace: default
spec:
  capacity:
    storage: 50Gi    
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /tank/appdata/paperless-data
    server: 172.16.1.10
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-paperless-data-pvc
  namespace: default
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeName: nfs-paperless-data-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-paperless-media-pv
  namespace: default
spec:
  capacity:
    storage: 50Gi    
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /tank/appdata/paperless-media
    server: 172.16.1.10
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-paperless-media-pvc
  namespace: default
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeName: nfs-paperless-media-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-paperless-consume-pv
  namespace: default
spec:
  capacity:
    storage: 50Gi    
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /tank/appdata/paperless-consume
    server: 172.16.1.10
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-paperless-consume-pvc
  namespace: default
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeName: nfs-paperless-consume-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-paperless-export-pv
  namespace: default
spec:
  capacity:
    storage: 50Gi   
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /tank/appdata/paperless-export
    server: 172.16.1.10
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-paperless-export-pvc
  namespace: default
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
  volumeName: nfs-paperless-export-pv