---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-nebula-paperless-data-pv
  namespace: default
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  mountOptions:
    - nfsvers=4
    - port=2049
  nfs:
    path: /tank/appdata/paperless-data
    server: "${NFS_SERVER_NEBULA}"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-nebula-paperless-data-pvc
  namespace: default
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeName: nfs-nebula-paperless-data-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-nebula-paperless-media-pv
  namespace: default
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  mountOptions:
    - nfsvers=4
    - port=2049
  nfs:
    path: /tank/appdata/paperless-media
    server: "${NFS_SERVER_NEBULA}"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-nebula-paperless-media-pvc
  namespace: default
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeName: nfs-nebula-paperless-media-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-nebula-paperless-consume-pv
  namespace: default
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  mountOptions:
    - nfsvers=4
    - port=2049
  nfs:
    path: /tank/appdata/paperless-consume
    server: "${NFS_SERVER_NEBULA}"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-nebula-paperless-consume-pvc
  namespace: default
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeName: nfs-nebula-paperless-consume-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-nebula-paperless-export-pv
  namespace: default
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  mountOptions:
    - nfsvers=4
    - port=2049
  nfs:
    path: /tank/appdata/paperless-export
    server: "${NFS_SERVER_NEBULA}"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-nebula-paperless-export-pvc
  namespace: default
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
  volumeName: nfs-nebula-paperless-export-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-redis-master-pvc
  namespace: networking
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: longhorn
