---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-paperless-data-pv
  namespace: default
spec:
  capacity:
    storage: 50Gi    
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /tank/appdata/paperless-data
    server: 172.16.1.10
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: nfs-paperless-data-pvc
    uid: 7f259b6a-1792-4758-8973-6f84d13dd9db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-paperless-data-pvc
  namespace: default
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-paperless-media-pv
  namespace: default
spec:
  capacity:
    storage: 50Gi    
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /tank/appdata/paperless-media
    server: 172.16.1.10
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: nfs-paperless-media-pvc
    uid: c8890daf-5015-45ff-92df-16478efe1f0e
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-paperless-media-pvc
  namespace: default
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-paperless-consume-pv
  namespace: default
spec:
  capacity:
    storage: 50Gi    
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /tank/appdata/paperless-consume
    server: 172.16.1.10
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: nfs-paperless-consume-pvc
    uid: ee378caa-03d4-4b48-be0e-d71280964ee0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-paperless-consume-pvc
  namespace: default
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-paperless-export-pv
  namespace: default
spec:
  capacity:
    storage: 50Gi   
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /tank/appdata/paperless-export
    server: 172.16.1.10
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    namespace: default
    name: nfs-paperless-export-pvc
    uid: cd9a9982-add1-47b2-9386-fbfe93f4677e
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-paperless-export-pvc
  namespace: default
  uid: cd9a9982-add1-47b2-9386-fbfe93f4677e
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi