{
 "title": "ZFS ARC",
 "description": "Graphs ZFS ARC and ARC L2 Hit %, Hits, Misses, Size, and Zpool",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(node_zfs_arc_size, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "ARC - Hit %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(node_zfs_arc_demand_data_hits{instance=~\"$node\"}[5m]) / (irate(node_zfs_arc_demand_data_hits{instance=~\"$node\"}[5m]) + irate(node_zfs_arc_demand_data_misses{instance=~\"$node\"}[5m])) * 100",
     "legendFormat": "data"
    },
    {
     "expr": "irate(node_zfs_arc_demand_metadata_hits{instance=~\"$node\"}[5m]) / (irate(node_zfs_arc_demand_metadata_hits{instance=~\"$node\"}[5m]) + irate(node_zfs_arc_demand_metadata_misses{instance=~\"$node\"}[5m])) * 100",
     "legendFormat": "metadata"
    }
   ]
  },
  {
   "title": "ARC - Hits, Misses",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(node_zfs_arc_demand_data_hits{instance=~\"$node\"}[5m])",
     "legendFormat": "data_hits"
    },
    {
     "expr": "irate(node_zfs_arc_demand_metadata_hits{instance=~\"$node\"}[5m])",
     "legendFormat": "metadata_hits"
    },
    {
     "expr": "irate(node_zfs_arc_demand_data_misses{instance=~\"$node\"}[5m])",
     "legendFormat": "data_misses"
    },
    {
     "expr": "irate(node_zfs_arc_demand_metadata_misses{instance=~\"$node\"}[5m])",
     "legendFormat": "metadata_misses"
    }
   ]
  },
  {
   "title": "ARC - Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_zfs_arc_data_size{instance=~\"$node\"}",
     "legendFormat": "data"
    },
    {
     "expr": "node_zfs_arc_metadata_size{instance=~\"$node\"}",
     "legendFormat": "metadata"
    },
    {
     "expr": "node_zfs_arc_anon_size{instance=~\"$node\"}",
     "legendFormat": "anon"
    },
    {
     "expr": "node_zfs_arc_hdr_size{instance=~\"$node\"}",
     "legendFormat": "hdr"
    },
    {
     "expr": "node_zfs_arc_other_size{instance=~\"$node\"}",
     "legendFormat": "other"
    }
   ]
  },
  {
   "title": "ARC L2 - Hit %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(node_zfs_arc_l2_hits{instance=~\"$node\"}[5m]) / (irate(node_zfs_arc_l2_hits{instance=~\"$node\"}[5m]) + irate(node_zfs_arc_l2_misses{instance=~\"$node\"}[5m])) * 100",
     "legendFormat": "L2"
    }
   ]
  },
  {
   "title": "ARC L2 - Hits, Misses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(node_zfs_arc_l2_hits{instance=~\"$node\"}[5m])",
     "legendFormat": "hits"
    },
    {
     "expr": "irate(node_zfs_arc_l2_misses{instance=~\"$node\"}[5m])",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "ARC L2 - Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_zfs_arc_l2_asize{instance=~\"$node\"}",
     "legendFormat": "asize"
    },
    {
     "expr": "node_zfs_arc_l2_hdr_size{instance=~\"$node\"}",
     "legendFormat": "metadata"
    },
    {
     "expr": "node_zfs_arc_l2_size{instance=~\"$node\"}",
     "legendFormat": "size"
    }
   ]
  }
 ]
}