---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: loki
      version: 5.36.0
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      interval: 5m
  values:
    loki:
      podSecurityContext:
        fsGroup: 2316
        runAsGroup: 2316
        runAsNonRoot: true
        runAsUser: 2316
      commonConfig:
        replication_factor: 1
      storage:
        type: 'filesystem'
      structuredConfig:
        auth_enabled: false
        server:
          log_level: info
          http_listen_port: 3100
          grpc_listen_port: 9095
        memberlist:
          join_members: ["loki-memberlist"]
        limits_config:
          retention_period: 60d
          enforce_metric_name: false
          reject_old_samples: true
          reject_old_samples_max_age: 168h
          max_cache_freshness_per_query: 10m
          split_queries_by_interval: 15m
          ingestion_rate_mb: 8
          ingestion_burst_size_mb: 16
        schema_config:
          configs:
            - from: "2022-01-11"
              store: boltdb-shipper
              object_store: filesystem
              schema: v12
              index:
                prefix: loki_index_
                period: 24h
        common:
          path_prefix: /var/loki
          replication_factor: 1
          ring:
            kvstore:
              store: memberlist
        ruler:
          enable_api: true
          enable_alertmanager_v2: true
          alertmanager_url: http://kube-prometheus-stack-alertmanager:9093
          storage:
            type: local
            local:
              directory: /rules
          rule_path: /tmp/scratch
          ring:
            kvstore:
              store: memberlist
        distributor:
          ring:
            kvstore:
              store: memberlist
        compactor:
          working_directory: /var/loki/boltdb-shipper-compactor
          shared_store: filesystem
          compaction_interval: 10m
          retention_enabled: true
          retention_delete_delay: 2h
          retention_delete_worker_count: 150
        ingester:
          max_chunk_age: 1h
          lifecycler:
            ring:
              kvstore:
                store: memberlist
        analytics:
          reporting_enabled: false
#     gateway:
#       enabled: true
#       replicas: 1
#       ingress:
#         enabled: true
#         ingressClassName: "nginx"
#         hosts:
#           - host: &host "loki.${SECRET_DOMAIN}"
#             paths:
#               - path: /
#                 pathType: Prefix
#         tls:
#           - hosts:
#               - *host
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        hajimari.io/enable: "false"
      paths:
        # -- https://github.com/grafana/loki/issues/7080
        write: []
        read: []
        headless:
          - /api/prom/push
          - /loki/api/v1/push
          - /api/prom/tail
          - /loki/api/v1/tail
          - /loki/api
          - /api/prom/rules
          - /loki/api/v1/rules
          - /prometheus/api/v1/rules
          - /prometheus/api/v1/alerts
      hosts:
        - &host "loki.${SECRET_DOMAIN}"
      tls:
        - hosts:
            - *host
    singleBinary:
      replicas: 1
      persistence:
        size: 30Gi
        storageClass: hack
      extraVolumes:
        - name: rules
          emptyDir: {}
      extraVolumeMounts:
        - name: rules
          mountPath: /rules
    monitoring:
      serviceMonitor:
        enabled: false
        metricsInstance:
          enabled: false
      selfMonitoring:
        enabled: false
        grafanaAgent:
          installOperator: false
        lokiCanary:
          enabled: false
    test:
      enabled: false
