---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-config-longhorn-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
