---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kah-common-chart
      version: 1.2.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:

    image:
      repository: louislam/uptime-kuma
      tag: 1.21.0
      pullPolicy: IfNotPresent

    # -- environment variables. See [application docs](https://github.com/louislam/uptime-kuma/wiki/Environment-Variables) for more details.
    env:
      # -- Set the container timezone
      TZ: "America/New_York"
      UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN: 0

    service:
      main:
        ports:
          http:
            port: 3001

    ingress:
      main:
        primary: true
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
        hosts:
          - host: "uptime.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "uptime.${SECRET_DOMAIN}"

    persistence:
      config:
        enabled: true
        existingClaim: uptime-kuma-config-longhorn-pvc
        mountPath: /app/data
