---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-ollama
  namespace: flux-system
spec:
  path: "./cluster/apps/llama/ollama/app"
  dependsOn:
    - name: cluster-apps-nvidia-device-plugin
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-ollama
  namespace: flux-system
spec:
  path: "./cluster/apps/llama/ollama/app"
  dependsOn:
    - name: cluster-apps-ollama
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
