# yaml-language-server: $schema=https://json.schemastore.org/kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./config-pvc.yaml
  - ./helm-release.yaml
configMapGenerator:
  - name: vllm-patches
    namespace: ai
    files:
      - qwen3_5.py=./patches/qwen3_5.py
generatorOptions:
  disableNameSuffixHash: true
