---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-redis-master-pvc-proxmox
  namespace: authentik
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: proxmox-csi-ext4-ssd
