---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.2.0/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless
  namespace: paperless
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  
  values:
    controllers:
      paperless:
        type: statefulset
        # annotations:
        #   reloader.stakater.com/auto: "true"
        # pod:
        #   supplementalGroups:
        #     - 2316
        containers:
          paperless:
            image:
              repository: ghcr.io/paperless-ngx/paperless-ngx
              tag: 2.18.2
              pullPolicy: IfNotPresent
            env:
              COMPOSE_PROJECT_NAME: paperless
              USERMAP_UID: 2316
              USERMAP_GID: 2316
              PAPERLESS_CONSUMER_POLLING: 30
              PAPERLESS_REDIS: "redis://paperless-redis:6379"
              PAPERLESS_ENABLE_HTTP_REMOTE_USER: "TRUE"
              PAPERLESS_HTTP_REMOTE_USER_HEADER_NAME: "HTTP_X_AUTHENTIK_USERNAME"
              PAPERLESS_URL: "https://paperless.${SECRET_DOMAIN}"
              PAPERLESS_PORT: 8000
              PAPERLESS_OCR_LANGUAGE: eng
    
    service:
      paperless:
        controller: paperless
        ports:
          http:
            port: 8000
    
    ingress:
      paperless:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          # https://goauthentik.io/docs/providers/proxy/forward_auth
          nginx.ingress.kubernetes.io/auth-url: |-
              http://authentik-server.authentik.svc.cluster.local/outpost.goauthentik.io/auth/nginx
          # If you're using domain-level auth, use the authentication URL instead of the application URL
          nginx.ingress.kubernetes.io/auth-signin: |-
              https://paperless.${SECRET_DOMAIN}/outpost.goauthentik.io/start?rd=$escaped_request_uri
          nginx.ingress.kubernetes.io/auth-response-headers: |-
              Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
          nginx.ingress.kubernetes.io/auth-snippet: |
              proxy_set_header X-Forwarded-Host $http_host;
          hajimari.io/icon: "leaf"
          hajimari.io/enable: "true"
          hajimari.io/group: "file storage"
        hosts:
          - host: "paperless.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: paperless        
        tls:
          - hosts:
              - "paperless.${SECRET_DOMAIN}"
    persistence:
      data:
        enabled: true
        existingClaim: nfs-paperless-data-pvc
        globalMounts:
          - path: /usr/src/paperless/data
      media:
        enabled: true
        existingClaim: nfs-paperless-media-pvc
        globalMounts:
          - path: /usr/src/paperless/media
      consume:
        enabled: true
        existingClaim: nfs-paperless-consume-pvc
        globalMounts:
          - path: /usr/src/paperless/consume
      export:
        enabled: true
        existingClaim: nfs-paperless-export-pvc
        globalMounts:
          - path: /usr/src/paperless/export
