---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: paperless
  namespace: paperless
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  
  values:
    controllers:
      main:
        # annotations:
        #   reloader.stakater.com/auto: "true"
        pods:
          supplementalGroups:
            - 2316
        containers:
          main:
            image:
              repository: ghcr.io/paperless-ngx/paperless-ngx
              tag: 1.17.4
              pullPolicy: IfNotPresent
        env:
          USERMAP_UID: 2316
          USERMAP_GID: 2316
          PAPERLESS_CONSUMER_POLLING: 30
          PAPERLESS_REDIS: "redis://paperless-redis:6379"
          PAPERLESS_ENABLE_HTTP_REMOTE_USER: "TRUE"
          PAPERLESS_HTTP_REMOTE_USER_HEADER_NAME: "HTTP_X_AUTHENTIK_USERNAME"
    
    service:
      main:
        ports:
          http:
            port: 8000
    
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          # https://goauthentik.io/docs/providers/proxy/forward_auth
          nginx.ingress.kubernetes.io/auth-url: |-
              http://authentik.authentik.svc.cluster.local/outpost.goauthentik.io/auth/nginx
          # If you're using domain-level auth, use the authentication URL instead of the application URL
          nginx.ingress.kubernetes.io/auth-signin: |-
              https://paperless.${SECRET_DOMAIN}/outpost.goauthentik.io/start?rd=$escaped_request_uri
          nginx.ingress.kubernetes.io/auth-response-headers: |-
              Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
          nginx.ingress.kubernetes.io/auth-snippet: |
              proxy_set_header X-Forwarded-Host $http_host;
          hajimari.io/icon: "leaf"
          hajimari.io/enable: "true"
          hajimari.io/group: "file storage"
        hosts:
          - host: "paperless.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main         
        tls:
          - hosts:
              - "paperless.${SECRET_DOMAIN}"
    persistence:
      data:
        enabled: true
        existingClaim: nfs-nebula-paperless-data-pvc
        globalMounts:
          - path: /usr/src/paperless/data
      media:
        enabled: true
        existingClaim: nfs-nebula-paperless-media-pvc
        globalMounts:
          - path: /usr/src/paperless/media
      consume:
        enabled: true
        existingClaim: nfs-nebula-paperless-consume-pvc
        globalMounts:
          - path: /usr/src/paperless/consume
      export:
        enabled: true
        existingClaim: nfs-nebula-paperless-export-pvc
        globalMounts:
          - path: /usr/src/paperless/export
