---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-plex-pv
  namespace: media
spec:
  capacity:
    storage: 20Gi    
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /tank/appdata/plex
    server: 172.16.1.10
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: media
    name: nfs-plex-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-plex-pvc
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-movies-pv
  namespace: media
spec:
  capacity:
    storage: 1000Gi    
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /mnt/dumpster/movies
    server: 172.16.1.10
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: media
    name: nfs-movies-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-movies-pvc
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-tv-pv
  namespace: media
spec:
  capacity:
    storage: 1000Gi    
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /mnt/dumpster/tv
    server: 172.16.1.10
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: media
    name: nfs-tv-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-tv-pvc
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-music-pv
  namespace: media
spec:
  capacity:
    storage: 100Gi    
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /tank/user_files/shared/music
    server: 172.16.1.10
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: media
    name: nfs-music-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-music-pvc
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi