---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  releaseName: plex
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: plex
      version: 4.4.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/plex
      tag: v1.23.2.4656-85f0adf5b
    env:
      TZ: "America/New_York"
    podSecurityContext:
      supplementalGroups:
      - 44
      - 109
      - 100
    service:
      enabled: true
      type: LoadBalancer
      externalIPs:
      - 172.16.1.101
      externalTrafficPolicy: Local
      port:
        port: 32400
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
      hosts:
      - host: "plex.${SECRET_DOMAIN}"
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "plex.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: nfs-plex-pvc
      #transcode:
      #  enabled: true
      #  type: emptyDir
      #  medium: Memory
      movies:
        enabled: true
        existingClaim: nfs-movies-pvc
        mountPath: /media-movies
      tv:
        enabled: true
        existingClaim: nfs-tv-pvc
        mountPath: /media-tv
      music:
        enabled: true
        existingClaim: nfs-music-pvc
        mountPath: /media-music
    #additionalVolumeMounts:
    #- name: media-nas
    #  mountPath: "/data"
    #additionalVolumes:
    #- name: media-nas
    #  persistentVolumeClaim:
    #    claimName: media-nfs-tank-share-pvc
