---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  releaseName: plex
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: plex
      version: 6.4.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      # repository: linuxserver/plex
      # tag: 1.30.1
      repository: ghcr.io/onedr0p/plex
      tag: 1.31.1.6782-77dfff442@sha256:7eb33afd08210169ef1f59840dda9c912599d9d2d3f84fe1330e10bd08d7e07a
    env:
      TZ: "America/New_York"
      PLEX_CLAIM: ${PLEX_CLAIM}
      ADVERTISE_IP: ${PLEX_ADVERTISE_IP}
      PUID: 2316
      PGID: 2316
    securityContext:
      runAsUser: 2316
      runAsGroup: 2316
      runAsNonRoot: true
      #fsGroup: 2316
      #fsGroupChangePolicy: OnRootMismatch

      #supplementalGroups:
      #- 44
      #- 109
      #- 100
    service:
      main:
        primary: true
        enabled: true
        type: LoadBalancer
        externalIPs:
          - "${PLEX_SVC_IP}"
        externalTrafficPolicy: Local
        port:
          port: 32400
    ingress:
      main:
        primary: true
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
        hosts:
          - host: "plex.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "plex.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: longhorn-plex-pvc
      transcode:
        enabled: true
        type: emptyDir
        medium: Memory
      music:
        enabled: true
        existingClaim: nfs-nebula-music-pvc
        mountPath: /music
        readOnly: true
      video:
        enabled: true
        existingClaim: nfs-nebula-video-pvc
        mountPath: /video
        readOnly: true
      audiobooks:
        enabled: true
        existingClaim: nfs-nebula-plex-audiobooks-pvc
        mountPath: /audiobooks
        readOnly: true
