---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  releaseName: plex
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: plex
      version: 6.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/plex
      tag: v1.25.5.5492-12f6b8c83
    env:
      TZ: "America/New_York"
      PLEX_CLAIM: ${PLEX_CLAIM}
      ADVERTISE_IP: ${PLEX_ADVERTISE_IP}
    podSecurityContext:
      runAsUser: 2316
      runAsGroup: 2316
      runAsNonRoot: true
      fsGroup: 2316
      fsGroupChangePolicy: OnRootMismatch
      
      #supplementalGroups:
      #- 44
      #- 109
      #- 100
    service:
      main:
        primary: true
        enabled: true
        type: LoadBalancer
        externalIPs:
        - "${PLEX_SVC_IP}"
        externalTrafficPolicy: Local
        port:
          port: 32400
    ingress:
      main:
        primary: true
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
        hosts:
        - host: "plex.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "plex.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: longhorn-plex-pvc
        #existingClaim: nfs-plex-pvc
      transcode:
        enabled: true
        type: emptyDir
        medium: Memory
      movies:
        enabled: true
        existingClaim: nfs-movies-pvc
        mountPath: /movies
        readOnly: true
      tv:
        enabled: true
        existingClaim: nfs-tv-pvc
        mountPath: /tv
        readOnly: true
      music:
        enabled: true
        existingClaim: nfs-music-pvc
        mountPath: /music
        readOnly: true
      #confignew:
      #  enabled: true
      #  existingClaim: longhorn-plex-pvc


