---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app ollama-webui
  namespace: llama
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/ollama-webui/ollama-webui
              tag: main@sha256:6f95f4f0a58477d3f71220f27a418328104b6b89e1f9eafd80dc6146613bff38
            env:
              OLLAMA_API_BASE_URL: http://ollama.llama.svc:11434/api
            resources:
              requests:
                cpu: 200m
              limits:
                memory: 2Gi
              startup:
                enabled: false
    service:
      main:
        ports:
          http:
            port: &port 8080
    ingress:
      main:
        strategy: Recreate
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          hajimari.io/icon: "fluent-emoji-high-contrast:llama"
          hajimari.io/group: "Gen-AI"
        hosts:
          - host: &host "ollama-ui.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: 8080
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        globalMounts:
          - path: /app/backend/data
        storageClassName: longhorn
        size: 10Gi

