# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    NFS_SERVER: ENC[AES256_GCM,data:lV2o4bCpCFISSoc=,iv:MRkC/EqDzgsdZQEntgbN43ELuRCahEdUXrYjpNKsXFo=,tag:VwvODhPfDRYITH1EuJByJw==,type:str]
    NFS_SERVER_NEBULA: ENC[AES256_GCM,data:olpvmJziADywCeQW2A==,iv:CoJm+C2/JSy5IyV49yl+kHq5EyLiPInzmcy7vdbMV4M=,tag:Vcg+sunpCajNYBMZK0OUcw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:+jDvhFQiqjcU,iv:L+h/9hZwsdn/4wgVv71aOvxB88RftJQp80rWgF+IHM4=,tag:gNquAlsYKPIyPa5++w8iVg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Ywji/esDT1/YGF8cXR0wOq5n6+yDxVOL,iv:aGib141tFS0l38u7kBZZNs6SamZ3H0UNznB0jQ2UuV4=,tag:hbfvU01J/OzpUFTGBu/qyQ==,type:str]
    NEXTCLOUD_DB_PASSWORD: ENC[AES256_GCM,data:X8VhkDQOiDgPvFWPM7HJdFTBZAvj,iv:D7oaekHqUdMz+Trz6gkjxo16E+XDamEYt/77zaeK4q4=,tag:vYwILfNW/HYU80Veag4lgw==,type:str]
    PHOTOPRISM_ADMIN_PASSWORD: ENC[AES256_GCM,data:sZFZQ9FF0NMQZem9VBrtzSxZ7RV3,iv:pjw+tYeqRxlT2ps8yXJcmUErS8hx7YRsohDydHnq8RM=,tag:n9DyGVasKX7aZ1w5F1QFzA==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:bqVN7naV/PFfcxVKdMD8ZDTk/IBDAvwa,iv:0f2FatkPXmdA4RoKZ8zfejMGTf/tDmMPxbudNiATRz0=,tag:GMJ4Y9g2MsoBK74zjT3L7A==,type:str]
    #ENC[AES256_GCM,data:iSU8UDI=,iv:kAHsSVrUzRBHW62TlbNGwF0g8QlrQ5Tz7pQlq4Z+M9A=,tag:/8S9HpNyc8o/c+F1xg3KSg==,type:comment]
    #ENC[AES256_GCM,data:7qDLgTCwN9ZfP0LFBFLdND82OMFWD3XwFJQHf81EzPYtGUUbpTaBBDNQwiyZfbw8KdD6PJVPVDkUBg==,iv:uWmgySzcaKmFRDEBwIFfXie5oI9Jwy2CPP4E8WycVV4=,tag:+/jevUmBCM8B4AEJGxG73w==,type:comment]
    PLEX_CLAIM: ENC[AES256_GCM,data:0gbZNxvxWmaaFtig4loiou8bDxuGBHaQ3FI=,iv:FHCuM4LIB6fwfXAoFXa2wErjcvtZFkniAk8+XA9/a68=,tag:pfFCWDDFSEVl2pyORSxaIQ==,type:str]
    PLEX_SVC_IP: ENC[AES256_GCM,data:SunjSQuJ12DZ5P06,iv:oC6WY5QstpHq9KPN/JBwzwH0SEds/SmVwiUI9BNdGac=,tag:IneQdoT2RiwvsVflMgNVdw==,type:str]
    PLEX_ADVERTISE_IP: ENC[AES256_GCM,data:H4Z4msbjNn1b+8OJot+4ypgs5+rcS7kTSHed,iv:dsyPQ5UkxFY3aj6+z+JrppT6zL/AGp02ZIrbhuHHAJA=,tag:Zrb4Blgmu81giaMVUVmKpA==,type:str]
    #ENC[AES256_GCM,data:yo461G4QhKKaB52uWMRo,iv:EHDmB5rVTLFA9Oxh0MaEryh8RUmGJ/fzTIkHBtPet18=,tag:vzmm8k2pH6HSPVi0YjdVWQ==,type:comment]
    HOME_ASSISTANT_SVC_IP: ENC[AES256_GCM,data:6s7B7QAAkfh2c6rQ,iv:/hma9gVRXSFsiQwOOi56cDrMwOFrltIGGltTthfOKkk=,tag:19rerEeMc+F2rSI8UPkxwg==,type:str]
    SVC_SYSLOG_ADDR: ENC[AES256_GCM,data:8J8p4cwyv8XJcFWR,iv:5Tta7Dc4p2pU7tmT+Om5xlhqoa77okHhnBRVILIcJTA=,tag:OEIdJTAH9yBE8TfFsKn2QQ==,type:str]
    #ENC[AES256_GCM,data:jgn418JDoxun/nO6b8IzTbU=,iv:1YMApgoJQhsReBDSwbmW8LxfIsM+36hGBq2nl4zRlBU=,tag:AEjSJ3pS5Ii8rtyNrPE2cg==,type:comment]
    UNIFI_HOST: ENC[AES256_GCM,data:amvv8YkpaySrExY13Hd9BtBzKxaN30o=,iv:zxUNMSrsACmC3OJB5iBPI8zzYHSpO3o9nBzJIGaGtUg=,tag:eLl+iide5crqMuWc/kyT3Q==,type:str]
    #ENC[AES256_GCM,data:bJEE22PHJCNVTIwe4dT6bh85,iv:egLOi3ItiULTRNbyW4JY1azaWNlzhFcl5gP3CzMXbH0=,tag:wPWcEACAgsV/gTLrpOSnXA==,type:comment]
    SECRET_SLACK_WEBHOOK: ENC[AES256_GCM,data:4KASjvmRAWwszSZblalFI8TR84IMbUnsmWHE9ohfU1iA2Fx11Y6dm/TLeGsB+zS5lbkjUkAwAB+MS4N8dbCCS1BV6f5KJNr7Vm4UZBLGnA==,iv:0ilAJGmpyiPrQo2elDKtFTD0Z0Vo1sOFEBVJgaKJSLo=,tag:yxByz59T05yAe8WYtfrxBA==,type:str]
    SECRET_PAPERLESS_REDIS_PASSWORD: ENC[AES256_GCM,data:WVLU87nycwqX2aICR3IvhXM/6egE6NDg1C0oTzGuFmol,iv:IO21InF4B8O761772++nnbPLHyXamqt3ADJsSwPUYfg=,tag:xwXYYXyU/ffJ+/XIbg6zHA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-05-12T04:11:46Z"
    mac: ENC[AES256_GCM,data:sTSjEvB+H6qI20TWEfXkP8Qyqdt2bvfZEi3WxAskqZk9bI2pLU0ABG2hg/rKsOJpK4Qs+WO88zO9wcN+1F8+fNQB2ItokiRPJUY965rAW6K904OWMfCji4MsjLMuIymI/RrvOBnwPyvPnulWeyvv2zfbNsgrbiI9442m+sTAjwk=,iv:wTWObCxC5acjenOLZsNhAxSmRkyD6uaOl0jY+80fy/M=,tag:rZQs4Spkup+I/XXyPU+4Ew==,type:str]
    pgp:
        - created_at: "2021-04-27T01:36:09Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0dSZMvnEisuARAAuWS+AmpIdkac23WG3FGBsRS/0tn1cBJ6S2DxcS9BhNls
            /xWZS4pHQi0v6j5jy0snRNCqiBop5DUMcXKivIE1PKw5x5yaxT5YYvZvrBC+D2wR
            i+fqUoZWHJa4DLJmmXRGLKf6qLJru8Ge7v68cRw+B7EnSEATyU8tBwVirdbLTucv
            MFfRBA0w8xLy6o7gmEPpuFAF5Q3wRp0xkMr3sm6g9r2ya6nrvueDoTR/1CbmROtr
            J8uEX+s1XqqUsIrn5O2blFmVM+iauWIv/u4W15xfK7uHNYt9w/wWdDnEguNV0N62
            KUZnVXxEhq0UKYN8GUkEUzSAvhq7uMSyEVT1H/Mtsw7ozyL+tx40ymAhYwdcKtIL
            ix0pCYzAxhYYEeThVAEUTAv0xpyBHoAC87hvyRovXeGHkaexGYJWdyrmfQ+MvyTG
            5BAbt6HNA45sGeIK8HGD/eB66afPVsj3u++vyiPu/OC4tOGn69fum+RJXTYZcaFK
            3Ekg3Mi7RedUY2+usnIkJAyTZeJXe7IAwP2/cnGmP0IHtS6atGaenvABOH1slvqq
            1NOitGMRKGxVi3EFHUJggl2PYcM6NBmtojjSMTWApjWGGRYYqObAx444KSrRVxoj
            UqdfTtRv0XtdnGSlUhVo+fMLi/xD5waxHX+t4v/igjymDtfVeeRurkstpUPTyWzS
            XgFVzfy23NPtnhlie7jAkERcWPRs0mAtYpwISvdRW9B8/HAA0C8zYjpuugK09Y3s
            Dm6EmH+j4Z4eTuwkz1tOrmYTi9FNGkIzi65LBVyDS0cCUljFRmN2nMBbgZtWT/o=
            =rbi5
            -----END PGP MESSAGE-----
          fp: 1DBC3ACFDB8B1DF2C44CDA23996024D3718273FA
        - created_at: "2021-04-27T01:36:09Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxbwxdi5IniFAQ//SLPKY59QXE/LiJ3S9ja0BwL0+bVPsW7IJdaXC3QYmrkt
            iI3Rw5XSKCYEKhs91cf4E/XII37CMtIKQ/l7uX/JiRMipvcly2v0ABiYxztj1hjq
            MV/E4dpDTnPrSz2fCiYs7oKVMuR9Fj59zQpH+FjOuAQcjmK5gGL5CuFd1eZ0FjMR
            xk1QMWOfasaKbtVjxtkZctF8aOH7ugdv/MgpLmbKhGw+zRmi0GpnEb3NE2LU2yzd
            DCnJtlZU/vS5CG19Br3mOF2CaSRXCk/pTZLyGWRWw9aW4jk9olOMdto9VVeQXsKJ
            CahJoviaYiWoF253sSs8B4R8gM6alxIf0teJMgtw4NNc7rELEbzzeCi2pAVQx2ki
            c7eq17OAsRMcKaZuBT86D94HTf6jiqw2wpKyl8S89QZlhUPQQHresnydbykGk/wY
            m5vAXleWSYxIVG2U3RI/x53L49WThjVuyLi293jkM2DR0IgBfUcRPvU0d14uMpmP
            QUKJOq9todoC58lojXWhZkGals0h4O+46QeVK21zYabotGg0JS7TdR3n7L1tUhj8
            ixSZhapgUwjeCW1BpkbuC+vVxOm9HOblGiK4edtwQPmQrwNifKJddo30mRLkyG2R
            vvuHPOU+6crswgRV5Gnr4tGu0P5xuwn2B89Ete9tTi38P7hoWbuMQl9LnWBc+uTS
            XgEIVRSuPzHnBcinD2u669Onk9UiW7DUcf9C2yTI0zG6lo2Kl+1EdfrUQKQQg2mB
            asQvHcRLhBvvJ/VXV5MxjOJpiayo0M8D8eYS/1QJYs/vTBlESfM0EAzVHT23YlE=
            =mk93
            -----END PGP MESSAGE-----
          fp: D9F3AF2D9762D61A974DCD3E7B318B162A7DEBC9
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
