---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-photoprism-storage-pv
  namespace: default
spec:
  capacity:
    storage: 500Gi  
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /tank/appdata/photoprism-storage
    server: 172.16.1.10
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-photoprism-storage-pvc
  namespace: default
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  volumeName: nfs-photoprism-storage-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-photoprism-originals-pv
  namespace: default
spec:
  capacity:
    storage: 2000Gi  
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /tank/user_files/shared/photos/originals
    server: 172.16.1.10
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-photoprism-originals-pvc
  namespace: default
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2000Gi
  volumeName: nfs-photoprism-originals-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-photoprism-import-pv
  namespace: default
spec:
  capacity:
    storage: 500Gi  
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /tank/user_files/shared/photos/import
    server: 172.16.1.10
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-photoprism-import-pvc
  namespace: default
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  volumeName: nfs-photoprism-import-pv