---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: photoprism
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: photoprism
      version: 6.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: photoprism/photoprism
      pullPolicy: IfNotPresent
      tag: "20220118"
    env:
      UID: 2317
      GID: 2316
      TZ: "America/New York"
      PHOTOPRISM_ADMIN_PASSWORD: "${PHOTOPRISM_ADMIN_PASSWORD}"
      PHOTOPRISM_DISABLE_CHOWN: "true"
    ingress:
      main:
        primary: true
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
        hosts:
        - host: "photoprism.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "photoprism.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: nfs-photoprism-storage-pvc
        mountPath: /photoprism/storage
      originals:
        enabled: true
        existingClaim: nfs-photoprism-originals-pvc
        mountPath: /photoprism/originals
      import:
        enabled: true
        existingClaim: nfs-photoprism-import-pvc
        mountPath: /photoprism/import
