---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: photoprism
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: photoprism
      version: 7.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: photoprism/photoprism
      pullPolicy: IfNotPresent
      tag: "220901-bullseye"
    env:
      # these need to be reworked
      # https://github.com/photoprism/photoprism/discussions/2799
      UID: 1199
      GID: 2316
      TZ: "America/New York"
      PHOTOPRISM_ADMIN_PASSWORD: "${PHOTOPRISM_ADMIN_PASSWORD}"
      PHOTOPRISM_DISABLE_CHOWN: "true"
      ${PHOTOPRISM_SUBSCRIPTION_KEY}: "${PHOTOPRISM_SUBSCRIPTION_VALUE}"
    ingress:
      main:
        primary: true
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          nginx.ingress.kubernetes.io/proxy-body-size: 4G
        hosts:
          - host: "photoprism.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "photoprism.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: nfs-nebula-photoprism-storage-pvc
        mountPath: /photoprism/storage
      originals:
        enabled: true
        existingClaim: nfs-nebula-photoprism-originals-pvc
        mountPath: /photoprism/originals
      import:
        enabled: true
        existingClaim: nfs-nebula-photoprism-import-pvc
        mountPath: /photoprism/import
