---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cluster-apps-photoprism
  namespace: flux-system
spec:
  path: ./cluster/apps/default/photoprism/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  #wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
