---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cluster-apps-cloudnative-pg
  namespace: flux-system
spec:
  path: ./cluster/apps/default/cloudnative-pg/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  #wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cluster-apps-cloudnative-pg-cluster
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-cloudnative-pg
    #- name: cluster-apps-external-secrets-stores
  path: ./cluster/apps/cloudnative-pg/cloudnative-pg/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-systems
  #wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
