---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-cloudnative-pg
  namespace: flux-system
spec:
  path: ./cluster/apps/cloudnative-pg/cloudnative-pg/app
  dependsOn:
    - name: cluster-apps-longhorn
    - name: cluster-apps-minio
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: cluster-apps-cloudnative-pg-cluster
#   namespace: flux-system
# spec:
#   dependsOn:
#     - name: cluster-apps-cloudnative-pg
#     #- name: cluster-apps-external-secrets-stores
#   path: ./cluster/apps/cloudnative-pg/cloudnative-pg/cluster
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   wait: true
#   interval: 30m
#   retryInterval: 1m
#   timeout: 5m
