---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-immich
  namespace: flux-system
spec:
  path: ./cluster/apps/immich/immich/app
  dependsOn:
    - name: cluster-apps-longhorn
    - name: cluster-apps-immich-database
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: cluster-apps-immich-database
#   namespace: flux-system
# spec:
#   path: ./cluster/apps/immich/immich/database
#   dependsOn:
#     - name: cluster-apps-longhorn
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   wait: true
#   interval: 30m
#   retryInterval: 1m
#   timeout: 5m
