---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealiedb-1
  namespace: mealie
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: proxmox-csi-ext4-ssd
  volumeMode: Filesystem
  volumeName: pvc-6bc49b00-22a4-464b-9a67-4baac4ae4c6a
