# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: nebula-conf
    namespace: networking
stringData:
    nebula.conf: ENC[AES256_GCM,data:5PpGwGBrSCVdZBkdXFCU0+qY0lsa4GUcFRIoRh4oT04T17f8VwFyCRMAf+Absjrs5N1DKkY6PHj/h7Y4Y/KZYFBk5gt9bEd8tp/U5PZFD+XN2I5+JFp2Cyp1TTRAfs/GTxFnv9fxQ2jj9Os/FDgXgzuvhep68vjgn5Mp3KHuoLb2NVaSCpVzUKmTkuv2noP3FFwWT5pEw96GbeoM2LWFkFnL16Iyge+mQoW6kCNV4p6bai60RAFEmugRUlOUFh4/bbV4aQ/dkdLUJ528rTgrSyWsLSkLhJ3E55dBZzni0tcdVKf5XrVibuE4HzhCCJVS0p9gUAccE/ay08qfKdBZyt3vPCzmSBcSaKIS7Pk4JFuAEI1eH6QNJGK8HYaeKLkh6WlF3dFtQoLsZ5gTwofVHVr4kG/0mq9b0l+X8XUW4hOHk73wMV1mOD1I1vVhBBnNpZ+pJ0zj24rxkWNtKr/y1u0OV2KqTqP5EcDN3PKYhcqS0KgtILN/phO/i1PI5aZN5DOvRLHfIPXrYqJpBGIzOBiyx1nFaIkQDEiYBHvXFWLXnOW54jXEktPpD0Curj+1rUbrDcwfJQxAbJSpG6n5C8REYjTW27orQN+WqMHhj4HK578YYLENE/uhlK2kUSxqJNn8Mc0oaUdCvEFswBadpc+kXmG5yp35Nca/3tjPxJtHFus2lU0ME1Rz4G+LznZl4dMSDtymSS2q0r7t+J9rTi/xnQKzXDUJn8Z6zssIzj0suuigedRJK13804JvzZmQeXfwyanvsXwrB3U7ODjEnVbN97NDtal4Jx1Vx1yC7wqVmQcl/5lSWgSlBScddD+C4NH00GZ1NwKL7OtswppcRA+auKJF42adnesivYlCYMxjmr5y9VuS/7pMuVri75eZMBNiQRuz8KRvp7pu892w9yAzM5P2dl9/XYtUmUSsy2PQEK5VGxgnz1VV9jRIVqsSVkvxtazbXeZjDihuyUttLw27/1971vHTBGHzGJYZb4ah+EJvI7OMLdurE7e3eAkA5sxwhilhe36gcVwt0wPA8gKdPoN+dLb32filHRgLUI4DzA1DQn7Gswfd0TgYr5znkwP50S0KnJTw0Z9wVf2r8DWQQtQm7YQgG1p/5CSFgcT2tueMfOn5MOP4Fp9RBhp7lQ3N9Oi2FNssvid2zcvgkuOMZNrVEEmb7PQURmWYoD+3/H4ZY2L9noz9J2pFd6fDVavVBhCXZmMnIyJHaVXizsumGx2s/Yjpbi/YL2HWVk1VPyR3ex+OWBe1fIrhacxahI991ujVxOwcDkvSWripBVvlakvRpNw/VrodA4ZlqdzcGm7FtJVOahnRM0CvyihlDKfFRo1AyIX0XHD4mXYjgV4Jye8bjaIAVZMDEMRqTKgbpZStI+jQHVgIaZApKetgGb1mXmsQ3jkr3Zw8QVnvRAmRS2mv9gpbmwH1GM52wAZZ9u93wvlApPwI/kZPoTdTwG4FvLHWEvKkZvND5kepLTNsVq3oxzO965JzsOQZ11DxWDq3TW7Okdgpl+epOmvtX2zk+Z4ldY8PeAzn8mImQa13kNrrNe8FQ3A0qGPev6amUPc034bWgRL+vLq7eMSUSBKzCL1CcZBCxuq+zHyjBL1zOvjoH9nFb184PUUeMg6s4Zh18qsg10s8lvwElpY1bSpn1aA2hybCKJgbcc18GuTPaqwQ4x9pbURS4O4nqnH83UNFJvxE6T6hYhnN4CkyJD7Mc19RH6FjjoXp8a/yjvGF3mICWQys1XDtsCuRfjNQ6BTb+SoZIPegd4RJpdb5p8gInL4RMjbiP/IVSBSV/CJzVN+R1gM6RO4Fuf+h+w10ma3dnCVNwV1E2wcAratClNqcCHBZaHITa3VCbltLzESrR5jok7O3F9r5LcYusfqnjHKkAtBbAe8WYl845XT/5x/K7vBMMLbg6I5G24q4IFNynpmVJXXOWlRSTjWKtuyjhzytoBBCfWDGlkHpoPHJcMDlkxcyvPBeIRn+3Od1XJLRfTVSwVDChsy/3oVB5aDscA/ElLuUiusXsBW1Z1qvb9sajLt1WYY3uCmwmS+O5IuswL7BZkwXxDTtO+/jfJ4TKhVm+FPyEt6p6wGL3zPkCfYXX7Nj/iZO5JgjrEDW693UzkVemkaOC4zFD3hwEq4Scwue71f535ViZBdbAVZj+ToQef6iB64qa3AvaTBKfFYsv+aqdRD1KHntAbP2XdedG34VQzBo/d4R1YRJ+LhzbMTXti4IhNP6Bi1KpBNo73XyDkYc+A2SNe4z0k7bAGfi84nKmVFqFg149adlgC/OEk3p1DolGA==,iv:eR1CoyTJSriEvI0NAwcMqbEuiOHtc/0OECDcvYxYuy0=,tag:bgOllTSPCtrGBRp4zld33Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-05-18T01:46:49Z"
    mac: ENC[AES256_GCM,data:Hdj0PBNnipL0ORdNoEeQG6mJkcHc6vUgR6D7Diqs4EF6myLxl2JA+4XjMowQP9J9205OILI4cgChQQc4aJ9CoMTul1YQq3ljHTHfNnYdjblI+w1vyYnG97RS9K2me3TA05MjS2QzDtVk7t7LJ5hujLE6Y+Yn11qJdmchyMG8YZY=,iv:d7lXTIzF42D47RkoOvVF6YQ25MwrasLo38wZH+DoAV8=,tag:SCkEhtX61MRnkHr2lkYsgw==,type:str]
    pgp:
        - created_at: "2022-05-30T19:12:36Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0dSZMvnEisuARAAnQobw/MrRqWvV2cPg9VSCA3yue5XW67TGVw0KCGNsy7A
            N2YqqWYoSqvZf24W5sY4XWH0rVcSspkbvmrUycHuTdjr6RiwO+dvgGZ8P1kO1/+8
            2FyYqzaPaTMAKTvrcztnY6SgV7v+SW6moEDttm74YtnCj9TtkqACTa6Myk+I2h/v
            k8Mvk5IsbJ55ltfzcfiwCa3P1eD+ZEMNte4B3e7cD1udT9dntJCBB+C8X4WAq++U
            ppzW82o1O0O0Ki0FX0wklelvt/XNxfgak4nohfdKHeOTR2AKGfa7cVS7Tj1gEbuD
            29CK5pK7CUL1jfCan/4FkPXQ1RnxDoZkI6CM6GawCvJRTXuxgRpz+wBXReT0KZLg
            ag341NeStFYHrEIiIlqLpLUl/Tu3IjfxeRjzL0cJG5tC85jWcG3NCO/iCuwQPrDb
            ur7DInnO+8Ks5pFUcFW/RxXFermpBWYxzcOAMFwK2++HJc5DP+1DTPCtJv8Lyomp
            bQpZ2QJ/tx6eCpD+kUqWZRrsQBIbdFR/5SQ3kIe3Nx7FvY9Fd++i6efwk5ea65LW
            FsmyfzOr+rxko8FgMK4WVqvwnDG0yMf4OEC6AD/Wzyq7jhuSHBPfCUQ9kY85QavY
            1Lc1HyTEngLXvP6XmoQlMrZjWu94bVRS4Pvtbs6MqMW7py73cBAhe/mSQn8eUbbS
            XgGplt4rX1y8XRG5EkBrzbt6qEbEVkXlp8Z/4T+K6SxyIRJKrXLedv4kxJvvmWJt
            IqLaZxMSigUro/RT0vZE1+gPNgdtDGv4PVyHIVq+Hdlj8QB6q16NvLSfhovRBJE=
            =YogM
            -----END PGP MESSAGE-----
          fp: 1DBC3ACFDB8B1DF2C44CDA23996024D3718273FA
        - created_at: "2022-05-30T19:12:36Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxbwxdi5IniFARAApp1tdHy/0Zs2p5XBR7i/530OjqbC7NK0C4tpQw/HjKrg
            YXXdD/SCtIU8QM6v3+XofOtezhuoipl+NfsC3F0DJcvHzS29f1meVWx2SpDYWlgR
            V0qFN09hFPqTLOdD2HyMoOLyiaGYABCbKITuDaNaGSx+2a8S78di/oWxfaEYPkO+
            R0JffIsuuEREOOWP03Capk3rWaCMfMeHRQmtO/y6wLAS8k0DKtH1AnwlfFfuAhkd
            RU2hxQIdocT3dOJQidBRh2mKYHAzj30ANRSYYtZ+0UOlUQ99LB+s9MgopLNNhUJh
            toc5ErA+mPDerRXN+BZy5HBAk+zl8Wo4zGy17f0fCbxX9h1cJUm0jRTyic8Tfc9Y
            Y6dImIjVTT+4Wh3xq3ke/fwQhr29D//e+ODBDzAz3RLUKtBOnUA4z1eQvKcvl6c2
            VVV8qCy4olmJqS1tM4Y99PgHshElhPoRpcT+htMwnJITK/6xdS39kJU8lSi/l39t
            Zqu4/vVgutaXMQrNsK7cl3p8rsMnDQL7yWFdvlIM8hHJgAZqaQKv4YUaSG8EhsRL
            ixRojWMOWuq0lgwUjBWtFvRSdJTKTvZs6myaYsQp1X8d/k7eRwvzSYTt/sBqs2XG
            Ij4QvPzeEY259O7ByvAtKexzjk2NP4m9h92c9AazUgxxXFsi8ZzLKYe8iWXxi/PS
            XgGRloNZj52M7hkFAj/2ZPLB8PcnAN4qbPx8oF0OE/4EwJpje24A7wcwJKM3PQBv
            YFCAxRSYjXlYIFFBpW4Udr/734D4O4NFxJmf/5z4g/ORR8FebhV7S0cUl17nZFE=
            =3ITY
            -----END PGP MESSAGE-----
          fp: D9F3AF2D9762D61A974DCD3E7B318B162A7DEBC9
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
