apiVersion: v1
kind: Secret
metadata:
    name: nebula-conf
    namespace: networking
stringData:
    nebula.conf: ENC[AES256_GCM,data:U9KMAZwJ2ZCBpaRDPVnlv+2HV7FEZTIALKpb5ZxX/VD2tmzs6jEF3/EV7JICCLAJeKUi2Y2UqaQkSJJI6w9z9Jqd7olYpl5liI4cUjnEClPLVKB38XPSDsbnywlyNk0WSfLQJ4IOhM1bknsjPrW6mNM9ekHSg+scbnJqk+Y8ZkyXpN1v11sPcLIbQ/g8ic0SCl7+dTYXGYaWexm0B1wjRdZh4ie+J+xUb0nytKFoIP9eyWNznUzxdPV4dm9hRN8bIVGbR2yRWusFbRNIIJakENDyh27NSyjEeMaWECLhqd3pdiVB8gYTLjhYYysw0Z9I/AEgaL16piI0Be8EHG2OGPH2TgH8ieJmNAm2IAP/doVPuOnH3IKaUS8r2rdsOJutNSqeQzi31Gbt7GDRev13E431IQ5/CwjQDkxxA9OZ4Or3spYn0JeT3BTQd5vtErrgOQQ1nwq2VFp/NXy6xTRp/hvZrT2f6TTPHxx/Ws7uoOnuTO2ojedwd679FdnMXl3dnB+8qb0jGOTLpW3YgeS3LUa6KykTDR9bVaqPu7Ch/QlQ0ZGfkR6gTx8K+y5SBzRBByhc4e4gnelg+F3QlYcBfBmbImTUZlTCr/OkNR8G2upA99eHBNNGN+Clg/ibLwDFtqPT4k6u4mpoaHpia0GlxIVf7COE+saRnk2MwaHU7Ym5UBSct3L1CiTeXapk/SMgZDDA5TPFoRfjvRcTcWIKCE2xiXvPBQ5xEZnSZS5arJrgq8uu/dYtTOlsigRWLGle5/tBTRhCMmMYuyT7UmzVUOvlfmiApIjqiSfMZ+3AkvbCU1j2t2AVTifUcW1PbJ/h6XTvG4bb2rD0tl+7gySrUHxhCZJO+mSPhZzBggbgLL4u7cbGfbLZ6DJ02s7MVCHr9izMRvdusEk5Ju5hSSDZ559jDvrxR3t1FCirV5dU4KqEr7XlF18KgbPrt6vFqkaZ9ZsFRQOYTTrawbkSbcoB2X3f7L7Xpq8hrMiDDBxtmzBzePNQSqZN5FvnQLPgfkoGuJyOunHHEY/cmgGAQh/Rc00li7rKubKo0gGlV9XABfhELFOl9lcn6/w2gd9l1etuGrHXiDX+Mqvc/5Gi9pFuzqUbxdNd5crH6yxVnuZ7kuYQu956cX8pixDn8xy+rDCxFEF8beEgOvI1jWrBulrvrzsoW66W4BsU1LLXOSOVe8F4ANmWSTH3W62yn9d0kNO8k5fI+Gg38M5laHk4ilWBGDt+neor1dJNQj1MM4MuZ066hRN0avXndEy6oqcgVwuEGsgTs5OAUFFIQUmk7FLCvPFbp+vtWoqahdlQObAcUb+2rrHLe+a8qWoXrrvQHJAHxrY5cBjyGLs1c/e7julcU28H6J0ZCSFFAJaJUIPLotw4eplWnpGpv1h8YpjJwJfR/zQT9fwNL3gGS5WxECm4HDml6KYxb7G6c7II2W4iPoAMaoheHweuLuZQEP8lWSzEw88lejkWfdih/zO9uo3ofYcF9gQtBztsbCpdNF2XvWJ2Hmtg8wE2Ft3u9i3FwnArcREiVox7YQ3gqKVnEfACvK+37B8vSutYHq5vpj+X8FLNUjnZIMV6/xh5JsnDn1rHqmaJse/wVO/z9NEXcl3W9Fw6Ncz5i8557wAhraq/1oXUfpQgAw0W/8+9S8pVWrRH+cP3CJuNVaayUdx6H55HQj0g10wj6OvSwh4m64VwAqvAHvMCr5tZJCY8y5DsV38itDZ7lzTwOYUz1TVydpR4jxcyM0k6SxDranlzK+yfhLVOfZE+vYynR37EvTi6W2xjxSZiKFLv1ycEPKlf0Rk66jJvNytg10Lc+MhrcHcZkCW2fYeaPl0CyJypJLMFYVcAFyba2wFhAX3N+ChGWL+5x3NBBdsoIj6fni0uQtNnx/9mVYxvFoWrSiJg8wgu96tPswCLclNLJL9QqQTzNYxn35U+bvYjOdNobWaOZtMl3XeiRBP3NG42UShJZKbCzu4ldl6M8tHLv6UcI66xOqELPI9Jb2LDplvNvurB+ejQmXDRdO9ME7nVLyaeBhGDCnZ+b7E3fM8KCNVc1FQl/3Kp/9lNH/J34S6ajcW8iTd9inMJMnrU9UqrApszQfmzieYqvTV3Te98fyNZmlWONqjLe1U+ur5Yyh+h9+xOwSU4wWXB5dklUtm9bv+l0JpW7tchjcvAW8xgYRQSdzkQuedcjf5XqHlJ,iv:yfOZxSWKOGX4fJ3mAs97weann+Ex0jBExypxQp19khg=,tag:re1bVrmulSP3v2hGLBAt7Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-06-13T01:41:36Z"
    mac: ENC[AES256_GCM,data:5RT3LNpSbampLEnm+AAq9R0QtBXauoKHM7KXB/DkoBb4gYpOcciJSDw/AETGgjysRkSVHEb3nMiMtN4DjzY/NtgevuvPpdM/p0/akRlSB0xIH5l1D5MwKgpY8M1n7oavvz6WqNWWtwZ6vAhZIolt6X0cTw9qbZXzTNox8NoQS8A=,iv:XA6/R9AHoPrM7uzA4srDECa2LpjSeHb/3RDaFIQJn2Q=,tag:udfdHAC5GKUJClZeql6myQ==,type:str]
    pgp:
        - created_at: "2022-05-30T19:12:36Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0dSZMvnEisuARAAnQobw/MrRqWvV2cPg9VSCA3yue5XW67TGVw0KCGNsy7A
            N2YqqWYoSqvZf24W5sY4XWH0rVcSspkbvmrUycHuTdjr6RiwO+dvgGZ8P1kO1/+8
            2FyYqzaPaTMAKTvrcztnY6SgV7v+SW6moEDttm74YtnCj9TtkqACTa6Myk+I2h/v
            k8Mvk5IsbJ55ltfzcfiwCa3P1eD+ZEMNte4B3e7cD1udT9dntJCBB+C8X4WAq++U
            ppzW82o1O0O0Ki0FX0wklelvt/XNxfgak4nohfdKHeOTR2AKGfa7cVS7Tj1gEbuD
            29CK5pK7CUL1jfCan/4FkPXQ1RnxDoZkI6CM6GawCvJRTXuxgRpz+wBXReT0KZLg
            ag341NeStFYHrEIiIlqLpLUl/Tu3IjfxeRjzL0cJG5tC85jWcG3NCO/iCuwQPrDb
            ur7DInnO+8Ks5pFUcFW/RxXFermpBWYxzcOAMFwK2++HJc5DP+1DTPCtJv8Lyomp
            bQpZ2QJ/tx6eCpD+kUqWZRrsQBIbdFR/5SQ3kIe3Nx7FvY9Fd++i6efwk5ea65LW
            FsmyfzOr+rxko8FgMK4WVqvwnDG0yMf4OEC6AD/Wzyq7jhuSHBPfCUQ9kY85QavY
            1Lc1HyTEngLXvP6XmoQlMrZjWu94bVRS4Pvtbs6MqMW7py73cBAhe/mSQn8eUbbS
            XgGplt4rX1y8XRG5EkBrzbt6qEbEVkXlp8Z/4T+K6SxyIRJKrXLedv4kxJvvmWJt
            IqLaZxMSigUro/RT0vZE1+gPNgdtDGv4PVyHIVq+Hdlj8QB6q16NvLSfhovRBJE=
            =YogM
            -----END PGP MESSAGE-----
          fp: 1DBC3ACFDB8B1DF2C44CDA23996024D3718273FA
        - created_at: "2022-05-30T19:12:36Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxbwxdi5IniFARAApp1tdHy/0Zs2p5XBR7i/530OjqbC7NK0C4tpQw/HjKrg
            YXXdD/SCtIU8QM6v3+XofOtezhuoipl+NfsC3F0DJcvHzS29f1meVWx2SpDYWlgR
            V0qFN09hFPqTLOdD2HyMoOLyiaGYABCbKITuDaNaGSx+2a8S78di/oWxfaEYPkO+
            R0JffIsuuEREOOWP03Capk3rWaCMfMeHRQmtO/y6wLAS8k0DKtH1AnwlfFfuAhkd
            RU2hxQIdocT3dOJQidBRh2mKYHAzj30ANRSYYtZ+0UOlUQ99LB+s9MgopLNNhUJh
            toc5ErA+mPDerRXN+BZy5HBAk+zl8Wo4zGy17f0fCbxX9h1cJUm0jRTyic8Tfc9Y
            Y6dImIjVTT+4Wh3xq3ke/fwQhr29D//e+ODBDzAz3RLUKtBOnUA4z1eQvKcvl6c2
            VVV8qCy4olmJqS1tM4Y99PgHshElhPoRpcT+htMwnJITK/6xdS39kJU8lSi/l39t
            Zqu4/vVgutaXMQrNsK7cl3p8rsMnDQL7yWFdvlIM8hHJgAZqaQKv4YUaSG8EhsRL
            ixRojWMOWuq0lgwUjBWtFvRSdJTKTvZs6myaYsQp1X8d/k7eRwvzSYTt/sBqs2XG
            Ij4QvPzeEY259O7ByvAtKexzjk2NP4m9h92c9AazUgxxXFsi8ZzLKYe8iWXxi/PS
            XgGRloNZj52M7hkFAj/2ZPLB8PcnAN4qbPx8oF0OE/4EwJpje24A7wcwJKM3PQBv
            YFCAxRSYjXlYIFFBpW4Udr/734D4O4NFxJmf/5z4g/ORR8FebhV7S0cUl17nZFE=
            =3ITY
            -----END PGP MESSAGE-----
          fp: D9F3AF2D9762D61A974DCD3E7B318B162A7DEBC9
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
