# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: nebula-conf
    namespace: networking
stringData:
    nebula.conf: ENC[AES256_GCM,data:9qp8407SbTt3W0rSbXKWTp/sg9J6AuMkJkZNVvYhc1tpuOazcSbvMiAt5JrnlbCQEhk1ptUpziCaDfSzHGcnQQG1q+JAmVAvUIK1mm0exmobT6iXbVfLJIUBOFSsXnYr/bURMUkoxMm6Tori1eEmdVoDAXVRJDxaTTbsQkFgq/Cn0+EMvpjxI33Mj9o0zylbufC/2tyGLKou9P5Q+l/RdyZgTy6tAOz4YQajmhnAoZxoK3Dmadesgel1bcamEKwo5DyxH8ENvaqzXPhL1SzpiO6RzJ80zsJlylxuBb9GqpKgbSbPYTqBAixWxqAZ6I2pauMjQs/2j5pdVtaJxzHSF8ViadHUXIQCQ7nO+snUvORI9+S9cUlmj+P4/goPu0BXBq4V+GhROuovDX65asV4XuLybAaPYP+7LMduBUFsgqR0taAyQWs12shFjpt/zSl6bhJ/YZNoDMONcOk+jNqhKQnpCQiV8iGgQPyxyBQ1o12zKWrAiHFR79gxRVq9RbDSHe9vJgFX8dTFs0hSud9bQVMHXGGHrFTsTlGFvZlQ+owNLrA8TLopfGiyzdeMx9wy3pwQlpCP4ePiJgN5fKfuMn8vxPC1gq7N9IqCxo49wYCqs26GRZc43Iiz7mGq7HHuQGthDSqxK45YUPkrVfQ2JUHC4nChEfBaDaPGWVhQbUoEuIPWgIVYGHIgrDtIDWPR24aN9QrMXs4qsEXRUSo7IOeciew1d7ogsvc7A7i0+KRK8SnbXAysPx1+V7lsjH6faUwZtMJCMTVjPgJcHQ2gKkJSodGVv9c+MHkv2ijPYk3UCAR4uWbOu+cptd0tDmJ9ywPlUBI2+oBlj9UrBM1xbsKwKuiiddy8NCU+TUmdt7eqpQlgEq+rFsQyEpS7Gi0d7AOalKeJEFa6Pl30rL7mAEc3rxZyrhHH2XDgO9l/uuJoHiCFefm+cuoP1WBiD0p+g9e+yP8PhVVx5jp88k0Wz9Re1DWi/2WkdeX83zrYQvBabeZfSYe71/G/CslFSDHZtxMPDzTEq3MmCA5nWaVLGNeqiieSlNDvHxhr8+2+IBg5jqxhFyxHjhRplysfnAxMCSUim5783KYlHR7LP1HJiARygKlEx7ixlwOftRccs+3cOy0GfFiUIO4qY8ir6XWia0EE9SVKD1Sb5TT0ld4NSQRmFInBdpJxSUAPA4bi1ESyIXWkX5Ip6EbXbt1vaeiSuyir5YiKg6I2LrusLgshLYESDWXYoA5xK6MccNNlAYUhsYttpgA66754xB+0pMMX8DDcE1ql2JcQ5OF/Few3s5aOnVf1DIyuZ55jVuh4AvoIW849ETsdndS1j7XvGJ/ROUPYBu0PG1YOHYulq6etIFCsT8b1+f40HGI1wxLMCzFF5mC34+uOovCxj+oVbjeI20QFk5RFlIyN9XKKfOWsXQGNCSH6KpWUQgpTqv7Sj+DCBu0KXXvIapfzNe2xFg5rpxwId5FUPbVQo8oH4KGH7r22OHYoRFHOUklMvwFYXISQ2sak+F67Vf9lZ9Po31CsBTZocW+m9D4mXihyrr7WPYlhfPk7pvgmObM43nqK6/KqMacVbyPCHlXFVLjGbD6dcrNwQGBjz2zDkQKr7WKPi8NGa9wTN2ANRlY5R0nyrwFLGfde//e2FSbV4E6Ob2l3pfp5n1iLjORMm8ywWwIyJ4pFBeC1F1idgWATNV6XCmpHPLObauLDE/j5LKTgdWzGToLKmfokqXLy1rmvNEaZrRm4FefrZHRMGb4IOLaLZ7qdDoPy2nNeTTMEauxAVlh6vTuHxTJUWx00OuYRxrc+CkbhO+wuQBHcU2IQsI7ZV2egmvtxgCCaAgZnhbfx6HhxoR+b6TEgg5bHWC7/c2k18Z6Sp9L6FZndqfokG8Llrj3ngGZtnFPNDirQwT9qmPfPgcvDz+TF6U40gn3YPw81mAAtsJAZwFAK94T5haaQi56xiPRh7WzjCdVtbNSQP0PMd4f3vTEbiC3M5WrMagfgoOwsByA3z9l6Y5Bhrhz7bxP7J6UwOTkcyX0prASs0v3VHjL+j01u0NOb1kYmLBVH+Atyg/30ovI8pprfBzLQrCbGd9Ku+V4Px2x/bQGQJ93ZWvkImuNz4jc1Pf6x4AEbESucifi4F2/dfMEybiRgpVJ0qMxO23o4fT9TiGb5YtVdFM2a+pXO/ObIzne2yd1L9LA3dzFDQ8ROJKKt9lU0u5FkIo8n1pk+m97PKmNVRxBEMaqjIOSo98d1wyQtLytbdV5x8ZGH1rfVQJOt8oc9RKoG2Rc9KBQCZFnAACRdk/bZQO7gUZpSal0r8+0royS9h0PMNWCjgjrcqEbdYPHDURnX8230dlz6z2rvdPRpJZQCToo=,iv:AUAPbttt9eBrwvVGsBMMZjO0aq8pw7zDhueUflsEHhc=,tag:Ch4l+vwGeM14bXEKEmrZiQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-05-18T01:54:19Z"
    mac: ENC[AES256_GCM,data:fGlnRfxEC4S28U8KTXy4eInpzKx/gbb8pDmm2BXv5NS1rfLMlXAnbjOCMtPaQrB8P7klJnc7ZqETBJMK15W82ZZwLbUe+nA8LDkihsEo1asMjrViaNPGd5dvmChVmKPwg4yn7r7FrC08jNGIZRHKoThIgCaQUwEkFa1h12N05sw=,iv:7kK1dxffskuCdv9ttr66wnctop6AkKopy3bCB79yGVU=,tag:41tAfoMahdFwP4ZpWfPrNg==,type:str]
    pgp:
        - created_at: "2022-05-30T19:12:36Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0dSZMvnEisuARAAnQobw/MrRqWvV2cPg9VSCA3yue5XW67TGVw0KCGNsy7A
            N2YqqWYoSqvZf24W5sY4XWH0rVcSspkbvmrUycHuTdjr6RiwO+dvgGZ8P1kO1/+8
            2FyYqzaPaTMAKTvrcztnY6SgV7v+SW6moEDttm74YtnCj9TtkqACTa6Myk+I2h/v
            k8Mvk5IsbJ55ltfzcfiwCa3P1eD+ZEMNte4B3e7cD1udT9dntJCBB+C8X4WAq++U
            ppzW82o1O0O0Ki0FX0wklelvt/XNxfgak4nohfdKHeOTR2AKGfa7cVS7Tj1gEbuD
            29CK5pK7CUL1jfCan/4FkPXQ1RnxDoZkI6CM6GawCvJRTXuxgRpz+wBXReT0KZLg
            ag341NeStFYHrEIiIlqLpLUl/Tu3IjfxeRjzL0cJG5tC85jWcG3NCO/iCuwQPrDb
            ur7DInnO+8Ks5pFUcFW/RxXFermpBWYxzcOAMFwK2++HJc5DP+1DTPCtJv8Lyomp
            bQpZ2QJ/tx6eCpD+kUqWZRrsQBIbdFR/5SQ3kIe3Nx7FvY9Fd++i6efwk5ea65LW
            FsmyfzOr+rxko8FgMK4WVqvwnDG0yMf4OEC6AD/Wzyq7jhuSHBPfCUQ9kY85QavY
            1Lc1HyTEngLXvP6XmoQlMrZjWu94bVRS4Pvtbs6MqMW7py73cBAhe/mSQn8eUbbS
            XgGplt4rX1y8XRG5EkBrzbt6qEbEVkXlp8Z/4T+K6SxyIRJKrXLedv4kxJvvmWJt
            IqLaZxMSigUro/RT0vZE1+gPNgdtDGv4PVyHIVq+Hdlj8QB6q16NvLSfhovRBJE=
            =YogM
            -----END PGP MESSAGE-----
          fp: 1DBC3ACFDB8B1DF2C44CDA23996024D3718273FA
        - created_at: "2022-05-30T19:12:36Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxbwxdi5IniFARAApp1tdHy/0Zs2p5XBR7i/530OjqbC7NK0C4tpQw/HjKrg
            YXXdD/SCtIU8QM6v3+XofOtezhuoipl+NfsC3F0DJcvHzS29f1meVWx2SpDYWlgR
            V0qFN09hFPqTLOdD2HyMoOLyiaGYABCbKITuDaNaGSx+2a8S78di/oWxfaEYPkO+
            R0JffIsuuEREOOWP03Capk3rWaCMfMeHRQmtO/y6wLAS8k0DKtH1AnwlfFfuAhkd
            RU2hxQIdocT3dOJQidBRh2mKYHAzj30ANRSYYtZ+0UOlUQ99LB+s9MgopLNNhUJh
            toc5ErA+mPDerRXN+BZy5HBAk+zl8Wo4zGy17f0fCbxX9h1cJUm0jRTyic8Tfc9Y
            Y6dImIjVTT+4Wh3xq3ke/fwQhr29D//e+ODBDzAz3RLUKtBOnUA4z1eQvKcvl6c2
            VVV8qCy4olmJqS1tM4Y99PgHshElhPoRpcT+htMwnJITK/6xdS39kJU8lSi/l39t
            Zqu4/vVgutaXMQrNsK7cl3p8rsMnDQL7yWFdvlIM8hHJgAZqaQKv4YUaSG8EhsRL
            ixRojWMOWuq0lgwUjBWtFvRSdJTKTvZs6myaYsQp1X8d/k7eRwvzSYTt/sBqs2XG
            Ij4QvPzeEY259O7ByvAtKexzjk2NP4m9h92c9AazUgxxXFsi8ZzLKYe8iWXxi/PS
            XgGRloNZj52M7hkFAj/2ZPLB8PcnAN4qbPx8oF0OE/4EwJpje24A7wcwJKM3PQBv
            YFCAxRSYjXlYIFFBpW4Udr/734D4O4NFxJmf/5z4g/ORR8FebhV7S0cUl17nZFE=
            =3ITY
            -----END PGP MESSAGE-----
          fp: D9F3AF2D9762D61A974DCD3E7B318B162A7DEBC9
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
