# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: nebula-conf
    namespace: networking
stringData:
    nebula.conf: ENC[AES256_GCM,data:tbi5pwDeWbXJpX7k49/KHCgxXIBtHfEKI/+QOes3z682NdwcDRLad2YFgkFSh1HopOksBLzpemxIXcB88jS0auYo7/NWY80N9wPEF0IdWpImXjnwuAttTOY1URfj4IAahd3HiFKsMsK8Wl9TqSadzMZGrUhff98D9i6n8s9cyo9XgE7wjIU4IdLj6i3aehEzsBNUEcFWBO+S82u/SOgB83yFc9xHMmFHdAUiXV0+dT/yKxb39iOObWqWKbLJkr+SKv2KF6OXBL4lLIuta2IlRhbgeJPSKLs0tC5JiOaKwp9UNJqp25VzoxFuJ6Ov0gneJN/avGgr631ANcH6M5uLZdc/9GmbnO10LOxO+vV0uQAjpzKNWr4xqrNU1QkfAM6/sBd98PdFvWu6EQAayocx9cxw+BK4e6FFznH5E3y2xoKgJc8NbUrgnmlRF7cohCfy77vU+otCV5tgtAH7F+qdYhjBUHiawgNW90kQdtO3KxIaop0dyhhapa2joTZJBJCuGEIzPLmgo1dmfvVl3Y8dhprzYTFF/46yVJjyroVxXWKVsoMN1v+IX3F6dQ7ZfkDfpNzTtpjX1uh5t/LwHs5WuUtMhnWMVSUYNW1lPYJnmR7dQNACZvAwb0bAEk+xWpjO/Dduuxm1YSO8regrZlEaFA5lN6AxDqzXWM+jcdpw5EppxOxokaRo29PxDf/K6S5Dhj2axEcRYfrfg4I+SiSTAUGDzMDzrIhsgUVgYgBAoBtdeigq1WZnqoLfe/iPxhsAiJZYA/6vJFvjVYv12Y+7rr5M26LAqLPwBD7WVY2KlnhD/2THa07i8f8uauR7v3jyuX6jbUgmL2tbnxXTgpqKwptjUvYfi6fIk7wHFrvKLBJHXDl0ni719R/RtEShCEdFrG01wqHmyEWuyxYmbuzRf8FOzOHrQOcvXZiSzkncWWrNQ7ZxyJk/dYkTXK4baFvoKba7RAXuK23mqZeTqPp89HNdxCQm9/WCE24BbSdCLharHuZoY6BeOm/Ik88ksQj+65lITh3VHUZetniicUJlj8GHW7x4vZxzywLjfqdRqn7j9c1AEZ2aMn6fdpIdHYUxsyJMfhb1ldHwwtcNa1sgDuHOKDSAQfp6EadS8QuI+aCdVj/O1a/o1Rnq7t3z/C9PPot+3YNEuwyigxWtijmjDSTUjVtVZ2jxOwWkqsyGHNgEIaYvV9ZSph5t0vx7sNpQo8kjVhkQgY2WFZNJtyJHLhkgSYFRibL/HssA/83igrly2iYZUsGYb+h1OOa88T1WxPPBexoTu6U8Ws9TRtmCIkh35+yauNyOVkYaLZXJ+ONbd+bB1h+l3vgYqpwfutdJIViWks4qCJTs27+IY344A2BzkYOuYvXelt1UX4Z1IqLsDwEWrGxWP9IlCSq52CDOUVyOgE5b5shAbIESTkcGzrjVkcXxKC/rlzCH0sbYghaJJRZfRvtuDBmHiL/5LG6RHcXHsMCkoJC8g+E54KEBGs5QswUA30CFP1kDUm/dLnRPEr0obfV77Flzw2vhux6XCWQ9nBRjk4WNi/BZolvLITN4qfn+kQfVxlZdihmNZIQRPoI8TM92Rv6NRCitR2dRwRkZsKCaF2enYqoJCFWqgtypk43GgAjh6X0n7mO5uBCTvhF3Y0pcppceY7/liwBthU7nc5vyZFqCqLmPKtizO3xLOHg43ueyfX48/aUqcEJqP61J2GFAEfyDaetP0elxBN7MGbUMtOzoL1Iu/T3AMSPIiuJsbhxiOHY3JM1sYFTaLycl564hMQYcY3FpWjdkwobcWt/jscKOP7IOvqMPqBmX4YWIVXpxVVfQK6G0hATK/+FQP712Pt0WsUEg8FmkpR4EnPM+4C/BkZtcIprsnB9S7gboxvPOGJOTjudPvjXYU58WTPxMQAxYCv3cxMqeSBLw9el1pCNa28kLn51B7eJxaYrNnCIaE+gxJaLHLFtfvWHOSOU2ZMiG817M3xHeCm8e7R4Nr09muDXivWyfX0B4DQfh1WwF/BhW21bCV29YuVBCbDdaSTQKlFJOFU/cRN7dyafNm22pJ7SbUcnlRw9fSyeAH8pgMD1BEsyqqXx1/c1yxrjJ2xhBzslZu3+Mu0EjIJKJuLrY00dA4GQXJ+UuQkxxoSViqhLntRtZwfrWT7ogWv5cQ6nSWpM/ufzwk5ZoMZDDedDbTx/XGkNbApJJulY6NNxT0lFYqnJXcj7urOdrIN3t4OuzdIQnh2m/7PcCv4Tgud/DFR/XreQ7tYANmxekkzCRJC0NFVI2T+MdmTDOBRlT3dlChYokxvAXb1LjmhyqBLi3Sytty28=,iv:imuSjPCIpXdJHJFKr5iSa44B6T6GfPrE2k1p+LNwi2E=,tag:peqhd6HXQCk7bGULn+KJ4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-05-18T02:16:06Z"
    mac: ENC[AES256_GCM,data:W4Q/i65Uz+QM9017CaMutv1iqr+Hp1ZVuGDtXeVQ9yXyQlTrRgUSwQfcXpzIlCA6mx9O4LVmge380NSwfdwqO55snJNZiUolibh6p3AR4w7pQ0ZJ6ydITX9mzT3KIXL+XrcE6PhC284JwUzzrgFExnfkSjqMLHnzHm4YOmAZRTs=,iv:Y6f4szhIIabrvbGlP57v9F3r4UiYGLyzHJSkOeev0rw=,tag:8Yk09H1Bjgt+96WsGWTGgQ==,type:str]
    pgp:
        - created_at: "2022-05-30T19:12:36Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0dSZMvnEisuARAAnQobw/MrRqWvV2cPg9VSCA3yue5XW67TGVw0KCGNsy7A
            N2YqqWYoSqvZf24W5sY4XWH0rVcSspkbvmrUycHuTdjr6RiwO+dvgGZ8P1kO1/+8
            2FyYqzaPaTMAKTvrcztnY6SgV7v+SW6moEDttm74YtnCj9TtkqACTa6Myk+I2h/v
            k8Mvk5IsbJ55ltfzcfiwCa3P1eD+ZEMNte4B3e7cD1udT9dntJCBB+C8X4WAq++U
            ppzW82o1O0O0Ki0FX0wklelvt/XNxfgak4nohfdKHeOTR2AKGfa7cVS7Tj1gEbuD
            29CK5pK7CUL1jfCan/4FkPXQ1RnxDoZkI6CM6GawCvJRTXuxgRpz+wBXReT0KZLg
            ag341NeStFYHrEIiIlqLpLUl/Tu3IjfxeRjzL0cJG5tC85jWcG3NCO/iCuwQPrDb
            ur7DInnO+8Ks5pFUcFW/RxXFermpBWYxzcOAMFwK2++HJc5DP+1DTPCtJv8Lyomp
            bQpZ2QJ/tx6eCpD+kUqWZRrsQBIbdFR/5SQ3kIe3Nx7FvY9Fd++i6efwk5ea65LW
            FsmyfzOr+rxko8FgMK4WVqvwnDG0yMf4OEC6AD/Wzyq7jhuSHBPfCUQ9kY85QavY
            1Lc1HyTEngLXvP6XmoQlMrZjWu94bVRS4Pvtbs6MqMW7py73cBAhe/mSQn8eUbbS
            XgGplt4rX1y8XRG5EkBrzbt6qEbEVkXlp8Z/4T+K6SxyIRJKrXLedv4kxJvvmWJt
            IqLaZxMSigUro/RT0vZE1+gPNgdtDGv4PVyHIVq+Hdlj8QB6q16NvLSfhovRBJE=
            =YogM
            -----END PGP MESSAGE-----
          fp: 1DBC3ACFDB8B1DF2C44CDA23996024D3718273FA
        - created_at: "2022-05-30T19:12:36Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxbwxdi5IniFARAApp1tdHy/0Zs2p5XBR7i/530OjqbC7NK0C4tpQw/HjKrg
            YXXdD/SCtIU8QM6v3+XofOtezhuoipl+NfsC3F0DJcvHzS29f1meVWx2SpDYWlgR
            V0qFN09hFPqTLOdD2HyMoOLyiaGYABCbKITuDaNaGSx+2a8S78di/oWxfaEYPkO+
            R0JffIsuuEREOOWP03Capk3rWaCMfMeHRQmtO/y6wLAS8k0DKtH1AnwlfFfuAhkd
            RU2hxQIdocT3dOJQidBRh2mKYHAzj30ANRSYYtZ+0UOlUQ99LB+s9MgopLNNhUJh
            toc5ErA+mPDerRXN+BZy5HBAk+zl8Wo4zGy17f0fCbxX9h1cJUm0jRTyic8Tfc9Y
            Y6dImIjVTT+4Wh3xq3ke/fwQhr29D//e+ODBDzAz3RLUKtBOnUA4z1eQvKcvl6c2
            VVV8qCy4olmJqS1tM4Y99PgHshElhPoRpcT+htMwnJITK/6xdS39kJU8lSi/l39t
            Zqu4/vVgutaXMQrNsK7cl3p8rsMnDQL7yWFdvlIM8hHJgAZqaQKv4YUaSG8EhsRL
            ixRojWMOWuq0lgwUjBWtFvRSdJTKTvZs6myaYsQp1X8d/k7eRwvzSYTt/sBqs2XG
            Ij4QvPzeEY259O7ByvAtKexzjk2NP4m9h92c9AazUgxxXFsi8ZzLKYe8iWXxi/PS
            XgGRloNZj52M7hkFAj/2ZPLB8PcnAN4qbPx8oF0OE/4EwJpje24A7wcwJKM3PQBv
            YFCAxRSYjXlYIFFBpW4Udr/734D4O4NFxJmf/5z4g/ORR8FebhV7S0cUl17nZFE=
            =3ITY
            -----END PGP MESSAGE-----
          fp: D9F3AF2D9762D61A974DCD3E7B318B162A7DEBC9
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
