# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: nebula-conf
    namespace: networking
stringData:
    nebula.conf: ENC[AES256_GCM,data:eJ3GlTJnDp+93BXJ4YcocUDu9PBZYGiD0TPyw2Fl/oONPF/sc37MkPoyBkbyao8ass3kUokPTLzZ0WqceLnxAcVI1k4cgIMwowMEApv4fdgnVUJPVePwxUgqBGz+cBGBb4bbnD+4QcuLtd6fNGHRHclKzMEOc1k4iL0xobGUdIIic1b0vEoLJPFF0G7BxlfJNrMpYTDW29DNxXis2Y2BST+gqroOm0dqCm0Zo9AHj5pnQ0XgUh+R6U2W67vk8/5x0gKkYML1PacNS8YG2Bez039RpZ/V+5YBUfd4XUntApO+SkoM3vqGF4j6RI6344sQIUuV0ziS4MMLAeB6ZkUqTvCYkybZaoAa9Q99l8osd7Gxab0Cey5LmRVXH/xs1Ir+JcvL1exJmXnL4F87tebL/zIh/y9xMoJJENmb0ptd7KvUfk8W5l5K503GTq4YLHqLcUAHfWdZvms14vEtT4H6zh7q97S56jaf5JWRU75UuC2Xu9lFz5d2i9Tc/JogLHUXFpUEGBnMo+y8Z5GuTHwiGKHYrCWdLIA3+tZg6vKscL4ujtGT2ivQU12R9A0FeIwbhxF5Ddhg2LFq7iIj4ln/iTjQ8odtJU6SwMl+WLzAvUjw6IW8mbJZhVef2FMhyg4P6s75uLsFP2sfLhV/hhdPLb/A7yh47tEW9NaYX9/rWQDd06sGSgqf7PzCIkOpPKw2WymKx8KqhR/AZZ9l26AMX1N/m0221lEDDyp00qTBPG2heRHhdpSWsg+lBleR6mDaQ6UyjoLFUsP8g6RANY3CZxqSl5ZjRCHYp4o3jdBKFe6zZD/0tBHFMbBXhyWF2eRUTHYjcMQ1cCN/o2U19At5AAxj+bmKuqYqqUoV+lWbXb45n0RSYUvLbFIF1Shb9U+tv5B1P/zfhAXOo49Z1uBp2UjpPXprTYY1dGe0IFb88PbvSgl7hUYqhcd7QmHGP5vd081Py4n9ZPRuA/h9eRqdCXknn5KpvwKOJeXqwP9VYNLdfOTJ60VPNrYueaMN/1MEAJLJxweKxkDPmFo+XS22NvpOM33vtNs+Jk3tJM0aFNUSV2jUYuFqkmEtTWdGQcgOTU1lcVahwzNnziMJ6oGDpCqExxz38hAbr6RvPiYUR1NuCh3/gtM+bIe4bGVLiamz7zOc3m7cMeY/L4rWBLG6Msvw2oVWfDyZzqiyADwaHdHLngeO+cpPmAR9tYbIGUiiiz/N3qHYRXK6g91f9GbTEsv+t9W89028T+dD/5cIDRHA5HC6KFGX11sosUsLEMPUo2AMLXrQFc4FnIxcUzQzFjUyYWcAkOiysasEj5ekl82DPyQr9w6excvbsSFGOL67AUrKXryvVA1omkhbO7rmyk1hLG7sLZa7XdNlFALalaP0SIyTiSxSG+NACf2J92n/RG8O73W6f22XCXhvZxade8w6TSVYAxEOJvuYah/EF/vCSwhIQ00TKEYx56i8Wc6LpWtvOlELwQ6Zk1HUlc8p3Wk8pGjiVJEcGX1DD7NCWnLKGumVhTCWnL8b1SLQnx3WJ+0PUJdPCSM3ocLbV6ESe4SHm4RA1nWl5veBRms8TrtrciqzubY4eUvVraN90D1ONlwrjRBsEqfnXoEbgAe+WR3fPQfw5CtWZUOul5zxYZvg2lie4QS/qF1U/vQ4DsgxJa1ksSrDJt0+bTCvfIOqPS2w+sR49aQaxL49xntpgRFOdwRcSaxwEvSHIqAlKOBtHXGU8MnTl0SE9brpqkVBmcr5BivXcHjxOIH68L4mIiig0ax2rkR2IYfBQYLWEUEg2b3te45sj6PTOt1ANim0HM7uhRpoBbXzUzQyA8cz1hpMOkkrZRwPSRUneONcxAsXaevRP3F4sYwnxS5V2pbATiNp5vmiyVzbFTL4vwUpd7syC3ecLIumazGlWVfS0knmeD0b4qf8QqftmLAOwSQEfAHqZ3hoqJDuFRrUeaBL/WXhIgihvszENZzBWfE0476CO5Ov5voZ0V40rcu4JqXDlZBNAOsyB13l1R2A/0NJBz/3v8B2SnKjRArwlHxd36XN4BJlJq8YopvD4oOvt3KmDWPgTbStraMU1xd6ysJJxlVBqb16NzdV20RCjrJ6apRnh3+uK/DN7Z5Ggolxk92Q8nE7z+kICLmh8Tg247JoVbFy9yWKVR9HNQxf2LBT7AkbzV5VN5g7gZY45Jti9tILe/4WqBBKHR+WA66wqaNvE3qsHE7ZxZLKL7ZsfnF4FqB8K7Hns/8mqqOvrDXVbywgzfU5xXjbo6Eo1oL6NIpHKPr4EC0AflIQyi+zhVSZLsSVhP5/s3YDCkHuoMF7tDjzHEykda/N3w4Z6k6CgOGdFwfDCscTsOvTlN1YMsz7Exy8oEmQWCaWe5tuSHwWGp1FzYD3OmnppZuABHoD7zH7Nf0tGjlMbJAWjTvS6ek0Rxkjjtq34thO3U8qcNuPIEL1Gwb56Gh+zGoWdY/JniBlbO4+6500Mbelgg2KzE0gtzvFcY1oNjePLTKGbxvIKNu86O6m7ZSUEJ3VCteL0RO52V/N,iv:v0CE6QftPYL/OTMzOaVhgOIXvkmhchNIBAckYeqbsXI=,tag:/xX6TIcIge0nWaJUcMj+dQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-05-18T01:21:09Z"
    mac: ENC[AES256_GCM,data:5x5qEiqu37v6JcxOdqUBSBXElhlaIgrrHLC6TBX7ci4ym9NNuQ4FnAepdQoDFRKE0tHeBbJJBpJdo7FlaCOMoLWBxGUmxqBWdsgrE+LsQZvuT53QCYCUPOB2ISk1QAb14khSCAlkOF83lLwtY9kgPgHoluv3radxPWC0YXnjUGY=,iv:WQdKmz8ciz+UQtZTbY3eiDexRlZNDRSoecSWTN6xkGs=,tag:GG3kA5Ijf4Kj562akYXvog==,type:str]
    pgp:
        - created_at: "2022-05-30T19:12:36Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0dSZMvnEisuARAAnQobw/MrRqWvV2cPg9VSCA3yue5XW67TGVw0KCGNsy7A
            N2YqqWYoSqvZf24W5sY4XWH0rVcSspkbvmrUycHuTdjr6RiwO+dvgGZ8P1kO1/+8
            2FyYqzaPaTMAKTvrcztnY6SgV7v+SW6moEDttm74YtnCj9TtkqACTa6Myk+I2h/v
            k8Mvk5IsbJ55ltfzcfiwCa3P1eD+ZEMNte4B3e7cD1udT9dntJCBB+C8X4WAq++U
            ppzW82o1O0O0Ki0FX0wklelvt/XNxfgak4nohfdKHeOTR2AKGfa7cVS7Tj1gEbuD
            29CK5pK7CUL1jfCan/4FkPXQ1RnxDoZkI6CM6GawCvJRTXuxgRpz+wBXReT0KZLg
            ag341NeStFYHrEIiIlqLpLUl/Tu3IjfxeRjzL0cJG5tC85jWcG3NCO/iCuwQPrDb
            ur7DInnO+8Ks5pFUcFW/RxXFermpBWYxzcOAMFwK2++HJc5DP+1DTPCtJv8Lyomp
            bQpZ2QJ/tx6eCpD+kUqWZRrsQBIbdFR/5SQ3kIe3Nx7FvY9Fd++i6efwk5ea65LW
            FsmyfzOr+rxko8FgMK4WVqvwnDG0yMf4OEC6AD/Wzyq7jhuSHBPfCUQ9kY85QavY
            1Lc1HyTEngLXvP6XmoQlMrZjWu94bVRS4Pvtbs6MqMW7py73cBAhe/mSQn8eUbbS
            XgGplt4rX1y8XRG5EkBrzbt6qEbEVkXlp8Z/4T+K6SxyIRJKrXLedv4kxJvvmWJt
            IqLaZxMSigUro/RT0vZE1+gPNgdtDGv4PVyHIVq+Hdlj8QB6q16NvLSfhovRBJE=
            =YogM
            -----END PGP MESSAGE-----
          fp: 1DBC3ACFDB8B1DF2C44CDA23996024D3718273FA
        - created_at: "2022-05-30T19:12:36Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxbwxdi5IniFARAApp1tdHy/0Zs2p5XBR7i/530OjqbC7NK0C4tpQw/HjKrg
            YXXdD/SCtIU8QM6v3+XofOtezhuoipl+NfsC3F0DJcvHzS29f1meVWx2SpDYWlgR
            V0qFN09hFPqTLOdD2HyMoOLyiaGYABCbKITuDaNaGSx+2a8S78di/oWxfaEYPkO+
            R0JffIsuuEREOOWP03Capk3rWaCMfMeHRQmtO/y6wLAS8k0DKtH1AnwlfFfuAhkd
            RU2hxQIdocT3dOJQidBRh2mKYHAzj30ANRSYYtZ+0UOlUQ99LB+s9MgopLNNhUJh
            toc5ErA+mPDerRXN+BZy5HBAk+zl8Wo4zGy17f0fCbxX9h1cJUm0jRTyic8Tfc9Y
            Y6dImIjVTT+4Wh3xq3ke/fwQhr29D//e+ODBDzAz3RLUKtBOnUA4z1eQvKcvl6c2
            VVV8qCy4olmJqS1tM4Y99PgHshElhPoRpcT+htMwnJITK/6xdS39kJU8lSi/l39t
            Zqu4/vVgutaXMQrNsK7cl3p8rsMnDQL7yWFdvlIM8hHJgAZqaQKv4YUaSG8EhsRL
            ixRojWMOWuq0lgwUjBWtFvRSdJTKTvZs6myaYsQp1X8d/k7eRwvzSYTt/sBqs2XG
            Ij4QvPzeEY259O7ByvAtKexzjk2NP4m9h92c9AazUgxxXFsi8ZzLKYe8iWXxi/PS
            XgGRloNZj52M7hkFAj/2ZPLB8PcnAN4qbPx8oF0OE/4EwJpje24A7wcwJKM3PQBv
            YFCAxRSYjXlYIFFBpW4Udr/734D4O4NFxJmf/5z4g/ORR8FebhV7S0cUl17nZFE=
            =3ITY
            -----END PGP MESSAGE-----
          fp: D9F3AF2D9762D61A974DCD3E7B318B162A7DEBC9
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
