apiVersion: v1
kind: Secret
metadata:
    name: nebula-conf
    namespace: networking
stringData:
    nebula.conf: ENC[AES256_GCM,data:GkRSPKIwR436Ws0PGtQKoKXp8EBs8emJGQ44nZ77OmnA18UYV+rugLyn7k02rTWef4PINcD5Y+VHqesvKUO6pWfcLLQYNPaesVLWz/eLbUGZgT+qlHWzQUpE5dPH8MtewWU6eyG8jIVxeOZ/OQDX8M5xuRy5A/I9IQeZnIOs6v+Jcma3IuaE0crzU0OZ8vtYoM9OXkhdPgTsxviyG3ysGiC621EgtuYmVr89gB8lWYmW2KSk2bjsjXL5l5n3LjLF3W2cmG03ncGAN79WDFRQEY8Yp9bN/GOYUKG1S5hy6vnktXNtMhzHPoG2T4Bbj1fXRI9ET06erdbxeW3TKl4QkyInHXpA+/+eR95Beykq8xToZVtOuPmRQsZqFqx/eHcNTvstvWwcpIUNABhmgbDfPhu7iCr0igFSgIwkZ9wCZ3fgqWeZBOPKjEQpKnkTFPjQV1AZ9CT4GLPPAcy9DuDMsvqrpADmPrUg5o9O68RnZZwfYmKiuqOAMYNzB7ViGu8uBdaVeQ+a+QqytWVD7nZtSAdOi0nrpMvH6xPGLP1CZP2Jf+mm9FPp0MNYldKLUnIITPKuKX9LZ1lqW814CZqN1DfpjMM8/cjjxq3EwN9oYxUdmfYMvU3XI0qAUyOYfP0lwkjZjuDU2gBkAwLW6VaLZcnHWLLzMLyFXWqzIsYbl/yATlyt/ZzgutcUmoADtDNIg7SPUaOpw9wZexFk80MRFjK4KSfOHRLyty8mrxjz7PH5tYFZbEuX2rMwiJJhKnCfHifjHxBfG5RfuIU+WlowkfPyNEHCnSMkpHRiUGg71iwlz9seuYf4ovVw9rdqP8xAxH5pcinQH6DYZZDLK9VIta+an2L41YwK2zmcD8mOh7pwATtCP27PxZ3eAqXnxZRuMfkPlrBGpuVUgF/t2/960jhQhhgQxd/iIUZN//e+Gv8CjpDaFIfUpS1Kz8YHl2Qp005bJHN0HRl92xer6qXKcoZhtK4NxBFj8LJd1o8ns3Z+jMxwCHtZjIZf+DGmddi/2ncU0rtevhSBSpG+F2DyAwwpn04LL20eqnTNnX5MSi5BwTGnwkyo0jp0yL738FPV3d4iPRwevl0DhdkdtEax01O2ZBE3anLmKB5OCOZMbgFdkyAc0HZ1xtVw9v94vRe2EJ6uAvzRZCCym7Z7Ul19qmIe6iykMHminYG/Z6VCxMTcrKl0rxNNB5CknlnD2B3tof64pG9wGTpxwjerq0F9A9rHcujekN1kwJfoTgKWcpNxq5IXrF5ZpG36jCAkurByWAl/3qcfLqfzuC4deWBiY+I1yyUOqVWj9jcHsnlj9FZygPcV309Y/Y5eqZDDQ9GTKPXUKOCNeiyFJSayuMzmPbO5T/jY0nOQY+c+XeQF0207EQD4R5UNm9NkeIZdW38J1OffEFMRyTWwJwM80dCZsqrSu8UoXRpw5vU69nWf6/OkFQuU2FxgGhXFrVsrNLxBUVcrPl/3aue3DIGMZ8BHNunqHUw5TADJ161p6DRR1HOb2n/RY0ThU6q95bN12JIN/+E720ooulUFbr+1KinqJ4bCIljqfaQAX5OQf08iIUswDquXsrq8aqTLXYzEqgxXWtITXZrIWWgE4Rj67EXjywi77ZAtrkJxn+nowlN4Lqi7cMIwEhzu5S9h+Wr1wwom5MAhsLY8Q4Hy3s0VtLcOBPwnSzB3yhcvMrdI1Yv6GtXpSezfdqC+J7QDISivg/b7gIKXuumuH/Y5FgEpkcjIOumgGiUocVCvIj6leS+Q72mji5KGQETQIVEvrLaksqB8ips5JwpxKQvdt+i+7HfdJK5rcO63CZBfOsqJT10+2ZWI1Ug9GaIlYiK4mHICQirUJ1oD+yohB77xqABaYnhgaMoNVDlo4o38qiccyh05B2SxZn7lbRRtLUMkTya9cgePMC2gi8CDkPzVe5gKTWNNq5agKLPi6eRJEImbEOKs6tNHqDhs1Dif0xdmWjWkKpXFR9olGGfmIQMmjGZHm/deb9bPHb+MWF8Ags9gWdscaXq47DzupURa6MvS1bctlbxbPwXY225YHvKPQl2bAAxUHpbCn7ycUvQuCrfueob8DRVZ0f3uT89Enzz7yznaw3gwa8elQr2xTNNe3JLHKHArNJWFSsWPJt9R+r6Cpk52LoIiyGnM3CjuZwWzj3+DvK17FiLBOFvc7tXpfDU8F0ElwrrJ+iiOFL3hGhzc/fbbRdeOeE7sYqGRNoc5UispagBbKyr1BNk1uq3f34BbdmX/sN0mo5mQ7gJLfQdoBIwSkcAPRm0WMA==,iv:mXKF9EZzrtBQ/kzkszzb53MIgKEo6NOSNs1moXXzsLU=,tag:Eh5eAPLcS7qr4tmRRhyt3A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-06-22T13:38:08Z"
    mac: ENC[AES256_GCM,data:zC/VulQnZC+Shdwd+JbL3qJpJjPIAHK1LlT3JqnorglFY7EQhR1+B8SZe8hhk5fqblkKNGvxHXxgiLmtPXPMhNyHJms3807IY8JV1BfvrRoO8lC0z+73MjGnFEX/V5v6hzq9uhoIU26F0KFdA0BePzcgOD1kj60jIcZOF+nMZqE=,iv:4becLFRKOLcMV2nlZp9BgNjwHSqbsep3tRaax+qNX0Q=,tag:jYA5oJbi+5uiwHkGKGTYnw==,type:str]
    pgp:
        - created_at: "2022-05-30T19:12:36Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0dSZMvnEisuARAAnQobw/MrRqWvV2cPg9VSCA3yue5XW67TGVw0KCGNsy7A
            N2YqqWYoSqvZf24W5sY4XWH0rVcSspkbvmrUycHuTdjr6RiwO+dvgGZ8P1kO1/+8
            2FyYqzaPaTMAKTvrcztnY6SgV7v+SW6moEDttm74YtnCj9TtkqACTa6Myk+I2h/v
            k8Mvk5IsbJ55ltfzcfiwCa3P1eD+ZEMNte4B3e7cD1udT9dntJCBB+C8X4WAq++U
            ppzW82o1O0O0Ki0FX0wklelvt/XNxfgak4nohfdKHeOTR2AKGfa7cVS7Tj1gEbuD
            29CK5pK7CUL1jfCan/4FkPXQ1RnxDoZkI6CM6GawCvJRTXuxgRpz+wBXReT0KZLg
            ag341NeStFYHrEIiIlqLpLUl/Tu3IjfxeRjzL0cJG5tC85jWcG3NCO/iCuwQPrDb
            ur7DInnO+8Ks5pFUcFW/RxXFermpBWYxzcOAMFwK2++HJc5DP+1DTPCtJv8Lyomp
            bQpZ2QJ/tx6eCpD+kUqWZRrsQBIbdFR/5SQ3kIe3Nx7FvY9Fd++i6efwk5ea65LW
            FsmyfzOr+rxko8FgMK4WVqvwnDG0yMf4OEC6AD/Wzyq7jhuSHBPfCUQ9kY85QavY
            1Lc1HyTEngLXvP6XmoQlMrZjWu94bVRS4Pvtbs6MqMW7py73cBAhe/mSQn8eUbbS
            XgGplt4rX1y8XRG5EkBrzbt6qEbEVkXlp8Z/4T+K6SxyIRJKrXLedv4kxJvvmWJt
            IqLaZxMSigUro/RT0vZE1+gPNgdtDGv4PVyHIVq+Hdlj8QB6q16NvLSfhovRBJE=
            =YogM
            -----END PGP MESSAGE-----
          fp: 1DBC3ACFDB8B1DF2C44CDA23996024D3718273FA
        - created_at: "2022-05-30T19:12:36Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxbwxdi5IniFARAApp1tdHy/0Zs2p5XBR7i/530OjqbC7NK0C4tpQw/HjKrg
            YXXdD/SCtIU8QM6v3+XofOtezhuoipl+NfsC3F0DJcvHzS29f1meVWx2SpDYWlgR
            V0qFN09hFPqTLOdD2HyMoOLyiaGYABCbKITuDaNaGSx+2a8S78di/oWxfaEYPkO+
            R0JffIsuuEREOOWP03Capk3rWaCMfMeHRQmtO/y6wLAS8k0DKtH1AnwlfFfuAhkd
            RU2hxQIdocT3dOJQidBRh2mKYHAzj30ANRSYYtZ+0UOlUQ99LB+s9MgopLNNhUJh
            toc5ErA+mPDerRXN+BZy5HBAk+zl8Wo4zGy17f0fCbxX9h1cJUm0jRTyic8Tfc9Y
            Y6dImIjVTT+4Wh3xq3ke/fwQhr29D//e+ODBDzAz3RLUKtBOnUA4z1eQvKcvl6c2
            VVV8qCy4olmJqS1tM4Y99PgHshElhPoRpcT+htMwnJITK/6xdS39kJU8lSi/l39t
            Zqu4/vVgutaXMQrNsK7cl3p8rsMnDQL7yWFdvlIM8hHJgAZqaQKv4YUaSG8EhsRL
            ixRojWMOWuq0lgwUjBWtFvRSdJTKTvZs6myaYsQp1X8d/k7eRwvzSYTt/sBqs2XG
            Ij4QvPzeEY259O7ByvAtKexzjk2NP4m9h92c9AazUgxxXFsi8ZzLKYe8iWXxi/PS
            XgGRloNZj52M7hkFAj/2ZPLB8PcnAN4qbPx8oF0OE/4EwJpje24A7wcwJKM3PQBv
            YFCAxRSYjXlYIFFBpW4Udr/734D4O4NFxJmf/5z4g/ORR8FebhV7S0cUl17nZFE=
            =3ITY
            -----END PGP MESSAGE-----
          fp: D9F3AF2D9762D61A974DCD3E7B318B162A7DEBC9
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
