# yaml-language-server: $schema=https://json.schemastore.org/kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: searxng
resources:
  - ./secret.sops.yaml
  - ./helm-release.yaml
configMapGenerator:
  - name: crw-configmap
    files:
      - config.toml=./resources/config.toml
    options:
      disableNameSuffixHash: true
