apiVersion: v1
kind: Secret
metadata:
    name: crw-secret
    namespace: searxng
stringData:
    CRW_AUTH__API_KEYS: ENC[AES256_GCM,data:++0uOOPViaHDjEj82JqP6+vE45St6J8iWCmqKuuPJKqm6C2qlGP6QZ8BExYwZHJlsGL4WVbaioWLQEHaRQAVDA==,iv:eM0XxnLdBEKAE8wgd7Kp6ADYA0jTjD/0XtDaqLxcujs=,tag:QrXyie/GNZdqtmTNGSL76g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-09-24T18:54:01Z"
    mac: ENC[AES256_GCM,data:CDuNelo32hRO3dpASwfLSwkSLAbRXYhYiO3CFYduKcleXjnkqoo7bK7h5NLLy7EKzgSHCGzRfxHB4dBtlHpzDwbULcuQ6n4ontlrjQCP1GciFdzmiQL7TTQKdplMakc2zOsH2/3yjbqpfnhoFgfRm1/KxstG/IvjBFdTz5QV4hY=,iv:Tv/SU2fxtzBT6HuDodBmLtGeO+DCmzofdcRW9SGuD6M=,tag:kw27LjbRJW3ZZ5x2QQEMNA==,type:str]
    pgp:
        - created_at: "2026-09-24T18:54:01Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0dSZMvnEisuARAAiMPJTNLiJSRJ3PASH9CgATu2JW2tAG0DQzECyVD9LsWS
            jGwg0R5+X7Imp99NLKe2AmuOWzsHQyLPpvH++Us4kR/E+2v5hA/nJBYr4SAzKtL0
            xzCn10eGQuQ5uu0F4GgWQpCqBLRtLYcuDfs09c3sQXS1MvkhLd7FjWE3b6rgkqVy
            cC8TVWRWx3lbEfB8XBvuxa2yCZWkNuDU+kYLnBNn4E5sWebWhO3nieQyR8u1dp8X
            42TSnLa23G8PeGy2qYL6mNO9ilNHZwjTMabrfI/9zZwCSHoYbXbzpTPlPJAa632u
            4d5JNRwwBgtgaCLEjUj9RMTVtpzmEOHh4jIZAZv0F+THwjDSx383r+9myYNXeVdA
            sikLMJn/2p4WDrzd94R9GgZcTknw391WQsoInpRahHC2AyVvYh2I+ygL3mYD+UpV
            uN5hvpmjCLDXxrCfHOf9hjySXt56TG7TuG74fBdNlJfWsAQWcGU3pnUP/ZTNlqNv
            hFqQgWX2nsI+wsqfEWaOg4GgPc56/5AeNmTm1meqDeVORjQh/MYk5oQAIXvh6sed
            OcNU/T3YWqQsw+p5/SQJCzUiCh0Nrf2m7u65dtTMGdy6ByFZbR/NVKDWqANchcD8
            1QAT/tpdPPLdzHypHXzd0AQ+uKakAV1yjWcBJuZr30DoYYvLRWh7EqQd+el7tbnS
            UQF9IN6j6N/Hm5cRnX7vnwIKWuL2v2Kj0tsAAX22ivzX7P3yMWi5bpZpPwXuBRLc
            BOHHYdMrViqk9QuSYe/TtD1Hmf+3il5r3mtxscSNbrXN3Q==
            =zGSv
            -----END PGP MESSAGE-----
          fp: 1DBC3ACFDB8B1DF2C44CDA23996024D3718273FA
        - created_at: "2026-09-24T18:54:01Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxbwxdi5IniFAQ/+OKskFE9gPYENjOpBNnrubAyirP8dOHReB64K9YfCAr8u
            2L9fd7p92niKq2ixjo7WgzCMeljIhTivqQ65pOjo8npmkEGSBUS9fh2VxLFHiRD0
            Zf9LT659csPQU5LEgq/ksGV6fEMY37SsTLww4BT/5q5L6zG2yDUy1RIwrjpAzqQA
            AIazzo3CQ/PkRLhlZM9F/CIyvL/3992ujWG3UfdxkUcG4fuuerVyF4PY7P4jiE5A
            EBvLPEhbqQjXGff/pvsB886SwQFZBYabYPKk99YEGw8MkohRhIpcLLrnC+LaqTIy
            RNgM8NbmeYLPtPACAJ524f8ReBeesIpaGY7lxOP+8lSADdzbq5Cpsl0AkWa3bOOw
            7JpqyljiXZf3kfmLkErM/vMd5LvP7+zEavJlRr7508JVkc+60qMbEuJA7PjISIik
            m5lmZpZjB4Sx13SzBD8xbk1ZgC9wcGsEvMA3QYtZo0ecx3kJw2+WinuQPU/SF0zN
            KQguAIS4fXRQ/fT1wuZC0FV77YWlxS0q0o7CcS4i39qF4xfRdOCq86KvOX8HmIf1
            TcfUDBX6C293FFDimfHAJL/D0r/bjknysKcvMTVtxFknUFetpgrDRGqkKDhMapLp
            3X5YGweeoJyOE4WYEI94bQ0oytPgRYLKvO9IyXwXH7W2gS6/eUKMnWwnAgHF7JzS
            UQGyZjfcN4K9+5xy52WAjB56WD1mesOl6fFj3bcP93YMtYDUQGlFXzSK/7ukYCWy
            7GQhbVA9BBI9qd1ZFBdlre6khhZh89LzeXhA8+hyQfrMzg==
            =Rjfh
            -----END PGP MESSAGE-----
          fp: D9F3AF2D9762D61A974DCD3E7B318B162A7DEBC9
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
