---
# this is a hack
# https://github.com/helm/charts/issues/9288#issuecomment-711165029
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-prometheus-pv
  namespace: monitoring
spec:
  storageClassName: "standard"
  capacity:
    storage: 10Gi  
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /tank/appdata/prometheus
    server: ${NFS_SERVER}
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: monitoring
    name: nfs-prometheus-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-kube-prometheus-stack-prometheus-db-prometheus-kube-prometheus-stack-prometheus-0
  namespace: monitoring
spec:
  storageClassName: "standard"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
