---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-prometheus-pv
  namespace: monitoring
spec:
  capacity:
    storage: 10Gi  
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /tank/appdata/prometheus
    server: ${NFS_SERVER}
  persistentVolumeReclaimPolicy: Retain
  #claimRef:
  #  namespace: monitoring
  #  name: nfs-prometheus-pvc
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: nfs-prometheus-pvc
#  namespace: monitoring
#spec:
#  accessModes:
#  - ReadWriteOnce
#  resources:
#    requests:
#      storage: 10Gi
