---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: metallb-source
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/metallb/metallb.git
  ref:
    tag: v0.13.3
  ignore: |
    # exclude all
    /*
    # include crd directory
    !/config/crd
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: crds-metallb
  namespace: flux-system
spec:
  interval: 15m
  prune: false
  sourceRef:
    kind: GitRepository
    name: metallb-source
