---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      version: 4.10.3
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-charts
        namespace: flux-system
  values:
    controller:
      ingressClass: nginx
      replicaCount: 1
      allowSnippetAnnotations: true
      service:
        type: LoadBalancer
        loadBalancerIP: "${INGRESS_NGINX_LB}"
        externalTrafficPolicy: Local
      config:
        ssl-protocols: "TLSv1.3 TLSv1.2"
        proxy-body-size: "1g"
        use-forwarded-headers: "true"
      metrics:
        enabled: false
        serviceMonitor:
          enabled: false
      extraArgs:
        default-ssl-certificate: "ingress/${SECRET_DOMAIN/./-}-tls"
      resources:
        requests:
          memory: 100Mi
          cpu: 100m
        limits:
          memory: 500Mi

      # add sidecar for slack nebula to allow
      # remote access
      extraContainers:
        - name: nebula
          image: ghcr.io/a-mcf/nebula-container:1.8.2
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - mountPath: /config
              readOnly: true
              name: nebula-conf
            - mountPath: /dev/net/tun
              name: devnet
          args: ["-config", "/config/config.yaml"]
      extraVolumes:
        - name: nebula-conf
          secret:
            secretName: nebula-conf
            items:
              - key: nebula.conf
                path: config.yaml
        - name: devnet
          hostPath:
            path: /dev/net/tun
