---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-mealie-database
  namespace: flux-system
spec:
  path: ./cluster/apps/mealie/mealie/database
  dependsOn:
    - name: cluster-apps-proxmox-csi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-mealie
  namespace: flux-system
spec:
  path: ./cluster/apps/mealie/mealie/app
  dependsOn:
    - name: cluster-apps-proxmox-csi
    - name: cluster-apps-mealie-database
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
