---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-bulk
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-connect
  target:
    name: garage-bulk
    template:
      engineVersion: v2
      data:
        GARAGE_RPC_SECRET: "{{ .GARAGE_RPC_SECRET }}"
        GARAGE_ADMIN_TOKEN: "{{ .GARAGE_ADMIN_TOKEN }}"
        GARAGE_METRICS_TOKEN: "{{ .GARAGE_METRICS_TOKEN }}"
        GARAGE_AUTH_USER_PASS: "{{ .GARAGE_AUTH_USER_PASS }}"
  dataFrom:
    - extract:
        key: garage
