apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-token
stringData:
    token: ENC[AES256_GCM,data:o52maRyNw+RYQQIIR+1/F9L2qaUav7jDVH8mx/w1pC+44/jqKjjhtMLTfxhtQLDenBCko+VHiZpwmuDxjLiENtjbz2NPUW49IG1TanQvIVp2KR7Ir2cw+FkDIgfi969SbNbslR3h7MWoUFyd1pTIMHrn2/9e3nu7YpUh2CRVVbfvsBHdMXcLSCZVGhd4mplqlBa8J4cW9tY6YVqO+C280VV0JdqvVA46ccATwdTXe7vl4GgTgYuMPcEL/w5BScJXtDE4nPWK6ouSfTR3JrTHKFc41GaaacNmwG/G+xswkN/u48g84onHdeYzqlbrXx9K3d8jXb3CX8wXeseEP6qqU4xFx8EWFx9gO1nmRD3ineAVKWMHDeRZ6G9Su4AQ/rGtpeVvEsdBfCNLJVI1pak5UPH1gQcaHdzzy8k8+QxqxpPkOoAL2PPizCrlusWy0pzDs7FqUBQ/MZOSUvuKhLQyNdCUhSHlNspOuI35Ar63moQdlr2NVvX4/mxZWfDN6TYdrTkuJEvH1CHzd7yOy8Hcgtpd4GbkKI1qWETis/137qBoodEignu0JzslPYXgP3yvO3TCk47uRyxSgEMtVjjMCPFgr720vELs5hrdiM3EHbwVP9dmTPu7P2gHA2quDB7BSsQIJDRBidM0XYZYafijZPElXIWzqloZEn4AaH43BdubpGfn0JWLGSmkd9A9IdgS6Q/dRrhgTPfG6dLzqLj6JC4ptv9zOMxcQweGUSpHjD9KNJCPOm+jyjhtilZmIesWRW9VDj9GRq+5fJH61rlq/aAvP6YaiYBa5ZjOEyk8BZcytj9FaEVcsHWNRTQY/vuaB8d5rvt1MlsykE64DoeiSI2+,iv:M9gE4z6RNfiKhfiBOTX9ryeng1tH6Aa4Qs0uB6B7vbY=,tag:bJ6E3g2hPui8StkJsN+yuA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-10-04T18:14:09Z"
    mac: ENC[AES256_GCM,data:ybffGvEBvj2yB7pIFGIozMLbyI+KKaYPayAajXVjlyDlhHLtJihtjA0eS+S6nyRvDXZpoi9oWVHWRLLexmT0ZkmDIx/sQjJcWYGdWZeFJdnNIPg8aoFT1cqbxSyKhc10HVy4YJWVPeMsTaUiLo1AOSka7ZYcjF6uxJBBcMRKH1w=,iv:KJoGY7RthttyGzRsTm1blxT1zUV6le6G3hAc40zOpl4=,tag:ayK+OGzYSic2T587iOgLpw==,type:str]
    pgp:
        - created_at: "2024-10-04T18:12:04Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0dSZMvnEisuARAApoCSP0X9hg5ZKzxZFJPb+upCPxNc0zv5w/MDqOgIy0Qw
            IwE3chMedRse7M97EL1f2drfaydKxLcF7kHzj+AeRX4uTK9Z+NZ+hDwYvmcHC/Ii
            VhuKfKcyCJJ31FvHh//AHDDpWVVeoG37Q8Km5VE5Jo1BFygQcOJAaDx2xrbvWDQL
            7VOeQ3Xb0fmG0E5XIHo4qPEEcX9k+XgNtJsD6mxwoiM5ubZhtmIJtM+Txqkgn7Wf
            WAXrb8cU2XagkxHWe1WzXXUP9lwB0Tn+nQL9mv32u/aODYpMlU6iFglgJzy+oPh+
            DY0hRb8PkdLa+dkUD2GdTjeMEGnwaOop/NKHSurvU0NYxRv5+4X9IGgNWImQE+FY
            eSY/RCDQb73zndonqcwxdzrxy3iL6mk4KMo6qphX8sbN+YUEbNVDGsVovcvZra4K
            QckPNoO5yynbV1lblmH+TaTAJGHY9oY4pBz7mDbA3yNHtr/cqJpPkxIYjLSoVBCZ
            hTxrgCF7x4F4iK6C3VHSol/qdXRvuj6vDrV0lrYK8nBqLX3VcGS3f8pXfxZTmp9j
            o8u2evg3pA694M4DGlm2ozmxfmlxzg5tS+alX3foS5OrohIHU2gchag4IH/2z+gI
            1BjjSUZ0hqn7777bV7syuIpywA9pxCNxven0A025aRN1QN79tRxAkq+X6V11a0DS
            XgG2tb889a99kPw0aX7zsGPccYiqmGyufVNmoRyudk1qpRW0hH8LdelaQKxqiBhN
            taaQLBHZmNQPXyWHZkZVNYy8a+FdGzY9Rtf263Tb4J7hZhqSr2OsJboamQ7xWfo=
            =wLpW
            -----END PGP MESSAGE-----
          fp: 1DBC3ACFDB8B1DF2C44CDA23996024D3718273FA
        - created_at: "2024-10-04T18:12:04Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxbwxdi5IniFARAAi+4TVuAwq0vATWsYf74NZHm1fIKb2FhyDt8Gx3Huam+M
            eZNKZd9C2ZGK7Z5F/2lAKwsyUrmMbgBUib/ZsOhspQVNSmFySsD+pR74DufPauKz
            xuQpZzcE+3FL8RBIpHKSw2TThY0cRWjNePR2ZzNP55ZGKqizRkNniXkLsjpQKnZv
            yisE25spGTft98l5vzNo2O7HADatCus3BikE//6qiNFI50n+8T9OaHVg/WfQBpug
            Q/7NPq6nrTbh2wqwllCScy2p9MAyKz/3F8kqcd0bQEyc6hyVAY2ROV4x69fzDths
            BhAkIMa6VpEZru/EffV5tmG9/LZpbkn8ZmUHDft3PhbZ5YCJoCYNW5B5m2/ljAft
            YYJ8rgMf7pu9sm28dj3/8drgAQgRcbPqATXq9dY0dN1ywSK/saUplz0bczriRQIu
            TgUn3a5jI+/KpuJboCZr/jR94u6whKgKgFB3nchx4mENzXQkILNvxkyLxXhtEzx2
            DRZiJCoWQUuzOpWU5fHoYVzQrKV3EaJvjogz5CBi4uaP7ZYFby3wi1rGX1M+PH3A
            HnLXs7dvNH30vUB62HxHJ/KACbqpZwxdAUeYk+HMebcVcMFsGHrBDTYD7VhrVbhL
            FsDgExEsV/Q7wJVUCj9t8BQVjDICquP7i1E8c2/B90mKU5qBVoJL3RrPaQitsN/S
            XgH++8UJDNtGo2q1zRTFJsTByVo0q2MVe4ua0HPkrY3V8P+fg54ib1YPD+/B76q8
            CKQtztXk3m/NP6ZyOJU6G9TbCyhXQF9P/6DTEDa+CohE4Z8QoRXHvY9KpgzkXhI=
            =K73E
            -----END PGP MESSAGE-----
          fp: D9F3AF2D9762D61A974DCD3E7B318B162A7DEBC9
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
