---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: 1password-connect
  namespace: 1password
spec:
  chart:
    spec:
      chart: connect
      version: 2.0.5
      sourceRef:
        kind: HelmRepository
        name: 1password
        namespace: flux-system
  interval: 30m
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    connect:
      create: true
      credentialsName: "op-credentials"
      credentialsKey: "1password-credentials.json"
      serviceType: ClusterIP
    operator:
      create: false
