# json must be base64 encoded,
# even in stringData
apiVersion: v1
kind: Secret
metadata:
    name: op-credentials
    namespace: 1password
stringData:
    1password-credentials.json:
        verifier:
            salt: ENC[AES256_GCM,data:K87AyljiwNxRdaz4RykEqBtjvLeu8w==,iv:Z25QIydwLEUlwj9cdjedSmW87O7F4kYjXnRfckow9ZU=,tag:X0oEeKqcxyMyRdfcZBUigw==,type:str]
            localHash: ENC[AES256_GCM,data:RkukBZW+vo8yLgatkpAmFPbp7Xj9ClnPDRqP9wKN7w/zOAn+SIIZu8yBlw==,iv:Y6OSrBLoWdRLSTfFNKwi5VIrQWGv9rm1OZ7SjeWKTnE=,tag:czaB9zhDIUueBwVY13BADw==,type:str]
        encCredentials:
            kid: ENC[AES256_GCM,data:lwol5QvtfB6by8CDb3nEBGs=,iv:RxmvtOrEpcK/d8Daf7+78WrhMUkTRiKNowE4NgHSZZ0=,tag:Am6xgfDdjGKfrYhrgkkTWw==,type:str]
            enc: ENC[AES256_GCM,data:blO5sab0mQ==,iv:hYbKvi8c56jmydXzXCHTWLGZZ0Gwww13eAYmnkuqyhE=,tag:EO1i/N/Rhx+xK3Bz5W8itw==,type:str]
            cty: ENC[AES256_GCM,data:mNqq+7VtNySaFdc=,iv:OxpR2o8pjrSqhqHLTgX2tlS/sDgGZyTTeFTPc1IIaGc=,tag:e2NMVhOTbPFOJ7p8Y2o4mw==,type:str]
            iv: ENC[AES256_GCM,data:xO9TtYTfV1qH1abd0tr4kw==,iv:QWQV36soJQARnYEWFBs0fRBLhpSFpIIj+ymHMl61Rtk=,tag:lP//e7Rt0acp7aK5R3s73A==,type:str]
            data: ENC[AES256_GCM,data:l6XKvDDgthFykqh7yP5XtoumIUD0ID+pG24KNEJviWCgDsid1FHg+FZ3GWPxOH0km+izdbZUIl1HUnzkLU1K95yBCULjmH96FjLFDmAIOU6nEpv8n26j/z+00Hy9xxnucz0yFqGVbbn7zxf6e6pmyRKeArKp3Sghl2yheOP2RtbBZQIl57bfjELFt4N78jJKS/8kP9OR2DjHaS6RUgxDQHQULesryuoh2SMYv1FwWvkmWukhChandTgqTpVKFMY3iWhYNvn91TC5C0oDLXdp1PtLiJP+5v/EX9U1MBuVCmRCF6rhLZ21+zLOwHZB9HyRoLS6kWqgUq/Z5cFe3K6QYqEMuLdnw57d2DT924g6uCX/42LsXEqQGDzM5fo+f1UREksObl9y97DvwUpV2Z8pSgM/P8wi44S2BpXRlvSXL2oAmOrogl0y/3Oo0H3NetFdXjrawVXHtKobPogiDbZb4MPODgue0nHZBrFHF1Nl2b+A0TzdGZnDzCU6JDr/6H8EDEZwQq4vM1leK9/97xl/13AuYw+16ixwt0LFzRI+hIPSL3Vi9I2DS9m8AT9aw2WKDiEzEQtLWCgIG8X2+pWYyYeUpGXR8xPcpjIwTuQJtAnB1nKZeGZWXv9le9al43GIqMd/In/fp0tzOR87ren3wTfkz4xKmdlmzbari0lNtnSdg5jPD5+fIg5xpGEXmPi8iKBat0I8Y72kvq90twZK9VYv6Ni65rhBkWQxHzh217zd0T3vRgh6/UEmA3UiFCov6eyT3fnBKwzUy0cVIaIFxtlWkZVUEttAG6XqIjMjfAagbQ/gzrnjHeXT3I3IdiPtY8GLdE/y8eOPXh8jTnxz+eoy,iv:7FIS0rEH6UQUP5aeRzGywwYxq7FXchs7GHJ/ovBZV/I=,tag:7JaA2O8p4TYPZ6ShtROJmw==,type:str]
        version: ENC[AES256_GCM,data:Sw==,iv:Gzlh8NfOMW7lB1Ju+i1fRKK1pKmQKGrR4pJ5J0YwtB4=,tag:7Vg7gz8Rfga/cF6o80sxIw==,type:str]
        deviceUuid: ENC[AES256_GCM,data:E4+CszMGu9+6+0VX+JI3ctQifXm6CJDHDGA=,iv:LI63cGlgpZTFOfkXMmncpFvQCljfxEQdU14O49cBBMQ=,tag:rSyMPp39pTwfRUvHPlRCOA==,type:str]
        uniqueKey:
            alg: ENC[AES256_GCM,data:mGMdVxoncQ==,iv:AItLRQ4aIett3Ezuvz15AnbPLcw79DOP9p0dKtAErqs=,tag:0RvMpSuo+DcGnasKAmC8eQ==,type:str]
            ext: ENC[AES256_GCM,data:WVo/YQ==,iv:0G+VYe2NQocv5i10pYYNk+4j8eYV1sEDqxNjk8TDpwQ=,tag:2oPHLqxxIkYfIQBVoref/w==,type:bool]
            k: ENC[AES256_GCM,data:p2FALDVBTVrYqDRrbGQ0XcwOQM8tlCekM3TmlUq9clxCJEmtCPvlKAzb0Q==,iv:JStxzjfrpjTEFQy7JB6zBCl5g/FX3f3IeTXgEbQ0olY=,tag:YzmL+pvgUKxZyUSl1jsOuA==,type:str]
            key_ops:
                - ENC[AES256_GCM,data:7KJbmylkBw==,iv:9PyfuwrjBVNo6AyZLoofLrBWQkiYvRNWejsFMZET3T0=,tag:wFZs3Xh2SN1msBVn6Z1hMg==,type:str]
                - ENC[AES256_GCM,data:8oHJjpYgDA==,iv:Khnc1CSByauElenqohZiQhkVmb/18CD0nbw+IYUjgvU=,tag:OZSzeAsHFgw+pdZcvmoSTw==,type:str]
            kty: ENC[AES256_GCM,data:Wht0,iv:36xofbIFRRBcr5i1fD3JpihvyrnQP3B98it5pH05Cko=,tag:W5hWuWPRwNad42mM2acjWg==,type:str]
            kid: ENC[AES256_GCM,data:9yU9Oh7GzreVJ9fQCVC2UqshoYjeMgxx/ns=,iv:7zrzjXxin6ex96heTQbWVk75tR58smeEp9ELoKCyuk4=,tag:Z2HJuRxxeQGeNPeABggIjA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-03-21T16:09:43Z"
    mac: ENC[AES256_GCM,data:ZfErNWcG5g+fJDy2GPVyRs3DVzEGXaBh2Zz6gpcu2veFRPKuyazzgbmvGtSc+9Aa4j5LJB20D3i31aQewKFBC2A1uKOXRs9U5xhLMxIthtSEzkd2t3Lyb2mon6Z0RtkH0njs8q4Ual0MWONgGlHET+Oqch9APvHj+LMT0b+W1Hk=,iv:nMhCLqhpYyycYthEGl6Pe+ICwzSiu9r8/H1r7YGGnzI=,tag:AiyJWJKaRqbhKA7TpPqfqw==,type:str]
    pgp:
        - created_at: "2024-10-04T17:24:51Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0dSZMvnEisuARAAk0kI6s9F59CKPBK/ksM5HrCWn3kVmuuUQav9E6nBfwzH
            V+pqSIuzCtPEDF+Pig6mIad15KXXks8QOvoJde1jwkQ9yqTIWU8GkYLvS4GtiZty
            4Xz/dZUNJrUzYoQCmSoqA0UE0pAalyQcnTZM6MadXB4Gd2ceXvDkNUGkaocSJ7wM
            RY0QvklLE4m4vxks61ZUfdXR04RIrC7US5k3Whew0ks8iGqwwcoYW2ASEle4gfzo
            95pSFKKxwRekhJXRPiKYhmAb1N7N3/zrTypRAWqP70gopzDrExaj7TeyRaG68o8k
            L1X56r6TImUfU+hdPCQhOTbAvswqJyiIB9fjHsZxhYYV2jjVQlb9AUaxalq6LuJv
            L13bWHvcqc6/YUKUdoOak9MvLekZVCLAFrqeDUL8ekhE1AAnMBwpAc5tkt33z3+z
            MYUp86uvUL0pt1QvzCH2o512e0ekLlZRNN6gqOnsBXVObaV4uDBG1/RUsczwv3O7
            NX6BCxds5xa9B3JDTrJ+uRKPnnSUJlkx+Q26T4fVcRLGDk9I6GQUYLg2MAavRxAb
            XmdN2XuS8IgFwy6EFlUB2Hgwo6vRbFFl2kmsnYBw4ks97W/OLNatOLKLDtOKdh26
            aKmfHksMaYl+XIsVZEc3siTCgcMmBaaMa22sJ+2t+6oF9qQEInNXTr4lzhufYVHS
            XAFlZiE/3cTp6cdWkylk/GqJ1krqALLRlNKXPI3oQGOOlS2JzuU/Re5kGpij4B+w
            uZLIWKRCplnn+4g+N5N1OB7Ijq1vz4zvC9TznXY3rqVoSFi7Q+vt5dKU3X8y
            =zBL+
            -----END PGP MESSAGE-----
          fp: 1DBC3ACFDB8B1DF2C44CDA23996024D3718273FA
        - created_at: "2024-10-04T17:24:51Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxbwxdi5IniFAQ//ZH3w+K1dAGY0IS8nmujF9WlUJpfmRfNhFOXJCSWqV35o
            24jyBIYpmXEU1CF9TaIYnZLnaCjN8RX4N8n+GnQl+6GnSlhNRED1PHWoE8KnmKRe
            wEaviaUEJoHjH6G8I7zX8NoG4hSap84tDy8nhXMu/xwevsGAMmxC1oaT3QHbxSGJ
            Xl0+6xps3LxRQ9i2NC+3vpgGEmvLvTFLlzwULQV/qX/Q3uH4OqBCpJrOUqZQwA2Y
            O1waeyjtvz4WGsiyc/Q7Wi9M7vVEFuzfXD5xLAAKmV/AMZRQt7nIsVo6Z3M3HLWu
            ci0RH5q3hi9uuyUSLOmKKOEL1NCPW+bCP2jL7CdNShS0/UdU+Nc2pS9mlYjAv70G
            o2i4FuiK/pX4lv2EU8r9B8nkh7fIXuv+EyFMMZHfyj4tNiMYcCXh8F7qgTLUjN40
            4ObAwPuJOvMATZDbsOmkzAowBzdvNlYv+PGd3J+1AM2Av2SGsMf21Tw8Hrs7QBgr
            mmzg4xCIic+opu8u21C1mXu16I2Znge+psB6DkJlvDUfz10VZDp8NAlRFNht5pEW
            7Xssg74ICmqodIKSgaEjKucg00F5R9NE4JcISBAJPVHACcZ93+mlTc2S1QlFcgYw
            gD48KB50mdjsCYuc0iyd8xtMvQECtWqolyB3z0dbIrnK3gSv6/QM+cZlDNo+2kDS
            XAHkHqONnnobxg3Lymy/IS7Sy776zA+OoqsrnjZgwqf6FVOoTh7U0esOhqd+RorC
            obWosVa0v82vp25jgrOhMwxcn+jumt3URhpZzpDyj/fGk9XLq6qB867g6BaD
            =x6xx
            -----END PGP MESSAGE-----
          fp: D9F3AF2D9762D61A974DCD3E7B318B162A7DEBC9
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
