# json must be base64 encoded,
# even in stringData
apiVersion: v1
kind: Secret
metadata:
    name: op-credentials
    namespace: 1password
data:
    1password-credentials.json: ENC[AES256_GCM,data:NCmUGNkxcMmhOa5gNW7iDRoglocd7yKJdoKHhqorR+6+G1tnhuOAFjJPUX+d6MU7j+2+loBd0nedxGUywnTO1zwfggBdzg4Fd041tcvGe19e9riFnBlSumzuPJI/k7Y+bQhUOkNF1sTuD2wJVHfKxuYzmOScCkBsgoV/PJ4syGfVfvbGL4OQ92IdZYeOUcmAc7MJSDjyKGqz8UaE1a9B2AdvgXgsuypTU0iMspFJ6z5mjDhNJddRwq1yc5GYQmytx6AJuZmDz4zdB9aMCin4AQ7I1A+QIJClzKHmOdpq09+5rsSFzbrCGwUchjrn9cfhmkO39qqj4Jwma+xcNx4dw3HAaZWYgXr+FJeTyCBDrN5MaBBytBMFEVCKgu9d78LZcJz9YuUrOkyxlEpa/Xqzqk8ZzsNECAXsgDqZrn1/HgIEmX6r6TvKUagJKj8pJ58SmTVzVAURaohKmuetJgcuXMwRi3SLS2UWqP2UFZfsnYTKuQtyqIpRshe5kvGV3thQTEin1n/9ijVLBB9H210MBi+PWfcttELlDhebELxBSxQa4EOvecTnGyn4o6fjjVHIa/hBcgtturpDigdAxeUyca+hps/AODbuwhhaQ/z3U8EQK1T6HRvZCVxlnxm1bkzHxNrOIfQwfwu47DNk7DPokZQJPw4GneE3Hh63nF4Ue4eZVmRzn8nLgyi4Gcl5AX68aU6Ps0sLVRqU0+23BKs+S/bqr9PAiRvGFV2QmzZq/ZqvSIvdN7KtG1pu+NOaV4byyYLVPrSs34vIWjDjnMVnLLTdjdgNd3yyO7HYodhwPra8w+JAfsJsQhg94grb+RKH0Ef5GvbKvJahFPU8I618bsH4WEm+6Sa4CtPPLIOsuQGuYJna0G86HU9aLYiP7p9M/4PTlJZeINOZp9NnaRk2sVsMzJoZdQ3z/y71gExjOI+Oq8x7xhhB4JLGqB1uPC4MiVJtImNTKt0BlSSW/jx2rtiKt64wFKy31/5yNTsgolVzvAworbrQCZAvwfyqj8+l5bqDNbQixAv7gSLKg7F7PnklwfqRn+NKOzbcGcK+83oqtG6uaoZ5+OV8zM00PhRbpjSIEFw/hUHe3/K2ZssptPZlccgwcuXQCSFlYNfAqnh4AR128HZ87DHBIxcINffADNPT53febyMjBtAiwgAEG45qrZC02tXyNHq4lM6qZWw+rlHzPmFZ5SJB+WXb/fa8rFezw25C2/v/OyXFdmPqHh5JnNKQqRBzNCKTuYtz/COKiz0elIYoBEiN1jA6F8DKiMO1FIw5pIUfdXkddRU76cRQHECTmOk5OyebBkLx1yinz9xurHkWU+lpeWyn0T4Y+/zri1sOLltA9ncKoQmYkU6DwX71i+O6fR8tDwaz9CcboElxo3HyGXdSqCX82wdAl8Ht1vuWr/RUGaPNQsaJovFCRZ8vlhDhLXMY8Q5xZl75jKEUoJ/3n1pDcTjkCgwLMSy0S68iz6Hj6G4qDYhx7mdC0gNmwkHton0JMkacULTW/bIetK7tYOTs+ABunCBFka1gaKAFg5O7tz8nhQmAS8VyrAOcdFz+x2kRCmgZZD4rP84UMfzuR/ntQ/jBeGLhNPbO6W3Kou+ZZ32Z5AbOcpWCgDxauIWRXQdE4GSvV31JSUonhD7kWdy90NI3I6bt1/wKgVIuAH8wA2c1stT1OAmSRw2iXOxuCRVnbby1ZUyH1ufKJ1qE5lyWuS5WA1M32K+Ex+b40jP1LjnEJQermb948jdHm7CQhhJJPGUZzN5HIMVdg2hekGJuZZiYnQdgQW0Xsxs0H1Wp2vRseSOEnmbXtQVMmhoGofpbNdBt6LcMeUPjnVj8kcA0NF1eCeS6Ktl1ZctuaonMEV/j4nKgKQy5cJrrHU7KyASzMIUyc9z4mI35LIza6EoehcybsuyVjGRe8OWZmrxhvuKn,iv:fGGntW1Caa5Yk9ahYbxaIQzgRaaw+ez5pXRgEd/F+8E=,tag:nj6eoztvYZZ0zraznm6tLQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-03-21T16:13:45Z"
    mac: ENC[AES256_GCM,data:KjCBEibNo9XNO2xQsrYthIjsqh7HMGK8SzSGgm2B2YQXmc5AYijzfdhqhN6efEnq+6LJ1N5cmFO5V0kicZE6WGpoFieD4WZO0KhibQY+QNSThqKidNtisY3Dns4AFF+YzC8xE4scm1XMn+vZOGGV4up81iXtLrrG0ndBaEKKKUQ=,iv:wb4tD9BN6a2tB/TYBqbCRmxeYS5XAPLXHiSxMaJbgzs=,tag:omAWKwTx8bv/ajTqBbjkPg==,type:str]
    pgp:
        - created_at: "2024-10-04T17:24:51Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0dSZMvnEisuARAAk0kI6s9F59CKPBK/ksM5HrCWn3kVmuuUQav9E6nBfwzH
            V+pqSIuzCtPEDF+Pig6mIad15KXXks8QOvoJde1jwkQ9yqTIWU8GkYLvS4GtiZty
            4Xz/dZUNJrUzYoQCmSoqA0UE0pAalyQcnTZM6MadXB4Gd2ceXvDkNUGkaocSJ7wM
            RY0QvklLE4m4vxks61ZUfdXR04RIrC7US5k3Whew0ks8iGqwwcoYW2ASEle4gfzo
            95pSFKKxwRekhJXRPiKYhmAb1N7N3/zrTypRAWqP70gopzDrExaj7TeyRaG68o8k
            L1X56r6TImUfU+hdPCQhOTbAvswqJyiIB9fjHsZxhYYV2jjVQlb9AUaxalq6LuJv
            L13bWHvcqc6/YUKUdoOak9MvLekZVCLAFrqeDUL8ekhE1AAnMBwpAc5tkt33z3+z
            MYUp86uvUL0pt1QvzCH2o512e0ekLlZRNN6gqOnsBXVObaV4uDBG1/RUsczwv3O7
            NX6BCxds5xa9B3JDTrJ+uRKPnnSUJlkx+Q26T4fVcRLGDk9I6GQUYLg2MAavRxAb
            XmdN2XuS8IgFwy6EFlUB2Hgwo6vRbFFl2kmsnYBw4ks97W/OLNatOLKLDtOKdh26
            aKmfHksMaYl+XIsVZEc3siTCgcMmBaaMa22sJ+2t+6oF9qQEInNXTr4lzhufYVHS
            XAFlZiE/3cTp6cdWkylk/GqJ1krqALLRlNKXPI3oQGOOlS2JzuU/Re5kGpij4B+w
            uZLIWKRCplnn+4g+N5N1OB7Ijq1vz4zvC9TznXY3rqVoSFi7Q+vt5dKU3X8y
            =zBL+
            -----END PGP MESSAGE-----
          fp: 1DBC3ACFDB8B1DF2C44CDA23996024D3718273FA
        - created_at: "2024-10-04T17:24:51Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxbwxdi5IniFAQ//ZH3w+K1dAGY0IS8nmujF9WlUJpfmRfNhFOXJCSWqV35o
            24jyBIYpmXEU1CF9TaIYnZLnaCjN8RX4N8n+GnQl+6GnSlhNRED1PHWoE8KnmKRe
            wEaviaUEJoHjH6G8I7zX8NoG4hSap84tDy8nhXMu/xwevsGAMmxC1oaT3QHbxSGJ
            Xl0+6xps3LxRQ9i2NC+3vpgGEmvLvTFLlzwULQV/qX/Q3uH4OqBCpJrOUqZQwA2Y
            O1waeyjtvz4WGsiyc/Q7Wi9M7vVEFuzfXD5xLAAKmV/AMZRQt7nIsVo6Z3M3HLWu
            ci0RH5q3hi9uuyUSLOmKKOEL1NCPW+bCP2jL7CdNShS0/UdU+Nc2pS9mlYjAv70G
            o2i4FuiK/pX4lv2EU8r9B8nkh7fIXuv+EyFMMZHfyj4tNiMYcCXh8F7qgTLUjN40
            4ObAwPuJOvMATZDbsOmkzAowBzdvNlYv+PGd3J+1AM2Av2SGsMf21Tw8Hrs7QBgr
            mmzg4xCIic+opu8u21C1mXu16I2Znge+psB6DkJlvDUfz10VZDp8NAlRFNht5pEW
            7Xssg74ICmqodIKSgaEjKucg00F5R9NE4JcISBAJPVHACcZ93+mlTc2S1QlFcgYw
            gD48KB50mdjsCYuc0iyd8xtMvQECtWqolyB3z0dbIrnK3gSv6/QM+cZlDNo+2kDS
            XAHkHqONnnobxg3Lymy/IS7Sy776zA+OoqsrnjZgwqf6FVOoTh7U0esOhqd+RorC
            obWosVa0v82vp25jgrOhMwxcn+jumt3URhpZzpDyj/fGk9XLq6qB867g6BaD
            =x6xx
            -----END PGP MESSAGE-----
          fp: D9F3AF2D9762D61A974DCD3E7B318B162A7DEBC9
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
