---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.2.0/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless-redis
  namespace: paperless
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.2.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      redis:
        containers:
          redis:
            image:
              repository: public.ecr.aws/docker/library/redis
              tag: 8.2.1
            resources:
              requests:
                cpu: 5m
                memory: 32M
              limits:
                memory: 32M

    service:
      redis:
        controller: redis
        ports:
          http:
            enabled: false
            port: 80
          redis:
            enabled: true
            port: 6379