---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless-redis
  namespace: paperless
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      redis:
        containers:
          redis:
            image:
              repository: public.ecr.aws/docker/library/redis
              tag: 7.4.0
            resources:
              requests:
                cpu: 5m
                memory: 32M
              limits:
                memory: 32M

    service:
      redis:
        controller: redis
        ports:
          http:
            enabled: false
          redis:
            enabled: true
            port: 6379