---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: searxng
resources:
  - ./helm-release.yaml
configMapGenerator:
  - name: searxng-configmap
    files:
      - settings.yml=./resources/settings.yaml
