apiVersion: v1
kind: Secret
metadata:
    name: searxng-helm-values
    namespace: searxng
stringData:
    searxng:
        config:
            use_default_settings: ENC[AES256_GCM,data:VSt4Zw==,iv:O0hsQF9D6YloCM5TMfLrEQwA2FkzohP/9RgvV5Zzfog=,tag:FER+/V2mxZ9MgmqgdcSPGw==,type:bool]
            server:
                base_url: ENC[AES256_GCM,data:L2nebA/5BuL9P+8F5q+AhwRoscgHP3PgMl0Pkn3USgM=,iv:mOllSReCDWk0ASL+puYMXpaV0odl7n628Gzp9Vz3ZlI=,tag:Up+zuDqnIdy2QsK9ZeHwIg==,type:str]
                image_proxy: ENC[AES256_GCM,data:+ymrdw==,iv:uaRTGVh2cnUh14AtYXX2WZNGBAVBgBSg2089TWM5yio=,tag:g7Ow9JCVsj0Nx/PCYns5WQ==,type:bool]
                http_protocol_version: ENC[AES256_GCM,data:Vrrv,iv:jUOY7A//VSwQUM81JPcrihgDpMv+km3soyCPMdlREgo=,tag:xIJMdXiggzUl9pHpt2He4w==,type:str]
                method: ENC[AES256_GCM,data:1xI+,iv:egTRl0zJKiT3wRPR9BKy4dXzrIVcoBMiD1mHAVS5H68=,tag:NH9JvBz30in0C5994wsqMQ==,type:str]
                secret_key: ENC[AES256_GCM,data:u2sHStAMIzDvrWlp+IWhxmSjQkGQ5vL0JhXFXsDg94TcOtMepdSKb8z15vi0bFe8Ef9M3TLjsNiIY+IQFhA2WQ==,iv:l/Vc8TPuLK71VvHQ5lAYbDqB5+2g1PW4/FXmuTCDngU=,tag:3v5PXWAlZK/vPgzu+ok8JQ==,type:str]
            search:
                safe_search: ENC[AES256_GCM,data:qw==,iv:ChMHDvxYdoIFKZJGW9KH1FpiH5Gs1BnGuhxe4hk8oRA=,tag:zF56Y6IgSl3FpyLd6sABeQ==,type:int]
                autocomplete: ENC[AES256_GCM,data:813vWezeUYVNKQ==,iv:hpcaS3LLNMqTT+REsIkhlRk494Pn9D6K+XhT4PIvInk=,tag:66r7U1BASJukNi6xALNmJQ==,type:str]
                autocomplete_min: ENC[AES256_GCM,data:fA==,iv:eOCyAP26AVWmqC52bmU5QVGkHixElsFf0rtGA40p41Q=,tag:+K9w79zD07br6bDsVJIQpA==,type:int]
                default_lang: ENC[AES256_GCM,data:YOw2,iv:VlqOXm38l1NuHbiUm9vKzYrscnnW9oCnPUdjAmBSN1I=,tag:LRw6JiFZvMTMTXilyJL1Pg==,type:str]
                max_page: ENC[AES256_GCM,data:HA==,iv:NrCQLZuZbUBZca9jey5mVqVmtRxb6sVm1fE8L7U+hcc=,tag:N6u0UPeNYg4ZMndFue1ETA==,type:int]
                formats:
                    - ENC[AES256_GCM,data:jzB6Bg==,iv:BnACJLUiWzRxTkc5epXwMhpDwFLiHQXGUh6NECzK13I=,tag:6FVj5m2x7tbfeW0MGB4JyQ==,type:str]
                    - ENC[AES256_GCM,data:tn+I4w==,iv:Duu7+R8vvVe/4PrEkYtxGg1z46VU6WF9fyVg8shjRPU=,tag:DRzUqUS5hhVlcNgu5sN8fg==,type:str]
# ui:
#     static_use_hash: true
#     infinite_scroll: true
#     query_in_title: true
#     default_theme: simple
#     theme_args:
#         simple_style: dark
# enabled_plugins:
#     - Hash plugin
#     - Search on category select
#     - Self Information
#     - Tracker URL remover
#     - Open Access DOI rewrite
#     - Vim-like hotkeys
sops:
#ENC[AES256_GCM,data:RIwJxsWBGQyQ,iv:VoaFZwRRvVMBo38iXMnML7B4OhlGEoV3vUvFZzfuevw=,tag:Nu4o2Bv9ohog45fvRhLX9A==,type:comment]
#ENC[AES256_GCM,data:7Fa5vwWSCSsLl7kpC6k4,iv:+JLLgfxl/QIkOru5aQH5BNeKbB4bhgI7LAi/W3OIH70=,tag:OQdOCgK7n/W3gqLEa+QL2Q==,type:comment]
#ENC[AES256_GCM,data:suqfzWsLM8G8ShuILhgRcFnNcOvc+oMoOoo=,iv:gpmddxKzKemZxS1p5fBMtZe87WZ6/sMqDh8xjqpkjQE=,tag:yuQfAmsddFHTuDWxyFQo6A==,type:comment]
#ENC[AES256_GCM,data:9xtd6doudyJs3pmcCSI+DKo=,iv:LaWcRFVHXVlMj2SmfvTLDCB22bb+y0SbopHrk11IoUg=,tag:Wn6t4DWk1kBVsM6ELekh/w==,type:comment]
#ENC[AES256_GCM,data:H46wsMy5puMFEXyeypRjquN5Bbh9CoUg,iv:sJYfp0u+27/q00O8mGcL1KXXWLiNJ7/67kfi1le8BeY=,tag:RS9/jWHIGbqzKZop24wTCg==,type:comment]
#ENC[AES256_GCM,data:YPVgJ3BWv/uw/B8GpQycnMSVxpRYAw==,iv:LnFyabO+bT6erwteK4ieauathCj4l90N/4R++Hb2QWU=,tag:jbFaGHZ2mwwIHMEXu9FlQA==,type:comment]
#ENC[AES256_GCM,data:ZDT0TVOQj39XIhndqEGdEJoQUrVMylwZ,iv:Jt/5aTAAJM0bo7W8ukAcDV7BvELwIP2DHIEPKZ/NjAs=,tag:NGPcjSZm4fo4u4JjLgunFA==,type:comment]
#ENC[AES256_GCM,data:FVpNU6/yz4uuEQOABL+kv18b9Jl3Ab/0Rw==,iv:8ZrOxNBlqys6pInFU55y64PCExK3izAN6N3QziXTizk=,tag:YAGRRtxl3sNrXpxW7KKpsg==,type:comment]
#ENC[AES256_GCM,data:g8lY2wVB4E4297uAm7d2nZTinwOXCma1+Fhs,iv:F7CE4ZwrxCPbEK+ev/EH+p7ZBRqyNTH+Ff0DQf7Za90=,tag:NdUY499AMOJJpIjXll5E0w==,type:comment]
#ENC[AES256_GCM,data:I4JnIPXWGepaO16+u+Qk2qz4PSEn,iv:e2ShzaMkv+8JekqcFJhnYTKOaE8sBojXsWBBsPsDUIA=,tag:sINnrRs4ZS9QC2ZRlyANzQ==,type:comment]
#ENC[AES256_GCM,data:WYN6Lgl9sBVZjZzqKTQlzQ==,iv:pdJafyc3Ab6L/bcaq/UBbZqGWIXNS9Fa0oc6IL7UCVc=,tag:7oZmTvRVNeePUhAI4po1Nw==,type:comment]
#ENC[AES256_GCM,data:y9N7OfFjSJmnt9wqJGx+l3GVutA=,iv:EJc1f+yOCnX7zm6UTkM4TlCKTwC5zzB/kIsDCfnknEY=,tag:N+it+FEdISN9yWvU95GtWw==,type:comment]
#ENC[AES256_GCM,data:lNgBjo5RBHwBxRE9CLI6zW4=,iv:Qw6fJe3K8QGRgDCGcxC7ao7kkZg0F6SCVmB8XatshDM=,tag:8DfX2nZzjhYIs1YNI6W5Rg==,type:comment]
#ENC[AES256_GCM,data:VgWE0HbkjFqpk70w+vKyNZs=,iv:JHu1LW4HYSmvGXQtduTx1zL34tlH+HvIfpumjRTIp3E=,tag:dOadoF/8vsW35VxWO7WZLQ==,type:comment]
#ENC[AES256_GCM,data:cKVr46/7dYOXMGSmUYF0bm1HpA==,iv:dcL5QLKpBwJlAN9uVn6oy/YIcPP3wgHY5FvIL+W1plw=,tag:kDviXknCemQQdpJaMGwckQ==,type:comment]
#ENC[AES256_GCM,data:lAtK0rIw/gEo2njNAQ2p0dyql0c=,iv:9oy/31Z0UTMFuQ/is7bzrUydVVnbodd1gJccFFT9q54=,tag:XCvSjMG94PBDs5+x8uM1bA==,type:comment]
#ENC[AES256_GCM,data:M6e8xD3AO4BYGDmr/9DUblSRHTY=,iv:fvR3XFAxyX3yO1sUdcg8qMrrKF2PrEfFK/w+PBLEzio=,tag:U8wAlkaETIhNmASJViUFpQ==,type:comment]
#ENC[AES256_GCM,data:JALaMbt/QgmxXwQbs+ex8Um2YM7CGd6dH6o=,iv:tJMCVEJmdNXXHkj3pxg7ohz7GxICRV1g1B5dhG1be6U=,tag:hfLjSwElcg6SluX1nye5qQ==,type:comment]
#ENC[AES256_GCM,data:i7BgP3aaZWURYVyraCPWIDeVoF4=,iv:NL2O26gQCnYFPRaKkfUH2IoJIgDr6gSWu7awHdyWGYQ=,tag:f6PdvXi8rvrhMixnXrdtDA==,type:comment]
#ENC[AES256_GCM,data:VjHY8gUopVnnw8a8Y1/9OJWONg==,iv:Rj0nkJrCi5wVee+7nklFq5GjJimnCrMp6SO3zZnKTWw=,tag:O8b9ifsogogXTHGZZaIdEg==,type:comment]
#ENC[AES256_GCM,data:hi3U4s4CAkQV7bUOSAvnVZNl6lSJ,iv:qLPUg2pXX8J8DctTpefhXw+OAUwu5jQHt3nQ9hZdn28=,tag:2RYHdj7CftODlSaG2jrOjA==,type:comment]
#ENC[AES256_GCM,data:/CG3YupuMu2uKyXlbXafFlYOlkppFp91v/w=,iv:MITiIqi4GdKnlme42dZuOKUFlqOno+4rHOTkWUW///o=,tag:ShSOn0l12Yn9fa1DDJmNsQ==,type:comment]
#ENC[AES256_GCM,data:MR8ga0pg1oN0eXxCaqXr33Bfw2Hg0IKmE7O1Yg==,iv:Hiqmp8glrHSrPyci60c71JhoF+goFKS1i/26V3R7ANI=,tag:kZd5zjrP/YiA48gbog7JDg==,type:comment]
#ENC[AES256_GCM,data:3uDu8jfTWCKnepqaCguiPOQ86A==,iv:wFzu4UxzXBCGGgorqv+iDT5+A9qew0Hc4jOTXXoTDSU=,tag:5McRq7+qaC51IRN3ePC8tA==,type:comment]
#ENC[AES256_GCM,data:guiTXy3as86r0IEpDwW9INJDS51C,iv:O+S76O9M6MQIGZ0sv+k/bW/zaKH4FxRGxZa0cEsGuVI=,tag:+UJD36o2cFXSZf89xLSRgQ==,type:comment]
#ENC[AES256_GCM,data:jTyjy1wmL0BftuMZiq3D+PQ=,iv:QA6pNslhQle0GnE9FiIYN7WNMIEt9n++tgf824HMVA4=,tag:fbBxpIUDqLwj8I2L5u5/CA==,type:comment]
#ENC[AES256_GCM,data:dmlb+MT8oO2rGkqoo+9aBASg1K9r,iv:KywVWhq6sng02pmSpDfTPVsym/o3sSItOfiRRMa+nPE=,tag:e57S2zN4Pf4pm4CuSka84A==,type:comment]
#ENC[AES256_GCM,data:3+J6/bnSnQDpVP7a+g8UYhU=,iv:Ochv10RQxe/KAJo/9ps55DVCqZ4aMNlpGPV5zsajqk4=,tag:Q3AHaQ6ErkJqA5KkAd8Ldw==,type:comment]
#ENC[AES256_GCM,data:9DPkspPj0r4w8sB6JNkYS+8=,iv:qu8ciOMQRL1Tk4Bh1aBnvbE/nAAbzmk72awVMBm5CPw=,tag:pKvcCu2ZK7uMhC2oqrKsuA==,type:comment]
#ENC[AES256_GCM,data:7maf+U3QXXBCj6YNQGZC8F5hkZ+zu7N1Y+wfYO0DAOCfRA==,iv:hUZK5PkCYuqQFli9tso1Bc/h+vaaA5VwPhRM1mpBJ6c=,tag:v1hAEmgfKsKDd/vtIJQRqA==,type:comment]
#ENC[AES256_GCM,data:DJm2lmbnBfgJedwSXj+IcdHUgXQ=,iv:FIH3YWCcf3stev9o9V4a1gQBVK8zU37j2SXvcEKJCYc=,tag:6bz0bP37n4hNC3Z0+E4yDQ==,type:comment]
#ENC[AES256_GCM,data:UnUb3HhN2PgZDBjk2BxIMKrCudU=,iv:poIEkQiiMBZ4+CdRlfl8hWOwsR3sPt2TDwXcqh53o6I=,tag:M0OofquWlIAOQ9Mxl6ZQeQ==,type:comment]
#ENC[AES256_GCM,data:vUJJV7nFpAoYkIWnJ4tnpcztzeBN0kmQ,iv:NUkNz/9XtCIfyByz1ixT40liFGBGRNKIwqdvY59lvQ4=,tag:PjIiYdxQ70erRRcVjhFy9Q==,type:comment]
#ENC[AES256_GCM,data:rlyGRgHuP39kmT7fmvk=,iv:JoTvvbe/iXEuGwry4zcG+pKi79YdkXKH8MFEUhIcVSE=,tag:4Yx+nK9/vVXZbBpNa/PvYQ==,type:comment]
#ENC[AES256_GCM,data:JA0K+QxKhhjwbLq/wNA/,iv:qOUIl80KKky7Jk3pOyWNUuGFj/7Jlbb+DA8N/0RQuQE=,tag:IfyU/yajLfRrE17qJbg1vg==,type:comment]
#ENC[AES256_GCM,data:/21xJffqvN/qxiq+c+QHApY=,iv:rJKUfqmvHdnSc0hUarLfgqS5q7LPe+ArN9vRtY8+ogM=,tag:cXLDMNncmhuoMWI936RtJw==,type:comment]
#ENC[AES256_GCM,data:SGN9sMGL2lRKix4tV/kt,iv:hXx3TZbBV/yvBuUoFjHi3jNfbAi/xgvhJWQKKKnLaJc=,tag:RUz9B0fCpIxqiEnVnLbXOw==,type:comment]
#ENC[AES256_GCM,data:mAgUkJbQ49F6TbFge5073ME=,iv:V7Drw3E2Co7Kpq3X+PDxjI5mGvOs6bOeG7G7oKNBdYY=,tag:pjVGNIH7erJRZqdkGdAz5A==,type:comment]
#ENC[AES256_GCM,data:M9ZlXDG5weJ+nZ1O6Y35GQPbNo13nQ==,iv:CflgtuJCmoQHKa/viz8neAtsDvEJ+tPZH15W3aAHzMo=,tag:JnSxX6BA52V0U5FJXqJmCg==,type:comment]
#ENC[AES256_GCM,data:+BodJaD9ZrH5aXxBIM85Y7kItSYL,iv:XVbSEwhWmDKKvGFPlzOGLdeKbZeCcv36hnLixrEdgwU=,tag:xCV8rEN92LG+QGBEBc4wpA==,type:comment]
#ENC[AES256_GCM,data:3X6oZJ60mrWcJ4mkBJc6ObBHMm73ZXx+,iv:1a0rQmWlw7Hi5QPLEhrmSFsPbn3TGZJHfpISyfPZ9zA=,tag:OKvk1f/z10/plGsA9+Ew1w==,type:comment]
#ENC[AES256_GCM,data:8oR9br8gdSLN6MZyzSM11Xgz7no=,iv:wD90RGN1/voZ2sf2/eNGFC3JA88Dgbp2BIieRceReFA=,tag:NlCllo86S57dUxFKrC7PSg==,type:comment]
#ENC[AES256_GCM,data:od2Rrfc7i7scgJ/VOn51KgWEpVs=,iv:apfV6L8A/Na2ispTXHynWB6TztvG5ofJgf58kEsurV8=,tag:yM0GPEXHYvV/eAN0uquNPQ==,type:comment]
#ENC[AES256_GCM,data:Ebari2BnXCb7iMpWlV7pYiNro/iIygb0kTw=,iv:fHgifzXUr7tMmW9APXGvQsUJVm45ROqpHrKkyoDTIAI=,tag:Vcj6D/X+xJw3TyKyC3y1oQ==,type:comment]
#ENC[AES256_GCM,data:f205f1zx8M89HjgfYdNw2kxs1w==,iv:hLFPb8n2hh+yYfCwhAzJpTwuGRQf6mZE/KtoWU8G8Sw=,tag:OnDWH2+vKfXfTdz9cCBrdQ==,type:comment]
#ENC[AES256_GCM,data:H0hwlFKKi6B9ee9gPBKS90FW,iv:Qg8wvWgffMtWKIz7i1Fm9jXpMjpfovkNxhibfIug9Fg=,tag:z1UOkGRGeqWCj2+gPseFrg==,type:comment]
#ENC[AES256_GCM,data:s3KvncEfrzB+Kqf85QwhnnYWWdCiTa8=,iv:CiRQXLfU6pIL1OTGSTW8aeB+9rb7+Ks9+co43bKbTq8=,tag:LcpVKvh6nTzsVzQXSAueSg==,type:comment]
#ENC[AES256_GCM,data:zBvXbnrBSCCRqlJtTJ4Wudo=,iv:vf1t/3X4ccISyfjQgM2GgIwxLPCECr7A6YaF5dhM1kE=,tag:EatGkmNjmAO4i70erOlZYg==,type:comment]
#ENC[AES256_GCM,data:9OszsP7Nzqpl,iv:b+HHr1CtJ+LYPhSbVDZAaePIfbfjYmHVn4mwtInZP3s=,tag:EvNMEhQmSqxFa6lonvqK0A==,type:comment]
#ENC[AES256_GCM,data:wV2eLwquWOd02WmVX1wE3CGR,iv:6z40y2jsBf9URkRrLV+nhbFICj+YAbb4INe+fqt0Y5I=,tag:1HL8pVOOElqkdAPNXlKE3A==,type:comment]
#ENC[AES256_GCM,data:VyWBveRji39EAQLTZwkZREsbdoGZjg==,iv:7BXjZFyUv7pGThdWDojA1p+Mk1tACamO9CEY0vfV5sU=,tag:7FFj6aEjqrk3vHAhwvFkgA==,type:comment]
#ENC[AES256_GCM,data:W6EWzWULHCuKJeZt8EFMOZcx1gja5A==,iv:bRA+L44oVDWV4oWOAe0ieVczSHi/ySPQIIBtI19OpXI=,tag:FFEUVW3QyZbXVttOqp/vNw==,type:comment]
#ENC[AES256_GCM,data:YReuy4W4m5IA5/LYI3QeQHDO+00ALw==,iv:N7c90oxItFh98GEFl5fSffn87TKl/Ua8PcUP9hG5ep4=,tag:cxCi6gXml9E9+hSm6ubLgQ==,type:comment]
#ENC[AES256_GCM,data:wLI6BLRjvuhd4jm2d43NPoG6sXVDoLoP5tchNg==,iv:OJhakUpxn9QiBhsLHXKvl9c07vO/T43rk10ycaLpZ0U=,tag:68zOrwt1J7kSj2/jF9XhGQ==,type:comment]
#ENC[AES256_GCM,data:ad3vpDMDGsLx+WTmf2iQLeJRlPfpPg==,iv:IM/UN8NkQGYpT+sX67qABpbkUlk+kFiIddt4cjHzqaw=,tag:4m1z5Kam1nj9iIH2rDqvtg==,type:comment]
#ENC[AES256_GCM,data:QgoSuXuq5YBzAce+pH6grngu6tgyJTCXqeBA1w==,iv:bXbarNgs2NWPeIHK/4UwoXGebDSEopyRu5egGQVe9jk=,tag:vp+GMP4HkVmgKmsiizVG/g==,type:comment]
#ENC[AES256_GCM,data:mvIEW+S4c5B5sRFBHMWKvXFnbzHzHw==,iv:+6vk0Q4v7+vNkA/rcXyYnNCB7LP1J06xqs8H5I7iOUU=,tag:3cMCwvJY3ZaIIKfvnYhRhw==,type:comment]
#ENC[AES256_GCM,data:oBFcltGeSa8/sI9jBP4OyDtdDg==,iv:jKOy0/r1oSQUK3QVqRkUWqrHWpvoKsWFwGFloLuOgHw=,tag:OCrexE8n2RqKBcmH4cendw==,type:comment]
#ENC[AES256_GCM,data:ER/v5n9b0deWuHq3YS7Ie/M5vtkBng==,iv:RpeN6tCA7h9tGwnVwJoAwhPsJiwB8cZseIiBPHnQSrQ=,tag:Dm6z3Z8RAhByK/nz5u5q9Q==,type:comment]
#ENC[AES256_GCM,data:8P2jcy9IS54aowkNxMLiJz2V5YeQ9KU=,iv:dWLISTd8WW1dmMCpbPEYziULWzeBB9nXonFCh4jl5g0=,tag:4ce+gPYsw6TtiRq1XcwFkQ==,type:comment]
#ENC[AES256_GCM,data:4lK/pSJiRSlkTE9q53izEh3PyMTTzA==,iv:j2CtiIcGAeY3DIGOCeSGgE1EdXufDlt+gaHlz5abScU=,tag:XsTZ3FbL7uudDjoEqXwqeQ==,type:comment]
#ENC[AES256_GCM,data:TUZAc26AcBAHxhtNgymCt0Z/umCumEqqISiXV/Jc,iv:m06Qet4TnvTYI0mW6B34SyNlJu6st4jErFUudujOoFk=,tag:M9U3oB+MYbl2/kfZC1ncRQ==,type:comment]
#ENC[AES256_GCM,data:V94eDYdyAGgrkjyzWijduk34KmR+Nw==,iv:5qF+5f47FKEKeZBuSOJ667jkfxZdIys5ETP2qhkw5K8=,tag:Mphr0iW1Dp/OW+780bI6Gw==,type:comment]
#ENC[AES256_GCM,data:Q1Ku6tfWB49tMFLT338hdEm84Q==,iv:zGvA8AT8s4mTPm+iKvAgbI343uP7zYINP5s5PGPsw5o=,tag:G+UYZoJxQwNj4WrVZR/d9A==,type:comment]
#ENC[AES256_GCM,data:7NvOvnnUj1JbCkcpxZTIdSwPNjb6uw==,iv:RinHPCdK6fQgaDzOhnrO/UnKBM7RUzGyIvSxrQD04Zk=,tag:wgZOaOfM7SHtgnZIE5hCdg==,type:comment]
#ENC[AES256_GCM,data:Zh97FEoPwyJfHYm1JL38hAr0Nyk+dBCSFulnpEKq6+uJc9h4,iv:Q65tRqkGDLWSXtaUhJ1OQE/sKC5H9Zwr0KUZwUnnv4Y=,tag:6klI8vmxP8lguRyIIPi8zw==,type:comment]
#ENC[AES256_GCM,data:7mChQNhllkuThIi/GOk2h8ZHw/tFQA==,iv:Vp+s32qqinLBe/eO/FBrOIjxAh9sEQ8dVBrkvp4yl/g=,tag:g8oxWorR1O5vJqY25OBNww==,type:comment]
#ENC[AES256_GCM,data:f3I0zfD/yLHOi7VAmFi9zLQDvBGF2A==,iv:eriqIoQvHWhQQTsB3zHTgWXddIFc3YMwl9UrZNlTSlE=,tag:3UvZd5GR/MKMCLp+wAoVEw==,type:comment]
#ENC[AES256_GCM,data:xsb3vapwao6I7dOvIrjeNXvsGLhxCQ==,iv:iKlra6C0YdwuJZ0dOcXKi+l5f2Cc8To13Rw3P67Sogo=,tag:EFTHdXe722riAW4bOPTZgQ==,type:comment]
#ENC[AES256_GCM,data:+eMAgDCvmoQ5S8Ak2ADe2YDoPw==,iv:Je3HS4BbYwYSq4X4n7iL6vDtsj4UW0gnGf6/FFSDpAY=,tag:U/lMVizizV+uxCGtq7ddPw==,type:comment]
#ENC[AES256_GCM,data:S/5DNX+cw1DJPh0fssb6aErbKU0bLw==,iv:iHwjqeHMep3Hj92213eVVV1yHT1DdEdZIDCR5llKIv8=,tag:Zy0v0OpwyvQJlPY04rjKqQ==,type:comment]
#ENC[AES256_GCM,data:B1e8HyxRmI6UgNWTT+MdQhtByGTT,iv:6ku1tcjTJ6GFZT+Lv3VRFbHjYELZkV14TeSiafJbWMw=,tag:dekNBXNtiSZ0eQv/pnC2vg==,type:comment]
#ENC[AES256_GCM,data:RQL9fq73F4bOD51RHsIXc1luFx1LRw==,iv:6zVfezyMnH7ldz0Vk7lqNA6uRQsE4Lcl4t49wCiRYhs=,tag:1xPi33ROL/liaXemGngIsg==,type:comment]
#ENC[AES256_GCM,data:FP6HCNHivrKX6bRDU+L3EilyF4Kw3LVDzVyhJRI=,iv:EE52+KZJ63zu4ZT4by3KIWCOMrNZc4TTOnYjr8EE3fQ=,tag:lATb6ylyWWwYUVcFrGIikQ==,type:comment]
#ENC[AES256_GCM,data:TW8VBpq6dNCyVIpg3aENEtyHhYuF0w==,iv:3Ua5j2GDhxq5BATRqoEkEEPY7OCQbNrE7HnhxBv5Oc8=,tag:neOjUxVEI/A475CMHOw7HQ==,type:comment]
#ENC[AES256_GCM,data:qIZBKu36/sYBdE9gl2knttwaqISpLw==,iv:ldR32qut7ei6DcLZWLoMXto0gGCFLdlOGfjYBMNl95g=,tag:JPev/HCbh5Lgiq5uzkcOgA==,type:comment]
#ENC[AES256_GCM,data:dnr26t4fG9zmsylCd6cSUxAK3jfvow==,iv:3kqIl8C17U1VOKbeTcSS8IDJSNUBZorM13WdQSlZ7HI=,tag:pPbREwBq+EkmqREL28i2Tw==,type:comment]
#ENC[AES256_GCM,data:C/HpS0Vy7GTyad/Z0AiarA==,iv:GkJcEV04rVitBs7LknCTLJgVsVk4xxkZW4CAdTum8ek=,tag:rzQUNZEe6xan4XwEH0Syog==,type:comment]
#ENC[AES256_GCM,data:klS3XtSgJXpNeDhe87gnmgqfwAkh3g==,iv:psxUGmvhnns3T5I584r814/Qw7J0fW8jKlyZFLCq6og=,tag:EiSRwM68od186upes7tW6Q==,type:comment]
#ENC[AES256_GCM,data:uUr6InML1tFC74cJ0LW7wbQ=,iv:lD7NZcyYZHoQYOuh9S8GKYSJ1Yc5xZbaVmaO4ZQHwEM=,tag:l72YnHeQrAbbNq32fl62XQ==,type:comment]
#ENC[AES256_GCM,data:qurNfs3VsLtl/5kH3opNlr1MZ/B0VQ==,iv:/kVWENrc+v9uKO5q+vgROmajWFJhN83MAtW5eOwU2CA=,tag:T1uzWHHPf6qVRCCS8KeDyw==,type:comment]
#ENC[AES256_GCM,data:0jUiwgVMY8Ohhwx3ws/HoTEyz+O5AcsxoQ==,iv:Uq0zolNIyBkVIxtUcmu7Da3b6eeST6/aYX5CIbF1OPI=,tag:EZmtO+MbOhcYSdEMr61ZGQ==,type:comment]
#ENC[AES256_GCM,data:e0CIkk7ELW3ajSztAC2bZVkBMgMYgwESDWuA0w==,iv:ky7H+XIFPWAyqfy4fSRAr9xgTqhDQVWXrJHx455C7fg=,tag:v3pS2m0iXZGF3ZbnKTKLjQ==,type:comment]
#ENC[AES256_GCM,data:QOZGjqLHheVv601aJ+84P4ls1tbvuQ==,iv:4DHLf3SH1iQe9Y6sXJ9iZtTs4dVNJSpNbTm8vv8ZYIM=,tag:Bq7AsaXKdkZp7nb20jjN9w==,type:comment]
#ENC[AES256_GCM,data:nxRaBSWwK+TKiAwjx76ls5Ba9Q==,iv:EfSsrDGsNm3IGLJQVSZmt9lMgrL7VstbQUj1QmTKbQM=,tag:olajqDxNP2vcujISGj53hg==,type:comment]
#ENC[AES256_GCM,data:9LyHgLSwtZd301TAHwvBsLtHIMzPcQ==,iv:9lpbR4ol7JSVzoo22q4m/JeBFLf2UAcoCyDs6e06gX8=,tag:0jqIKu97ptQIy/eKev7FGg==,type:comment]
#ENC[AES256_GCM,data:fFI03VGUYZK2KuWqIN/W2VxLsg==,iv:FHSifRbL0jaCaDVLFM/+hz24VMtfEh65AOnbelEJIho=,tag:YgiifRQiWKA3rp8P/S18oA==,type:comment]
#ENC[AES256_GCM,data:RSvDrRWdsOkw9+go/m8ZOrl1qk2f/w==,iv:CQ8TpMGRZwmDLlm56bhmUgizw0qwEwqDH0SkeSBeer8=,tag:smT9tIR+y7/W0DvRuAa7kQ==,type:comment]
#ENC[AES256_GCM,data:96WBSmJISXCooD8KcAUKIdJ7oFNeiA==,iv:b9Sg3n7RXwZxeixAS1SeFTt7/eFYFH0TvNkrVCzk+Bc=,tag:y8t59wfqIAZ1Kkm5zKNuKw==,type:comment]
#ENC[AES256_GCM,data:+ZCY+BNxqMwFw8f7xJ4K992u9fZeyQ==,iv:gru0oGBWPEXANdeNh+UR45DhQtTucrgqtGCBHzrqfb4=,tag:LfmcKYwlUFSunAWD8/J/cg==,type:comment]
#ENC[AES256_GCM,data:5MYJUSP7HiiN,iv:fERbsMFX03MARPUSp9nwDY23+gb2U5wMFlAKJ2TvWFE=,tag:wsLBHAMZ28MolDX3A1okDA==,type:comment]
#ENC[AES256_GCM,data:zh8b9WJiSFIuKp6S+JYh6ZbaMjIUGmt9PUgwtUspVEtk,iv:7LxHqrrvjJFexOTA7qHiNl6ojhcXixFzP+wocwEVbi0=,tag:lR5fp6PBM7dSecQ5gUlayQ==,type:comment]
#ENC[AES256_GCM,data:QjkS0jvdM4HcRNC9MRLSRJuvjEQ/nm+RqRHv78E=,iv:U3Z0GtSXYlYGG0PJ71oi//qVTODHx5mSwq1V1tHNl7w=,tag:2gFUPVfLyCdvFppu1QcXLw==,type:comment]
#ENC[AES256_GCM,data:2MDgvfSwUBvoZ7q8VNIfo5IUo5B8zV7s,iv:vuB9xV7r6w1f+0Mz9a69yHYUHHIS5MazAlnV2lpV4tY=,tag:eF57T6dau1xcunhfRX9TXQ==,type:comment]
#ENC[AES256_GCM,data:M3gLpl+fqdcyULYWyS4ZfDO10bwIvWc=,iv:m5o3vqGs8Dwrxiobawhog//uP+WFnPlk4YMUjfMzG6o=,tag:SPu/C1P4f19RQg4bSgKwXg==,type:comment]
#ENC[AES256_GCM,data:RDfidWYqoDqLcgr47ACZ7Qu0Dq7IUANmmiY=,iv:CNFRx2p2jSDZ/TK6QaXLMFfWyBJ8Y9+5pjAzRW8l4Ms=,tag:isV23jVvvi4oXDUcAyypBQ==,type:comment]
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-10-18T16:06:41Z"
    mac: ENC[AES256_GCM,data:VpRID25cP7i0Me6ogq6efWhcwRMJUj3yUkhGV/Y1MLPCXfdE+CI81tRP01X+EKbFWHtA26vf4vCdgsnu7W0ZfxcqPtkqr8srZMxCMtlvqbaz5Ym9E5Troown6kk1BCaUJsEwY3s+/ntFqxECTcDmE800V/DyTeSXH3YVrQ5egjQ=,iv:C8iLVubwC0fX12Xzo4qyMDn9K/Ojz7QtDXXNHgcPLkI=,tag:B+28RU9e5MUpAd6P4aTe2A==,type:str]
    pgp:
        - created_at: "2024-10-15T12:58:39Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0dSZMvnEisuAQ//UCIRpwhcfO/wRL3CJW5Z9Cu9fBuMQ4d9rwCgLv+2FAGT
            A7QkErv8P8D/BNBA8rm4gfoa3g4ogWtheaK5POHCDFSdHxAQvJGvygKZ2Jsno3AG
            teFJm1kiga0frb87vFSwV7tC30UkhTdxxVsdcXrGD1NzlNKJRHlLA3qqLcZ3HCky
            u1G9mJeNm0p9mXISlsk0zVSELVhXFvBhdKfavJAAFQQJhiX2ajGu70EpI4JuJRQs
            f5Bg0jLreq9LvJygBlQ6EUl/Hp4tjXXSDW9AkYNEvH1PHfuELRqZbz22py+Sbk9f
            948VwGJZUcprKxRmrb57swQuFlYjbQPWW9hRfNmW7tRiMXngAiW25UcddZip+oYO
            603i6+nzBKdWyhtEBG7YT+yUfwJWyw3Uue5aLBadZlVf/KSSow4+BwPdwta//+DT
            YYb5TCTLF/OimQPGd0hV2B72i06PlfCzH9zjlouO8J0PXixPErFC6/uBlSo+22Kk
            jQnLkjYBsprlrxLX/Uuu+KB47raKX9I5pD3r3OWjC7LxhKabseElaEiQtvBOqnpt
            qog6f7H0x5cos7OdibrIwbS0k/jmGaPIP/Ks1ddRryIi+tcjYput2PI/Ph9gYi+h
            wBJKAAEhiS/+KX9V3vCECAr8pVt0F3CwfGCpnZWYD51RAApUHGHQR8YiJPkZvtTS
            XAGiL++AEMVEGr6IDZixsz+h3KzMdNAIW0qT17Wr/8nWfteNj5SVCFTk6Vd5iY3l
            UUtQC4SAfTvrt0IA5ZgJix+IGNubhdO88KjVzCJ2oq/vMBE1HEI5cS0n0EHv
            =9vyZ
            -----END PGP MESSAGE-----
          fp: 1DBC3ACFDB8B1DF2C44CDA23996024D3718273FA
        - created_at: "2024-10-15T12:58:39Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxbwxdi5IniFARAAtaDjNNh/8NSv7N9bh5ES4w944c3lZOpaMC2nzKAqNySx
            y9jccFaexhtvJYCogcuSMT6yJTj/4N5kpEBNXLQC8jLga0n/k28X6WP5YJBXhD6S
            pIW/ws3VAwxwQwD5/A56+aIAJBarftCpoymks6coqObYe3DzQZusM77WBQt4tOsg
            899s8O8ACnLVtY7gmFdA+0+jzKNC0ajuZePrmU/3am+2yiCzvTohtbt74Y6FknDl
            TlhOK+r4SyKj2iq4JaHVD4SjGocbUvjN5rAB3dMv/Dx8fVuFQyrCnXOk6yq1niDO
            cnM+HlvQBJeNvbLZ4wgNklbr+m7d+HEDW5wVWLGnP2h32FJBfQP05wN15NStpl5O
            hVuDYABXVIrXDH6RKreONDLrP6ipTvKPHYqW5WknDf30JItkWe2AnCH85cPYPa5S
            eJ7y6MVY2vQ5rgD27qRQRmA0diA0lIKCaPD5PCV5BuEgCQiK5dsLC0KJdZv0qr9c
            dc1rwFlber76ZHEyGfmCMFHDR38d7iKn39eEQ74UGtpHXjRyn+i+/n84i/g49ih0
            FWn703eV8k78XQW8iELqr+5l2l+HGeEJikE7uqBoYkD8P+HYfXQFxupmZdKW7i78
            wOgfRMiiq+kUqkzZrrp0aF2XDUGK48y/KuZ2rin9AmRwDB5qHxJ90vZFon4DLCTS
            XAFJV/zP9T3BcLsLQ86vfmJ/Ey/b4r2FONJ18ezm3C0QLHsfTiwNkKnyg2uoOM2S
            yZwmc+O1CD/gzeiWPlN21WCkZshGONMfXobG+k5U+V4QBMyJfVmSZJc5Vy+u
            =EsFR
            -----END PGP MESSAGE-----
          fp: D9F3AF2D9762D61A974DCD3E7B318B162A7DEBC9
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
