---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.2.0/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: audiobookshelf
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      audiobookshelf:
        containers:
          audiobookshelf:
            image:
              repository: ghcr.io/advplyr/audiobookshelf
              tag: 2.29.0
            env:
              TZ: "America/New_York"
              AUDIOBOOKSHELF_UID: 2316
              AUDIOBOOKSHELF_GID: 2316

    service:
      audiobookshelf:
        controller: audiobookshelf
        ports:
          http:
            port: 80
    
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          hajimari.io/icon: "bookshelf"
          hajimari.io/enable: "true"
          hajimari.io/group: "media"
        hosts:
          - host: &host "audiobookshelf.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: audiobookshelf
        tls:
          - hosts:
              - *host
    
    persistence:
      # old-config:
      #   enabled: true
      #   existingClaim: longhorn-audiobookshelf-config-pvc
      # old-metadata:
      #   enabled: true
      #   existingClaim: longhorn-audiobookshelf-metadata-pvc
      config:
        enabled: true
        existingClaim: proxmox-csi-audiobookshelf-config-pvc
      metadata:
        enabled: true
        existingClaim: proxmox-csi-audiobookshelf-metadata-pvc
      # audiobooks:
      #   enabled: true
      #   existingClaim: nfs-audiobooks-pvc
      #   globalMounts:
      #     - path: /audiobooks
      #       readOnly: true
      audio:
        enabled: true
        existingClaim: nfs-abs-audio-pvc
        globalMounts:
          - path: /audio
            readOnly: true
      backups:
        enabled: true
        existingClaim: nfs-audiobookshelf-backups-pvc
        globalMounts:
          - path: /metadata/backups
            readOnly: false    
