---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: audiobookshelf
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/advplyr/audiobookshelf
              tag: 2.11.0
            env:
              TZ: "America/New_York"
              AUDIOBOOKSHELF_UID: 2316
              AUDIOBOOKSHELF_GID: 2316

    service:
      main:
        ports:
          http:
            port: 80
    
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          hajimari.io/icon: "bookshelf"
          hajimari.io/enable: "true"
          hajimari.io/group: "media"
        hosts:
          - host: &host "audiobookshelf.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
        tls:
          - hosts:
              - *host
    
    persistence:
      config:
        enabled: true
        existingClaim: longhorn-audiobookshelf-config-pvc
      metadata:
        enabled: true
        existingClaim: longhorn-audiobookshelf-metadata-pvc
      audiobooks:
        enabled: true
        existingClaim: nfs-nebula-audiobooks-pvc
        readOnly: true
      backups:
        enabled: true
        existingClaim: nfs-nebula-audiobookshelf-backups-pvc
        globalMounts:
          - path: /metadata/backups
        readOnly: false    
