apiVersion: v1
kind: Secret
metadata:
    name: gluetun-secret
    namespace: gluetun
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:+mEc3JDX/yZk3Nv7R19YNMZyfI+dY0ujqxAVQ2M5v5bLEKpEBV2DxOD2G28=,iv:SNh3SuxKLtLd15Gz/xdonlV+LmH80NAuI9XAu2pjuwA=,tag:ZFRpo7J/7Bk3++pocB4Gzw==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:CfZZ+D0Sjng9v3oQ,iv:k6G2FoF27MAQtYU0o66GmkNi0ESbK5IQ3Jeknxq3Fzk=,tag:67SPQgqVvMa63pbyG3YLyA==,type:str]
    SERVER_COUNTRIES: ENC[AES256_GCM,data:zB9rngpSFJAWpld3xA==,iv:kk9kIrtSitTksEbZLuuTp6yBzC41l7RQnsEfatgJJvo=,tag:kUb7lfhfS2y0vbK4rr6Aeg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-10T15:27:49Z"
    mac: ENC[AES256_GCM,data:/CG37UuGsYzyRZyNG4/b68+7RPFPnYNDxJgPxyeBtWShNTrVNkc9wHA4384avPSp/3pNZpzp3aE74u4zyyytnFOlVHdiTAFM4GE1J4pyE5zVT/JHmyhvZM9ZAAdO0C0BabjzPqrmDwbVVz1IJbigx/9QbWoHJxaQSABIUZOh+C4=,iv:JeSm0nssRUGCakwG1l6DPQLkMWsInBolozaksjTA0yQ=,tag:GvK8EmWvYwlMrGNj+ybfBg==,type:str]
    pgp:
        - created_at: "2026-07-10T15:27:49Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0dSZMvnEisuARAAqqiyhca6BGuckSOUxBzRYW4PWgsj9Tc863XSAddlufOH
            iVoYk3qMGcxHGq+vSbQNwh4TI1/tEjPwB7cRkpqC0+A5PTBZNzX/5yXxOj31JmNd
            ttxvMZyaquoChY1JWc9UvqVQqG2izH0WmHkTk52lUH1prQBo9gPn37BTTCfIJKlF
            4w3EXKNAAgZcfDN8SJKRYajKhvuFpVbvk31rJdpY1qiiuOwK5h0He56u46Tb0hLw
            ZA5uLGRrFG/tj/q8HJhOiM/uvWhgX5+AFi1MACgKnbxJ+UkCgvAomxTbF6d2EP8e
            MCvIF3+KYX45LtO8feT27eO/QKS1P0W8i7OcmT6NYoTbLkztQYn9TofPjWROoeQ6
            ZIsYrzKdjmxwT+48OWMegt0owUazAXqTiQ5jHo/eZbEg1DGOHBmTtz3bUZRIJ1cj
            ZyLkgOs9aXKV04ZP6J7Q2ktOiJ5qQqkf2t+4nlK1CXzKajqGoBMUmZTl5DXZUR80
            t+C7diGJtD/MskCupsJFyjCGwgNSlA/PYzZ+NiyD5AZOUCFipkzGQ3icol/VHEfG
            o4+cKv0txR8/Vd7ldXsw9OscUt1dmJfd5DaeEx+DVN+hxT1LbZghdxGhOQFAR37N
            UWy2YmkC2wS8bhZ5f1Knmmk4TdohlsGhBR9JMbwl1rdnHxFYAwJp82AGfMLOr6zS
            XgGL5IygS6tLjwMzRAhJRNjsOSt58tLwmu9CWvsZG48HW30y65tvR5ziwxMj8yVq
            H7Tf633yA/WJMZln8gPHcuCc3V2JC3zpw9UjiB3chKD36YxF2yGmVe93Iz+CmOM=
            =USjY
            -----END PGP MESSAGE-----
          fp: 1DBC3ACFDB8B1DF2C44CDA23996024D3718273FA
        - created_at: "2026-07-10T15:27:49Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxbwxdi5IniFAQ/+NLY0SxMux00L7rxKgBjXI0ZvOkdRxhsN8wlkjs83Zdb+
            3mhx6fp5jkpB/QuXZ1fQQIN1Xlps8X4QIswyFpseov3Fq19vcp4yNRBLSHvD6MT3
            2Ltm8eo1ZlcC5IeJ07KVlcHSYqpYbi+q4scIQC8ai6w2qgPVpRctwxa7vTcwJhjk
            rHEDBDZIpaEkWIsOk9Lprv0ukMQiW3f1o9HpJXotB3/JW8fgAO5tlmN/MyF3A8kk
            0VL+GKCakGrmD1TR+ajGYxIN9HUPOgit8O9TXtGD7ThfATowA9A7Xjdzuz/+UIZI
            YtOQtAQfxSZuBV1XBfcb9fSDN0guY4/19HJFsylXwS3fnifAQeY3lroYa+4zTXZu
            v3RXAzZ2hdo5PvQcYdabCIk6SZG1Rq09TbDU63R4w5Xt0HUrGqssLHEQVkOa4EKw
            vIaxsxux5AbKsKZ8p5FSxalmm7WJkXAgmw2mNZoOxI9vqgmwbTqL4N5fh+Dn+9WI
            gt80fm8/nXwW0omnnf39FtJUZ4Fu6oZduGhJ3cKWg6yTV/haPt3QdzdeMYWX9KUi
            g6IJG94mkkCo1TrzXpKvI1TxnSn9xAXUiy5vKQAlAC0iyooXWZ5MtgM7OkFUHnAa
            NLNQTIa3vO3DApT0Y/gA/2PWsPJ9pdganRPvrqSHCeSBBR2TIK8QgNWpw94fFYTS
            XgEZZIHiuUszuZcwfT1NEzqzkzs/lefs4RpeZ76vGQFs8x8y0UZXLR+1DzdGlC9n
            L+41iBpACHhfNvW1UME792AN9//onDQcy1QrJSgO8vVIEyZYamPuMoKfedS5ucs=
            =spSz
            -----END PGP MESSAGE-----
          fp: D9F3AF2D9762D61A974DCD3E7B318B162A7DEBC9
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
