---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: obsidian-couchdb
  namespace: obsidian-couchdb
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      main:
        type: statefulset
        # annotations:
        #   reloader.stakater.com/auto: "true"

        containers:
          main:
            image:
              repository: public.ecr.aws/docker/library/couchdb
              tag: 3.3.2
            env:
              COUCHDB_USER:
                valueFrom:
                  secretKeyRef:
                    name: obsidian-couchdb-secret
                    key: couchdb-user
              COUCHDB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: obsidian-couchdb-secret
                    key: couchdb-password
            initContainers:
              init-config:
                image: public.ecr.aws/docker/library/busybox:latest@sha256:3fbc632167424a6d997e74f52b878d7cc478225cffac6bc977eedfe51c7f4e79
                command:
                  - "sh"
                  - "-c"
                  - "cp /tmp/config/*.ini /default.d/; ls -lrt /default.d;"
                volumeMounts:
                  - name: config
                    mountPath: /tmp/config
                  - name: config-storage
                    mountPath: /default.d
    defaultPodOptions:
      SecurityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: "OnRootMismatch"

    service:
      main:
        ports:
          http:
            port: 5984

    ingress:
      main:
        enabled: true
        className: "nginx"
        annotations:
          hajimari.io/enable: "false"
        hosts:
          - host: &host "obsidian-db.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        type: configMap
        name: obsidian-couchdb-configmap
        mountPath: "-"

      config-storage:
        enabled: true
        type: emptyDir
        mountPath: /opt/couchdb/etc/default.d



    resources:
      requests:
        cpu: 48m
        memory: 146M
      limits:
        memory: 2000M

    volumeClaimTemplates:
      - name: data
        mountPath: /opt/couchdb/data
        accessMode: ReadWriteOnce
        size: 10Gi
        storageClass: longhorn
