---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: obsidian-couchdb
  namespace: obsidian-couchdb
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      obsidian-couchdb:
        type: statefulset
        # annotations:
        #   reloader.stakater.com/auto: "true"
      
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: "OnRootMismatch"

        initContainers:
          init-config:
            image:
              repository: public.ecr.aws/docker/library/busybox
              tag: latest@sha256:650fd573e056b679a5110a70aabeb01e26b76e545ec4b9c70a9523f2dfaf18c6
              pullPolicy: IfNotPresent
            command:
              - "/bin/sh"
              - "-c"
              - "cp /config/*.ini /opt/couchdb/etc/default.d/; ls -lrt /opt/couchdb/etc/default.d;"

        containers:
          obsidian-couchdb:
            image:
              repository: public.ecr.aws/docker/library/couchdb
              tag: 3.3.3
            
            env:
              COUCHDB_USER:
                valueFrom:
                  secretKeyRef:
                    name: obsidian-couchdb-secret
                    key: couchdb-user
              COUCHDB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: obsidian-couchdb-secret
                    key: couchdb-password
            
            resources:
              requests:
                cpu: 48m
                memory: 146M
              limits:
                memory: 2000M
            
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5

    service:
      obsidian-couchdb:
        controller: obsidian-couchdb
        ports:
          http:
            port: 5984

    ingress:
      main:
        enabled: true
        className: "nginx"
        annotations:
          hajimari.io/enable: "false"
        hosts:
          - host: &host "obsidian-db.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: obsidian-couchdb
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        type: configMap
        name: obsidian-couchdb-configmap
        advancedMounts:
          obsidian-couchdb:
            init-config:
              - path: /config

      config-storage:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /opt/couchdb/etc/default.d

      obsidian-data:
        enabled: true
        existingClaim: longhorn-obsidian-data
        globalMounts:
          - path: /opt/couchdb/data
