---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: obsidian-couchdb
  namespace: obsidian-couchdb
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      main:
        type: statefulset
        # annotations:
        #   reloader.stakater.com/auto: "true"

        containers:
          main:
            image:
              repository: public.ecr.aws/docker/library/couchdb
              tag: 3.3.3
            env:
              COUCHDB_USER:
                valueFrom:
                  secretKeyRef:
                    name: obsidian-couchdb-secret
                    key: couchdb-user
              COUCHDB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: obsidian-couchdb-secret
                    key: couchdb-password
                resources:
                  requests:
                    cpu: 48m
                    memory: 146M
                  limits:
                    memory: 2000M
        initContainers:
          init-config:
            image:
              repository: busybox
              tag: latest@sha256:c3839dd800b9eb7603340509769c43e146a74c63dca3045a8e7dc8ee07e53966
            command:
              - "sh"
              - "-c"
              - "cp /config/*.ini /opt/couchdb/etc/default.d/; ls -lrt /opt/couchdb/etc/default.d;"
            volumeMounts:
              - name: config
                mountPath: /config
              - name: config-storage
                mountPath: /opt/couchdb/etc/default.d
    defaultPodOptions:
      SecurityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: "OnRootMismatch"

    service:
      main:
        ports:
          http:
            port: 5984

    ingress:
      main:
        enabled: true
        className: "nginx"
        annotations:
          hajimari.io/enable: "false"
        hosts:
          - host: &host "obsidian-db.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        type: configMap
        name: obsidian-couchdb-configmap

      config-storage:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /opt/couchdb/etc/default.d

      obsidian-data:
        enabled: true
        existingClaim: longhorn-obsidian-data
        globalMounts:
          - path: /opt/couchdb/data
