apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: obsidian-couchdb
resources:
  - config-pvc.yaml
  - helm-release.yaml
  - obsidian-couchdb.sops.yaml
configMapGenerator:
  - name: obsidian-couchdb-configmap
    files:
      - ../config/config.ini
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
