---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-example
  namespace: external-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: vault-demo-secret
  data:
  - secretKey: demo # key value in k8s secret
    remoteRef:
      key: secret/foo # path to the secret in vault
      property: my-value # property name of the item in vault (secrets have multiple properties)
  - secretKey: demo2 # key value in k8s secret
    remoteRef:
      key: secret/foo
      property: my-other-value
