---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  namespace: external-secrets
spec:
  provider:
    vault:
      server: ${VAULT_ADDR}
      path: "secret"
      version: "v2"
      caProvider:
        type: "Secret"
        name: vault-connect
        key: ca-bundle
      auth:
        # points to a secret that contains a vault token
        # https://www.vaultproject.io/docs/auth/token
        tokenSecretRef:
          namespace: external-secrets
          name: "vault-token"
          key: "token"
