apiVersion: v1
stringData:
    auth: ENC[AES256_GCM,data:lUuuDeKQjOsouyVPBSNVdSAj7EkOVSNHqYSv/Sp120RtC054tPAtFQ+pOmkzkw==,iv:JVa4Vk8+/Mhh3XfDtTJpMw1zaaBiV7t475EBUIyiIXo=,tag:FFY+CrszvyaOl3JcFIYzzQ==,type:str]
kind: Secret
metadata:
    name: longhorn-basic
    namespace: flux-system
type: basic-auth
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-06-11T20:35:41Z"
    mac: ENC[AES256_GCM,data:Yr/3wfcok0e0ztBtusPWimNaZ7TQMaVWZtec6+BTrDK6sqWp/oD8aOHsUmWhT2cB4rByJPV2FO/c8MkbyoiuailLzSQ6bXmF2gDwLzMIB9rUYqVzK9cnOyKbPdU70OeVjodg60RT/1v2q2wwmFUVfV/5QOoTJgRz3zrREs9Fyfc=,iv:JdbDNxTJs10BiJCeDPLpbsvbiLWvICMroPaoXe5HzGk=,tag:vp/dcujLksgJcKt0n2tGHA==,type:str]
    pgp:
        - created_at: "2022-06-11T20:24:56Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0dSZMvnEisuAQ//az7RSuD8DMkPZ5MuLwZ9ihn6Ibi10nwRsHR6060980u/
            BZ4OV1O5C09BxV2bE46+EipohB6tHXQpOJWsr3yESsR2Uu/KY0PfjN16gGDZScAJ
            RZzyFObutSXjtZz4CkXIT/2SpPXAxT06OZVY12aODB9f4S8DxMjU8mnFCzbH1/Oy
            pIFsj7Uhd/nwgYBoqcEE1LgrtwzaNECkUJLCF3rEr2f+Xra0YGXBqMnoc8dc7qiD
            M8P1SRw0gAmcSeuwyHIFSwdewArs7+qSU+v18M4HJuKVCUxJbmqaRClsOVsvAOQn
            LwR6IMR8knAdmeHvTWzXDKFDzGAQs+Vuzq3r4QGLv+yzOfr/bAJ2ho6/9RGqzy0o
            XaNQySpq/ZJEFdl7u6YHlyHkYeA5l8zvD5BapH3st3d8mmHffMnywHs4IJxLhWRB
            ixxQDYzvTgyRKdZROUX5WPPrLbOHpT04OQ5DABE43gpyWUMR9ZRxJZFAVNkvwOhc
            qKTFpDn6fANxdyy53vm9pWr2BburZ3N1RDD98vOLuECHuoEkx14rJTBmJmZIHguZ
            XTiW1+mp62lwYw375OmnS1aDxqDBkTKuO4YPwDxkEQsZX3YkFxbLdAUA1ZXRqtrD
            pcMcLotScr/P70pn/LOPnilR5s0RBmC9deLf1yA0i0vX9lpG5c4TIPZEAJC0+Z/S
            XAHxr7RT3OE3yBH5LyaAML2ltPWWGaxOosIMd1x8nwLw/2vUdSwGzIoDatCMXKWH
            eLSGZJWrQZd4Rz8muPqe8UJUIfWhBt5DT9O8kcYtClKLfUGICSdXyk1vXI6s
            =VLdw
            -----END PGP MESSAGE-----
          fp: 1DBC3ACFDB8B1DF2C44CDA23996024D3718273FA
        - created_at: "2022-06-11T20:24:56Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxbwxdi5IniFAQ//T32YajNDwEunhTf1JDh0MkZJLVL5SVcmYMyC6c/vdA7N
            TitKCa7FSZtut3+kbE4rLNq+pAlT5/W3FgbUKBa5ZgHIHZ+Q/yaFBRCgcqWaC4cR
            rJ4FknHOynu8E1B5KHjoq3EyREcxtD3CX++KQ2jX5AMXmilZl3y1YfK38xQEERmx
            qblEtQvSS5C6GX8DLzTJe96c7QMreWjqMP9bFovibqOY4LoKvQBtJQXkCFoT44zV
            L5+zkWvl9EgnUkoxDDlLfR3REuL8Hc9uH9qKJRZMIYoIUyR8JfoUA9MBP/lpQ5ub
            erfBLacm4FFfaI46sLlG+C6pev5SgkSxs7jQXiyl/NVwHEk4jpULmKwL5wzi8Sd1
            tGmjQwiSC28MpwTOzLyaJtZwN7UTO/JaIMIydnGGf2SHI0B+51JcrYT5RQIM+P5O
            E3ED5Ex7OUMyq/nVgQM/QUKmwOD5mHsfq30Y9ewWoRac4s5OMpbOAp2xPxsNBlDa
            YANkHaNvh8hBsCvQ1hxXAC41DHATiUMuI3nVEbung7/aYZ7SKiUKSRalkqWoXAhc
            7/QJ+/xGjs1hRFu5vg6b0JZu7gwHFuNValDYfYJvE+fC807/ALZ9JubjCFfAp/9E
            YLUuHf+0gozea4tubhTkZyjELPMrbnvNuWJnQ/YPYB/U6yna5xH4qPcc/+sxYxPS
            XAF8OuYtckOxb/hqsDm3W9hn2iN3+Nc8ZW+8Fdb1M/R/74zL+G1CgvGkS2L+Evmf
            CDLkIw+dSbNaj/0mQbbS/vnW0nArm7f1p09ss8sw9rCK1DjGdYozNM4q4Ejy
            =Q4vl
            -----END PGP MESSAGE-----
          fp: D9F3AF2D9762D61A974DCD3E7B318B162A7DEBC9
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
