---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  chart:
    spec:
      chart: longhorn
      version: 1.3.0
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  values:
    persistence:
      defaultClass: false
    defaultSettings:
      backupTarget: nfs://192.168.09.10:/dumpster/backups/apps/longhorn
      defaultDataPath: /var/lib/longhorn_data
      defaultReplicaCount: 2
      storageMinimalAvailablePercentage: 10
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        # this isn't working, gets a 503
        # https://www.howtogeek.com/devops/how-to-add-http-basic-authentication-to-a-kubernetes-nginx-ingress/
        # https://longhorn.io/docs/1.2.4/deploy/accessing-the-ui/longhorn-ingress/
        # nginx.ingress.kubernetes.io/auth-type: basic-auth
        # nginx.ingress.kubernetes.io/ssl-redirect: false
        # nginx.ingress.kubernetes.io/auth-secret: longhorn-basic
        # nginx.ingress.kubernetes.io/auth-realm: Authentication Required
      host: "longhorn.${SECRET_DOMAIN}"
