---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  chart:
    spec:
      chart: longhorn
      version: 1.3.0
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  values:
    persistence:
      defaultClass: false
    defaultSettings:
      backupTarget: "nfs://${NFS_SERVER_NEBULA}:/dumpster/backups/apps/longhorn"
      defaultDataPath: /var/lib/longhorn_data
      defaultReplicaCount: 2
      storageMinimalAvailablePercentage: 10
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        # Basic Auth - this isn't working, gets a 503
        # https://www.howtogeek.com/devops/how-to-add-http-basic-authentication-to-a-kubernetes-nginx-ingress/
        # https://longhorn.io/docs/1.2.4/deploy/accessing-the-ui/longhorn-ingress/
        # nginx.ingress.kubernetes.io/auth-type: basic-auth
        # nginx.ingress.kubernetes.io/ssl-redirect: false
        # nginx.ingress.kubernetes.io/auth-secret: longhorn-basic
        # nginx.ingress.kubernetes.io/auth-realm: Authentication Required
        # Authentik Authentication
        # https://github.com/goauthentik/authentik/issues/2235
        # https://goauthentik.io/docs/providers/proxy/forward_auth
        # nginx.ingress.kubernetes.io/auth-url: http://ak-outpost-authentik-embedded-outpost.networking.svc.cluster.local:9000/akprox/auth/nginx
        # # nginx.ingress.kubernetes.io/auth-url: https://longhorn.${SECRET_DOMAIN}/akprox/auth/nginx
        # nginx.ingress.kubernetes.io/auth-signin: https://longhorn.${SECRET_DOMAIN}/akprox/start?rd=$escaped_request_uri
        # nginx.ingress.kubernetes.io/auth-response-headers: |
        #  Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
        nginx.ingress.kubernetes.io/auth-url: |-
            http://authentik-outpost:9000/outpost.goauthentik.io/auth/nginx
        # If you're using domain-level auth, use the authentication URL instead of the application URL
        nginx.ingress.kubernetes.io/auth-signin: |-
            https://longhorn.${SECRET_DOMAIN}/outpost.goauthentik.io/start?rd=$escaped_request_uri
        nginx.ingress.kubernetes.io/auth-response-headers: |-
            Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
        nginx.ingress.kubernetes.io/auth-snippet: |
            proxy_set_header X-Forwarded-Host $http_host;
      host: "longhorn.${SECRET_DOMAIN}"
