---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  chart:
    spec:
      chart: longhorn
      version: 1.2.4
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  values:
    persistence:
      defaultClass: true
    defaultSettings:
      backupTarget: nfs://192.168.09.10:/dumpster/backups/apps/longhorn
      defaultDataPath: /var/lib/longhorn_data
      defaultReplicaCount: 2
      storageMinimalAvailablePercentage: 10
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/auth-type: basic-auth
        nginx.ingress.kubernetes.io/ssl-redirect: 'false'
        # https://www.howtogeek.com/devops/how-to-add-http-basic-authentication-to-a-kubernetes-nginx-ingress/
        nginx.ingress.kubernetes.io/auth-secret: longhorn-basic
      host: "longhorn.${SECRET_DOMAIN}"
