apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: authentik-outpost
    namespace: longhorn-system
spec:
    rules:
        - host: "longhorn.${SECRET_DOMAIN}"
          http:
              paths:
                  - backend:
                        # Or, to use an external Outpost, create an ExternalName service and reference that here.
                        # See https://kubernetes.io/docs/concepts/services-networking/service/#externalname
                        serviceName: ak-outpost-authentik-embedded-outpost.networking.svc.cluster.local
                        servicePort: 9000
                    path: /outpost.goauthentik.io