---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  releaseName: plex
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: plex
      version: 6.4.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      # repository: linuxserver/plex
      # tag: 1.30.1
      repository: ghcr.io/onedr0p/plex
      tag: 1.32.5.7349-8f4248874@sha256:e2fa39779d5fe7f10ee92b9c2fc492113c3a397d3ce5032152e0cb6d557a295c
    env:
      TZ: "America/New_York"
      PLEX_CLAIM: ${PLEX_CLAIM}
      ADVERTISE_IP: "https://plex.${SECRET_DOMAIN}, ${PLEX_ADVERTISE_IP}"
      PUID: 2316
      PGID: 2316
    securityContext:
      runAsUser: 2316
      runAsGroup: 2316
      runAsNonRoot: true
    service:
      main:
        primary: true
        enabled: true
        type: LoadBalancer
        externalIPs:
          - "${PLEX_SVC_IP}"
        externalTrafficPolicy: Local
        port:
          port: 32400
    ingress:
      main:
        primary: true
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          hajimari.io/icon: "plex"
          hajimari.io/group: "media"
        hosts:
          - host: "plex.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "plex.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: longhorn-plex-pvc-static
      transcode:
        enabled: true
        type: emptyDir
        medium: Memory
      music:
        enabled: true
        existingClaim: nfs-nebula-music-pvc
        mountPath: /music
        readOnly: true
      video:
        enabled: true
        existingClaim: nfs-nebula-video-pvc
        mountPath: /video
        readOnly: false
      audiobooks:
        enabled: true
        existingClaim: nfs-nebula-plex-audiobooks-pvc
        mountPath: /audiobooks
        readOnly: true
