---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.2.0/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    controllers:
      plex:
        # annotations:
        #   reloader.stakater.com/auto: "true"
        containers:
          plex:
            image:
              repository: ghcr.io/onedr0p/plex
              tag: 1.41.5.9522@sha256:6d393c4eee152100bd6762a94bdd891b8c80c1c8a914a7f906b4097ab69fd557
            env:
              TZ: America/New_York
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /identity
                    port: 32400
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            resources:
              requests:
                cpu: 200m
                memory: 2Gi
                #nvidia.com/gpu: 1
              limits:
                memory: 12Gi
                #nvidia.com/gpu: 1
        pod:
          runtimeClassName: nvidia
          nodeSelector:
            gpu: "true"
          securityContext:
            runAsUser: 2316
            runAsGroup: 2316
    service:
      plex:
        controller: plex
        type: LoadBalancer
        loadBalancerIP: "${PLEX_SVC_IP}"
        ports:
          http:
            port: 32400
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          hajimari.io/icon: "plex"
          hajimari.io/group: "media"
        hosts:
          - host: &host "plex.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: plex
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: longhorn-plex-pvc-static
      transcode:
        enabled: true
        existingClaim: nfs-video-transcode-pvc
        globalMounts: 
          - path: /transcode
      # music:
      #   enabled: true
      #   existingClaim: nfs-music-pvc
      #   globalMounts: 
      #     - path: /music
      #       readOnly: true
      video:
        enabled: true
        existingClaim: nfs-plex-video-pvc
        globalMounts:
          - path: /video
            readOnly: false
      # audiobooks:
      #   enabled: true
      #   existingClaim: nfs-plex-audiobooks-pvc
      #   globalMounts: 
      #     - path: /audiobooks
      #       readOnly: true
      audio:
        enabled: true
        existingClaim: nfs-plex-audio-pvc
        globalMounts: 
          - path: /audio
            readOnly: true
