---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  # dependsOn:
  #   - name: intel-device-plugin-gpu
  #     namespace: kube-system
  #   - name: rook-ceph-cluster
  #     namespace: rook-ceph
  #   - name: volsync
  #     namespace: volsync
  values:
    controllers:
      main:
        # annotations:
        #   reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/plex
              tag: 1.40.0.7998-c29d4c0c8@sha256:7c4501799f0d5f4f94fcb95a8a47b883528354c779a182a9ae4af118a1fc6b10
            env:
              TZ: America/New_York
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /identity
                    port: 32400
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            resources:
              requests:
                cpu: 200m
                memory: 2Gi
                #nvidia.com/gpu: 1
              limits:
                memory: 12Gi
                #nvidia.com/gpu: 1
        pod:
          runtimeClassName: nvidia
          nodeSelector:
            gpu: "true"
          securityContext:
            runAsUser: 2316
            runAsGroup: 2316
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: "${PLEX_SVC_IP}"
        ports:
          http:
            port: 32400
    ingress:
      main:
        strategy: Recreate
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          hajimari.io/icon: "plex"
          hajimari.io/group: "media"
        hosts:
          - host: &host "plex.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: longhorn-plex-pvc-static
      transcode:
        enabled: true
        existingClaim: nfs-nebula-video-transcode-pvc
        globalMounts: 
          - path: /transcode
      music:
        enabled: true
        existingClaim: nfs-nebula-music-pvc
        globalMounts: 
          - path: /music
        readOnly: true
      video:
        enabled: true
        existingClaim: nfs-nebula-video-pvc
        globalMounts:
          - path: /video
        readOnly: false
      audiobooks:
        enabled: true
        existingClaim: nfs-nebula-plex-audiobooks-pvc
        globalMounts: 
          - path: /audiobooks
        readOnly: true
