---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://nextcloud.github.io/helm/
      chart: nextcloud
      version: 2.6.1
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
  values:
    image:
      repository: nextcloud
      tag: 21.0.1-apache
    #env:
    #  OVERWRITEPROTOCOL: 'https'
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/proxy-body-size: 4G
      hosts:
      - host: "nextcloud.${SECRET_DOMAIN}"
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "nextcloud.${SECRET_DOMAIN}"
    persistence:
      enabled: true
      existingClaim: nfs-nextcloud-data-pvc
    cronjob:
      enabled: true
    metrics:
      enabled: true
    nextcloud:
      host: "nextcloud.${SECRET_DOMAIN}"
      configs:
        custom.config.php: |-
          <?php
          $CONFIG = array(
            'overwriteprotocol' => 'https',
            'filelocking.enabled' => 'true',
            'loglevel' => 2
          );