---
# yaml-language-server: $schema=https://gist.githubusercontent.com/a-mcf/4adb544a0629376aefb4b259223e6bcc/raw/28fd33b190394e1777948ec7908f488133721e3d/gistfile1.txt
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-cnpg
  namespace: immich
spec:
  instances: 1
  enablePDB: false
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16.4-v0.3.0
  enableSuperuserAccess: true
  startDelay: 30
  stopDelay: 100
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: restart ##@@ Cannot use switchover with 1 instance
  postgresql:
    parameters:
      max_connections: "600"
      shared_buffers: 512MB
    shared_preload_libraries:
      - "vectors.so"
  storage:
    size: 25Gi
    storageClass: proxmox-csi-ext4-ssd
  monitoring:
    enablePodMonitor: true
  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath: s3://cnpg-backups
      endpointURL: https://s3-premium.${SECRET_DOMAIN}
      serverName: immich-cnpg
      s3Credentials:
        accessKeyId:
          name: cloudnative-pg-secret-garage
          key: garage-access-key-id
        secretAccessKey:
          name: cloudnative-pg-secret-garage
          key: garage-secret-access-key

  bootstrap:
    recovery:
      source: minio
    initdb:
      dataChecksums: true
      postInitApplicationSQL:
        - ALTER SYSTEM SET search_path TO "$user", public, vectors;
        - SET search_path TO "$user", public, vectors;
        - CREATE EXTENSION IF NOT EXISTS "vectors";
        - CREATE EXTENSION IF NOT EXISTS "cube";
        - CREATE EXTENSION IF NOT EXISTS "earthdistance";
        - ALTER SCHEMA vectors OWNER TO "app";
        - GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA vectors TO "app";
        - GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "app";

  # bootstrap:
  #   recovery:
  #     source: freshrssdb-backup-minio
      # recoveryTarget:
      #   targetTime: "2025-10-27T10:00:00" #20251025T220000
  externalClusters:
    - name: minio
      barmanObjectStore:
        wal:
          compression: bzip2
          maxParallel: 8
        destinationPath: s3://cloudnative-pg-backup
        endpointURL: https://s3.${SECRET_DOMAIN}
        serverName: freshrss
        s3Credentials:
          accessKeyId:
            name: cloudnative-pg-secret
            key: minio-access-key-id
          secretAccessKey:
            name: cloudnative-pg-secret
            key: minio-secret-access-key

  # externalClusters:
  #   - name: immichdb
  #     connectionParameters:
  #       # Use the correct IP or host name for the source database
  #       host: immichdb-rw
  #       user: postgres
  #       dbname: app
  #     password:
  #       name: immichdb-superuser
  #       key: password




  # bootstrap:
  #   initdb:
  #     import:
  #       type: microservice
  #       databases:
  #         - app
  #       source:
  #         externalCluster: immichdb

  # externalClusters:
  #   - name: immichdb
  #     connectionParameters:
  #       # Use the correct IP or host name for the source database
  #       host: immichdb-rw
  #       user: postgres
  #       dbname: app
  #     password:
  #       name: immichdb-superuser
  #       key: password

# POST-RESTORE CHECKLIST:
# If restoring from backup, the postInitApplicationSQL commands will NOT run automatically.
# Manually execute these commands after restore:
#   kubectl exec -it -n immich <pod-name> -- psql -U postgres -d app
#   ALTER DATABASE app SET search_path TO "$user", public, vectors;
#   CREATE EXTENSION IF NOT EXISTS "vectors";
#   CREATE EXTENSION IF NOT EXISTS "cube";
#   CREATE EXTENSION IF NOT EXISTS "earthdistance";
#   ALTER SCHEMA vectors OWNER TO "app";
#   GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA vectors TO "app";
#   GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "app";
# Then restart the database pod and Immich deployment.
