---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: old-immich-cnpg-1
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
  storageClassName: proxmox-csi-ext4-ssd
  volumeMode: Filesystem
  volumeName: pvc-d37f66b6-2e2d-4d47-a850-f80afd5f1bce
