---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.2.0/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app open-webui
  namespace: ollama
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      open-web-ui:
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          open-web-ui:
            image:
              # repository: ghcr.io/ollama-webui/ollama-webui
              # tag: main@sha256:d5a5c1126b5decbfbfcac4f2c3d0595e0bbf7957e3fcabc9ee802d3bc66db6d2
              repository: ghcr.io/open-webui/open-webui
              tag: v0.6.2
            env:
              OLLAMA_BASE_URL: http://ollama.ollama.svc:11434
            resources:
              requests:
                cpu: 200m
              limits:
                memory: 2Gi
    service:
      open-web-ui:
        controller: open-web-ui
        ports:
          http:
            port: &port 8080
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          hajimari.io/icon: "fluent-emoji-high-contrast:llama"
          hajimari.io/group: "Gen-AI"
        hosts:
          - host: &host "blunderbot.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: open-web-ui
                  port: 8080
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        globalMounts:
          - path: /app/backend/data
        existingClaim: longhorn-openwebui-pvc-static

