---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-opencloud-storage-users-pv
  namespace: opencloud
spec:
  capacity:
    storage: 2000Gi
  accessModes:
    - ReadWriteOnce
  mountOptions:
    - nfsvers=4
    - port=2049
  nfs:
    path: /tank/user_files/shared/opencloud
    server: "${NFS_SERVER}"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-opencloud-storage-users-pvc
  namespace: opencloud
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  volumeName: nfs-opencloud-storage-users-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-opencloud-data-pv
  namespace: opencloud
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  mountOptions:
    - nfsvers=4
    - port=2049
  nfs:
    path: /tank/appdata/opencloud
    server: "${NFS_SERVER}"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-opencloud-data-pvc
  namespace: opencloud
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: nfs-opencloud-data-pv
