---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ganesha-opencloud-storage-users-pv
  namespace: opencloud
spec:
  capacity:
    storage: 2000Gi
  accessModes:
    - ReadWriteOnce
  mountOptions:
    - nfsvers=4.2
    - port=2049
  nfs:
    path: /opencloud-data
    server: 172.16.10.16
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ganesha-opencloud-storage-users-pvc
  namespace: opencloud
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  volumeName: ganesha-opencloud-storage-users-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ganesha-opencloud-data-pv
  namespace: opencloud
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  mountOptions:
    - nfsvers=4.2
    - port=2049
  nfs:
    path: /opencloud-config
    server: 172.16.10.16
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ganesha-opencloud-data-pvc
  namespace: opencloud
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: ganesha-opencloud-data-pv
