---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opencloud
  namespace: opencloud
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.4.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      opencloud:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 2316
            runAsGroup: 2316
            runAsNonRoot: true
            fsGroup: 2316
            fsGroupChangePolicy: OnRootMismatch
        containers:
          opencloud:
            image:
              repository: opencloudeu/opencloud-rolling
              tag: 3.5.0
            command:
              ["/bin/sh", "-c", "opencloud init || true; opencloud server"]
            env:
              ## -- old OCIS values
              # DEMO_USERS: false
              # OCIS_LOG_COLOR: true
              # OCIS_LOG_LEVEL: info
              # OCIS_LOG_PRETTY: true
              # OCIS_URL: "https://opencloud.${SECRET_DOMAIN}"
              # PROXY_TLS: false
              # STORAGE_USERS_OCIS_ROOT: /data
              # # Authentik OIDC
              # # Auto role assignment:
              # # docs: https://doc.owncloud.com/opencloud/next/deployment/services/s-list/proxy.html#automatic-role-assignments
              # OCIS_OIDC_ISSUER: "https://authentik.${SECRET_DOMAIN}/application/o/opencloud/"
              # PROXY_AUTOPROVISION_ACCOUNTS: true
              # PROXY_OIDC_ACCESS_TOKEN_VERIFY_METHOD: none
              # PROXY_OIDC_REWRITE_WELLKNOWN: true
              # PROXY_ROLE_ASSIGNMENT_DRIVER: oidc
              # PROXY_ROLE_ASSIGNMENT_OIDC_CLAIM: groups
              # PROXY_USER_OIDC_CLAIM: preferred_username
              # #PROXY_USER_CS3_CLAIM: username
              # WEB_OIDC_METADATA_URL: "https://authentik.${SECRET_DOMAIN}/application/o/opencloud/.well-known/openid-configuration"
              # WEB_OIDC_SCOPE: "openid profile email groups"
              ## -- new OpenCloud values
              IDM_CREATE_DEMO_USERS: false
              IDM_ADMIN_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: opencloud-secret
                    key: idm-admin-password
              OC_ENABLE_OCM: false
              OC_INSECURE: false
              OC_LOG_LEVEL: info
              OC_URL: https://opencloud.${SECRET_DOMAIN}
              PROXY_TLS: false
            envFrom:
              - secretRef:
                  name: opencloud-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 512Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    service:
      app:
        controller: opencloud
        ports:
          http:
            port: 9200

    ingress:
      app:
        className: "nginx"
        annotations:
          hajimari.io/appName: "OCIS"
          hajimari.io/group: "Storage"
          hajimari.io/icon: arcticons:owncloud
        hosts:
          - host: "opencloud.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      storage-users:
        existingClaim: nfs-opencloud-storage-users-pvc
        globalMounts:
          - path: /var/lib/opencloud
            subPath: data
      data:
        existingClaim: nfs-opencloud-data-pvc
        globalMounts:
          - path: /etc/opencloud
            subPath: config
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
            subPath: tmp
