---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml

configMapGenerator:
  - name: openwakeword
    namespace: home
    files:
      - resources/hey_glados.tflite

generatorOptions:
  disableNameSuffixHash: true