apiVersion: v1
kind: Secret
metadata:
  name: slack-url
  namespace: flux-system
type: Generic
data:
  address: "${SECRET_SLACK_FLUX_WEBHOOK_BASE64}"
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: slack
  namespace: flux-system
spec:
  type: slack
  channel: fluxcd
  secretRef:
    name: slack-url